### ISSUE TITLE
Drafts folder retains messages after send

### ISSUE THREAD

**Issue by mschaufelberger** [thunderbird/thunderbird-android#1047]
When a message is auto-saved to drafts or when you "save as draft" and then you go back to the message... After sending, the message stays in the drafts folder and then you have to delete it manually. It should be deleted automatically after sending.

This has already been reported long time ago (Dec 2011) for 4.102 and other 4.x versions:
https://code.google.com/archive/p/k9mail/issues/3906

I still can reproduce it with 5.007 and it's rather annoying. I'm using a gmail account with IMAP and android 6.0.

**Comment by wrooot** [comment]
Confirm that. I often end up with copies of drafts after sending messages. Usually this happens when you switch to some other application when you are composing a message. At that point auto-save kicks in. But after you get back to composing it probably thinks that this is a new message, so the old draft is left after sending.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with a recent version of K-9 Mail.
