### ISSUE TITLE
can't compose Mails on fairphone2

### ISSUE THREAD

**Issue by pointout** [thunderbird/thunderbird-android#1161]
### Expected behaviour

Getting editor to write mail or answer in mail
### Actual behaviour

Get only a white page
### Steps to reproduce
1. click on New mail symbol
2. only white screen to see
### Environment

K-9 Mail version: 5.008

Android version: 

Account type (IMAP, POP3, WebDAV/Exchange): imap

**Comment by cketti** [comment]
That is not much information to go on. And since there are no reports this doesn't work with other phones it's most likely a bug in the Fairphone 2 firmware, rather than in K-9 Mail.

If someone is willing to send me a device I'm happy to look into this issue. No promises I'll be able to fix it, though.

Because it's unlikely someone will actually work on this I'm closing this issue for now. I'd be happy to re-open if someone is willing to pick this up.

**Comment by pointout** [comment]
Thanks for your attention. It later worked. Don't know what it was.
