### ISSUE TITLE
FileBackedBody parts are sometimes not saved correctly

### ISSUE THREAD

**Issue by wilzbach** [thunderbird/thunderbird-android#1243]
### Expected behaviour

Tell us what should happen

Content should be displayed 
### Actual behaviour

Tell us what happens instead

Empty view with warnings about the non encryption status. Clicking on reply shows the plain text part of the mail, so it really is just an ui rendering problem. 
### Steps to reproduce
1. Open a multipart mail in k9 
   2.
   3.
### Environment

K-9 Mail version: latest dev release (5.108)

Android version: 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP 

I guess this behavior was probably already reported, but I couldn't find am issue. Sorry. 
Happy to help debugging this if I am the first reporter.

**Comment by philipwhiuk** [comment]
The source of the email would be useful - I've not encountered this problem myself.

**Comment by greenify** [comment]
@philipwhiuk - have a look here http://sprunge.us/KdIH 
Basically every multipart mail that I get is displayed empty.

**Comment by philipwhiuk** [comment]
What version of K-9 are you using - I can't reproduce this in master code.

**Comment by philipwhiuk** [comment]
Hmm odd. I can't reproduce this in my copy of K-9 with a multipart/alternative email from Pi Weekly. Can you enable the debug logging and opening the email again.

**Comment by greenify** [comment]
5.108 -
I also can't open any file - I guess this is related. 
Log below is what happens when I try to open the mail. As it crashes completely when I open a file in any mail, I reported the error via Google play too. 
does this help you? 
Privacy information is replaced with XXXXXX

build.board: shamu
build.bootloader: moto-apq8084-71.15
build.brand: google
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: shamu
build.display: MMB29K
build.hardware: shamu
build.host: wped2.hot.corp.google.com
build.id: MMB29K
build.manufacturer: motorola
build.model: Nexus 6
build.product: shamu
build.type: user
build.user: android-build
version.codename: REL
version.release: 6.0.1
version.sdk_int: 23

04-04 02:57:23.993 I/ActivityManager(2167): START u0 {flg=0x14020000 cmp=com.fsck.k9/.activity.MessageList bnds=[278,2224][457,2364] (has extras)} from uid 10144 on display 0
04-04 02:57:24.168 I/k9      (17584): Running Foreground command 'getFolderUnread:XXXXXXXXh:INBOX', seq = 26
04-04 02:57:24.191 I/k9      (17584): Foreground Command 'getFolderUnread:XXXXXXXX:INBOX' completed
04-04 02:57:24.286 I/ActivityManager(2167): Displayed com.fsck.k9/.activity.MessageList: +277ms
04-04 02:57:32.365 D/k9      (17584): MessageView displaying message MessageReference{accountUuid='6cc9bc83-3a2f-42b0-b3b7-3d7c8fe16e90', folderName='INBOX', uid='16625', flag=null}
04-04 02:57:32.662 E/k9      (17584): Unable to getTextFromPart
04-04 02:57:32.662 E/k9      (17584): com.fsck.k9.mail.MessagingException: File not found
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.mailstore.FileBackedBody.getInputStream(FileBackedBody.java:32)
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.mail.internet.MimeUtility.decodeBody(MimeUtility.java:1021)
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:78)
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.mailstore.LocalMessageExtractor.buildHtml(LocalMessageExtractor.java:153)
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.mailstore.LocalMessageExtractor.extractTextAndAttachments(LocalMessageExtractor.java:117)
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.mailstore.LocalMessageExtractor.decodeMessageForView(LocalMessageExtractor.java:442)
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.ui.message.DecodeMessageLoader.loadInBackground(DecodeMessageLoader.java:46)
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.ui.message.DecodeMessageLoader.loadInBackground(DecodeMessageLoader.java:15)
04-04 02:57:32.662 E/k9      (17584): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
04-04 02:57:32.662 E/k9      (17584): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
04-04 02:57:32.662 E/k9      (17584): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
04-04 02:57:32.662 E/k9      (17584): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
04-04 02:57:32.662 E/k9      (17584): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 02:57:32.662 E/k9      (17584): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-04 02:57:32.662 E/k9      (17584): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-04 02:57:32.662 E/k9      (17584): 	at java.lang.Thread.run(Thread.java:818)
04-04 02:57:32.662 E/k9      (17584): Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.fsck.k9/files/6cc9bc83-3a2f-42b0-b3b7-3d7c8fe16e90.db_att/9602: open failed: ENOENT (No such file or directory)
04-04 02:57:32.662 E/k9      (17584): 	at libcore.io.IoBridge.open(IoBridge.java:452)
04-04 02:57:32.662 E/k9      (17584): 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
04-04 02:57:32.662 E/k9      (17584): 	at com.fsck.k9.mailstore.FileBackedBody.getInputStream(FileBackedBody.java:30)
04-04 02:57:32.662 E/k9      (17584): 	... 15 more
04-04 02:57:32.662 E/k9      (17584): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-04 02:57:32.662 E/k9      (17584): 	at libcore.io.Posix.open(Native Method)
04-04 02:57:32.662 E/k9      (17584): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
04-04 02:57:32.662 E/k9      (17584): 	at libcore.io.IoBridge.open(IoBridge.java:438)
04-04 02:57:32.662 E/k9      (17584): 	... 17 more
04-04 02:57:32.899 D/k9      (17584): No external images.

**Comment by philipwhiuk** [comment]
Oh, so it's caused by us failing to save the file correctly - #1164 discusses it a bit. 

Maybe that's the root cause for all of them. We need to get to the bottom of why we aren't saving the file in the first place..

We should probably check the file exists after writing and then retry or something (possibly crash) if it doesn't. It's a pain to test because I only got it occasionally when I reported that bug.

Taking this one to investigate more.

**Comment by greenify** [comment]
> It's a pain to test because I only got it occasionally when I reported that bug.

It always appears on my device, so let me know if I can help ;-)

**Comment by greenify** [comment]
FYI I downgraded to 5.008 which works perfectly fine...

**Comment by Valodim** [comment]
We should probably handle the case where a file doesn't exist better. I dug into this a bit:

* At the moment, the X_DOWNLOADED_FULL flag is considered reliable. Do we want to keep this assumption? Or change the semantics of this flag to "tried to download this before"?
* There is no preemptive handling for missing files: If a file is flagged as `DataLocation.ON_DISK`, the FileBackedBody will throw an `ENOENT` MessagingException. We could easily add a check for `File.exists()` there and not set a message body similar to the `DataLocation.MISSING` case
* Are there cases where the info might not be available at all? Should we always offer to try downloading a message again (possibly recovering from error states from a bug where the file wasn't written properly), or should we have a permanent error state?

None of this should be decided in the view classes, so I started working on this by moving the "is message fully downloaded" logic into MessageViewInfoExtractor. My take here would be to offer a "Download Message" button again if any body part isn't available (i.e. `getBody() == null`), hoping that the error message the user gets when they try to download the mail again is helpful enough.

Feedback please.

**Comment by cketti** [comment]
Is this still an issue?

**Comment by Valodim** [comment]
Message parts can be re-downloaded if they don't exist now (#1514), but we never figured out how it happened that they weren't saved in the first place. I'm fairly sure that no IOException is thrown during saving, because those are escalated and the entire database transaction is rolled back.

I never got the issue myself. @wilzbach can you test this again with the latest alpha? That would be very helpful.

**Comment by olnabe** [comment]
@Valodim May be the followings have something to do with the not-save-issue:
In the function "renameTemporaryFile" (of LocalFolder.java), the use of "file.renameTo(destination)" hits something: 

https://developer.android.com/reference/java/io/File.html#renameTo(java.io.File)
"Both paths be on the same mount point. On Android, applications are most likely to hit this restriction when attempting to copy between internal storage and an SD card. "

For example, the bug happens when downloading to internal storage and then "rename" the file to SD card. The action fails and nothing is saved to the expected destination.

**Comment by philipwhiuk** [comment]
We need to be strict about calls to `java.io.File` and check every return value to ensure it occurred correctly.

**Comment by philipwhiuk** [comment]
So in LocalFolder we do renameTo:

https://github.com/k9mail/k-9/blob/78d3b011e658fcddd3c23d284b32a16e49f467e3/k9mail/src/main/java/com/fsck/k9/mailstore/LocalFolder.java#L1365

But we already have a class that handles this sort of error. FileHelper.java does a bunch of defensive checks and and other actions in the 'move()' command (which is what we are really doing).

I think also we should consider throwing an IOException here instead of just logging the failure.

Thoughts?
