### ISSUE TITLE
For OpenPGP encryption, email address must be in Android's contacts

### ISSUE THREAD

**Issue by kolAflash** [thunderbird/thunderbird-android#1655]
### Steps to reproduce
1. Create a new mail to some address you have a public key for.
2. Select "Always encrypt and sign" in the encryption menu.
3. Click "Send"
### Expected behavior

Encrypts and sends the mail
### Actual behavior

Says there is not public key for the receiver.
Although there's a public key and everything just works and encrypts if set to "Encrypt if possible".

Remember: The choice "Always encrypt and sign" is important if you want to be sure to encrypt!
### Environment

K-9 Mail version: 5.111

Android version: 6.0 (Cyanogenmod 13)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment]
This is a very general scenario, and I wasn't able to reproduce the issue with the provided steps. Does this happen for anyone else?

**Comment by kolAflash** [comment]
If I enforce encryption...
![tmp_16984-img_20161015_204033855923795](https://cloud.githubusercontent.com/assets/3355089/19414388/a20c5e86-934b-11e6-9c8d-72168855e069.jpg)
I can't send the mail.
![tmp_16984-img_20161015_204118-1569993344](https://cloud.githubusercontent.com/assets/3355089/19414389/aad2543a-934b-11e6-9e6b-391b4ed080b7.jpg)

Nevertheless, if I don't enforce encryption, the mail becomes encrypted anyway.
![tmp_16984-img_20161015_204225-906786560](https://cloud.githubusercontent.com/assets/3355089/19414391/b5bb2570-934b-11e6-8c32-e9f08c3d5d14.jpg)

This is the receivers key.
![tmp_16984-screenshot_20161015-202444548110039](https://cloud.githubusercontent.com/assets/3355089/19414394/c4057ff4-934b-11e6-9ee4-f90e7e2f0709.png)
I don't have gpg@cacert.org in my address book.

Please try to reproduce.

**Comment by Valodim** [comment]
I see the problem. K-9 didn't query the crypto provider for that address, and wrongly assumes that no keys are available. That decision really shouldn't be made where it is currently made. Thanks for the report, I have a fix in mind :+1:

**Comment by Newbie1980** [comment]
Has this been fixed? I experienced this issue too - still using 5.008 and APG as I couldnt find a work around.

**Comment by ettlz** [comment]
I'm using 5.202 and seeing this with OpenKeychain (exactly as described -- mandatory encrypt fails, but encrypt when possible works). Any progress?

**Comment by rugk** [comment]
Why has not this been included in the PGP/MIME milestone?

**Comment by lbort** [comment]
I experienced the same behaviour. I have a key of mail@example.com in my openkeychain, but do get the message about missing keys when I try to force encryption. But **only** if mail@example.com is not part of a contact in my phone. After I created a contact in the adress book of my phone with mail@example.com as email adress, it worked. 
Hope this can be fixed with this help to reproduce. Using 5.203 and openkeychain 4.2.1

Related to this, but offtopic: It would be nice if it were possible to choose from the keys, so that I can encrypt a message to alice@example.com with the key that has bob@example.com in its name. If I know that alice@example is just an alias of bob for example, and bob will be able do decrypt.

**Comment by DarkerSideUK** [comment]
This also happens if you follow the standard openkeychain instructions using adele (https://www.openkeychain.org/howto/#/).

At this point (https://www.openkeychain.org/howto/#/send_compose), instead of being able to select encrypt (or at least the encrypt option with the new UI), you can't select encrypt without encountering the errors described above. It will send (and encrypt) if you select encrypt if possible, but everything indicates that the message will be sent in plain text.

Slightly oddly, if you select the email address a different padlock icon shows (orange with two dots). See screenshot.

![adeleencryptionerror](https://cloud.githubusercontent.com/assets/25220670/22528657/2c616dee-e8cc-11e6-81b3-aa7e473b66f5.png)

**Comment by ettlz** [comment]
I find that if you save the message as a draft first, then re-open it, mandatory encrypt works.

**Comment by prudemar** [comment]
Confirm, I have the same issue, as described.
Setting lock to "Encrypt" fails to send the message and gives the error, "Private mode is enabled but some recipients don't have keys!."

But, using "Encrypt if possible," successfully encrypts and sends the messages.

I have K9 v 5.203, imap, Android 4.4.2

**Comment by Newbie1980** [comment]
I am still on 5.010 because of this problem.
Strange no one is taking notice

**Comment by philipwhiuk** [comment]
I believe @Valodim is working on this given his comment.

**Comment by kolAflash** [comment]
Still an issue in 5.206.

**Comment by ettlz** [comment]
Adding to contacts doesn't work for me -- at least not when sending to myself. (Unless the Samsung contacts app doesn't count.)

**Comment by rugk** [comment]
Still reproducible with v5.208 (LineageOS 14). (And it is annoying and discourages people from using PGP :disappointed:.)

**Comment by Valodim** [comment]
The originally reported issue sort of went away with current alpha, since there is no longer an "opportunistic" and "private" mode. I also remembered to do #2861, which fills contacts from the crypto provider. That should fix this issue.

**Comment by Valodim** [comment]
Pretty sure this is fixed in the current release, closing this issue.
