### ISSUE TITLE
Database size doesn't decrease

### ISSUE THREAD

**Issue by Aviedo887** [thunderbird/thunderbird-android#1917]
Before the update when I would empty the trash the mailbox size would reduce now after the update this is not happening. Even after using the option to clear local Messages the size of the mailbox was only reduced by a very small amount . 

 Before the update the size of my Nina email box after clearing all trash was approximately 92 KB to 127 KB now after deleting all local messages it is still over 1 MB.

 I am using canine mail app for four different email accounts sure the size of the mailboxes is quite excessive .

K-9 Mail version:  5.201

Android version:  6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): POP3 and IMAP

Galaxy Note 5

**Comment by cketti** [comment]
Go to the folder list screen and select "Compact account" from the menu.

In the future please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.

**Comment by Aviedo887** [comment]
This has also been tried and it is not working and the account sizes on all
four email account will not shrink. This has started only since your
current update. Which is why I posted it as an issue not as a request for
support.

And in the future please make sure your updates don't "fix" what isn't
broken.

**Comment by lynnwr** [comment]
This issue should not be closed! I am experiencing this 'bug' since the recent update as well. Compacting does not work, and my data storage number keeps rising even with EVERY message deleted and subsequently removed from Trash. All folders show empty.

**Comment by Valodim** [comment]
If someone has a rooted phone and wants to help out, the output of `/data/data/com.fsck.k9/databases/*` might be helpful to debug this issue.

**Comment by dpthakar** [comment]
I am also facing same issue, I tried clear messages, and later compact account. Still total size is 1.7mb. I am using imap.

**Comment by dpthakar** [comment]
attached database is for my test mail server account, which is after clear & compact is 200kb+ this I believe should be 100kb,
[databases.zip](https://github.com/k9mail/k-9/files/683954/databases.zip)

**Comment by cketti** [comment]
Looks like the full text search tables aren't cleared.

**Comment by Aviedo887** [comment]
@Valodim, my "disrespectful" was in answer to cketti's disrespectful answer to me. Suggesting that in the future I use the the mail list for support requests!  Clearly as a user for more than 10 years I know how to empty the trash or clear messages, which I described in my original post which by the way I made to help your company and its users and not to be chastised or embarrassed publicly.

**Comment by Aviedo887** [comment]
@Valodim, my "disrespectful" was in answer to cketti's disrespectful answer to me. Suggesting that in the future I use the the mail list for support requests!  Clearly as a user for more than 10 years I know how to empty the trash or clear messages, which I described in my original post which by the way I made to help your company and its users and not to be chastised or embarrassed publicly.

**Comment by enrique-henri** [comment]
I have 4 accounts set up.
Prior to recent update, when the accounts were empty each was about 88.3KB.
After update 3 increased to 104.4KB.
The one that did not increase has Storage set to "Regular internal storage" the other 3 are set to "External Storage (SD Card)".

Today I received two emails to the account which was 88.3KB when empty.  After these were deleted that account is now empty showing a size of 92.3KB.

I do not manually delete emails in these accounts as I have all 4 set to "Remove messages when deleted on server".
I have "Compacted" all accounts.

K-9 Mail version: 5.202

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):  POP3  x  4.

**Comment by philipwhiuk** [comment]
@Aviedo887

Given none the attempts you'd made to resolve it was in your original post cketti's request was perfectly reasonable. We have no idea how much experience you have with the application before you tell us.

And we aren't a company. None of us get paid to work on this, we do it in our free time typically because we want a better app on our device. So enough of the expectation that we exist to fix your problems, thanks.

**Comment by HGWT** [comment]
I am having the same issue. I have also tried all the answers put forth in this thread so far with no fix.
I hope they are aware and working on this because eventually this will be a huge problem as size will never decrease.

**Comment by Kent01** [comment]
I am also having the same issue as a number of other users.  The mailbox size especially with the POP accounts does not go back to 88KB after the upgrade.  I don't have any messages in the mailbox.

**Comment by korelstar** [comment]
Some hours ago, [the new version 5.203 of K9 was released](https://github.com/k9mail/k-9/releases/tag/5.203), which should contain the fix for this. Currently, neither Google Play nor F-Droid has the update, but surely, it will not take a long time anymore ... :grinning:

**Comment by Kent01** [comment]
I actually have this updated version and it did not solve the problem

On January 18, 2017 10:12:41 AM EST, korelstar <notifications@github.com> wrote:
>Some hours ago, [the new version 5.203 of K9 was
>released](https://github.com/k9mail/k-9/releases/tag/5.203), which
>should contain the fix for this. Currently, neither Google Play nor
>F-Droid has the update, but surely, it will not take a long time
>anymore ... :grinning:
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1917#issuecomment-273501802

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by korelstar** [comment]
Same for me. Since I can't reopen this issue, I've created a new one: #2103

**Comment by pmontrasio** [comment]
I confirm that 5.203 didn't fix the issue.
I noticed this:
- I enter the Sent folder of my mailbox based on POP3 account, select all messages, delete them.
- The Sent folder becomes empty.
- The number of messages in the Trash folder doesn't increase. It used to, by the number of messages deleted from in Sent.
- I empty Trash and the database decreases only by a small amount, probably because the messages in Trash got deleted but the ones from Sent were not. I always have more messages in Sent than in Trash coming from Inbox.
- Compact account doesn't reduce the space.

I didn't check the code of the fix and I'm not sure I can understand it but could it be that this is what's happening:
- The messages deleted from Sent are marked as deleted there but not actually moved to Trash
- They don't show in Sent but they're still hidden in there and take space in the database? 

Do I have a way to check that as a user? My phone is not rooted and I can't find the database. It's probably in some system directory I can't access to.
