### ISSUE TITLE
Missing buttons/text

### ISSUE THREAD

**Issue by JDJADU** [thunderbird/thunderbird-android#1984]
### Expected behavior
It should work as in the previous version

### Actual behavior
On some messages the top line (with the back button, K9 icon and subject description) is missing
On some messages the bottom line (with the prev/next, delete,... and More buttons), is missing
On some messages the line with the sender name is missing.

All these problems are message-dependent. If the top line is missing on the message A, it is always missing on the message A and vice versa.
If the top line is missing in portrait then in landscape it is not missing and vice versa.
The buttons are there but are invisible; if the button is pressed then the appropriate action is activated and the button appears. Pressing for example More (three dots) displays three dots and the icon on the left side of More. Moving to the left displays the remaining invisible icons/buttons
Changing setting in Global setting-Display has no effect - except the Fixed font. With this option on, it is much worse and problem is with almost every message.
When the problematic message is displayed, in the beginning everything is OK but in a fraction of a second black rectangles "cover" and hide the buttons.
With the Split option on the black rectangles cover part of the left message list.
When the snap of the screen is activated, all the missing items are displayed and the photo is absolutely perfect.
When the screen of the phone is switched off while displaying a message with some missing buttons and then is on again, the problematic message is displayed correctly.

The photos are not very good but illustrative enough:
![jpg-k-9-2](https://cloud.githubusercontent.com/assets/24942865/21693202/5095a970-d380-11e6-891e-4fdb5594ff91.jpg)
![jpg-k-9-3](https://cloud.githubusercontent.com/assets/24942865/21693201/5094f52a-d380-11e6-9624-878adc0922cf.jpg)
![jpg-k-9-1](https://cloud.githubusercontent.com/assets/24942865/21693200/509417b8-d380-11e6-8162-9a791fed98a3.jpg)

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.201
Android version:
4.4.4.
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by JDJADU** [comment]
Version 5.202 added new option - the lower half of the buttons is visible. Now it is obvious that the buttons are covered with black area (the black theme is on) when the message body appears.

**Comment by ssb22** [comment]
Reproduced on Sony Xperia Z Ultra, also running Android 4.4.4 (all icons are on the lower part of the screen on this screen size).  Sometimes only the right-hand half of the lower icons display (i.e. just Reply, New and Menu, or just New and Menu).

With the "Show GPU view updates" option turned on under Developer Options, it can be seen that the missing icons are not drawn at all.  (i.e. screen simply isn't drawn: rules out 'incorrectly drawn in background colour' or similar).

Reproduction is much more likely if the message content is too short to reach to the bottom of the screen.  If it's a large message with more than 1 screenful, the icons usually show OK.

I tried different settings of Message body font size: no effect.

**Comment by ssb22** [comment]
Further to my previous comment, the 'Sometimes only the right-hand half of the lower icons display' situation seems to happen only if Animations are turned on.  If Animations are turned off, the icons consistently don't display at all for the affected short emails.

Setting Dark theme has no effect on this problem.

**Comment by ssb22** [comment]
For what it's worth, I read through `git log -p` from January 5 back to December 12, and I didn't see any changes to do with view updates on the message screen.  Nevertheless I have not noticed this problem before.  Strange.

If I could build the thing myself, I might be able to do a `git bisect` and locate the exact commit that somehow changed things.  But right now I can't get Android Studio running on my machine, which means I can only build Android source that works under the old Eclipse ADT from 2015 :-( sorry I'm not being much help.

**Comment by JDJADU** [comment]
Till 5.201 there were no display problems. I think that there had to be some updates on the message screen because now the attachments are displayed differently.

**Comment by ssb22** [comment]
Do you mean version 5.201 was OK, or version 5.201 was the first version with the problem?  We need to work out which git date that corresponds to (perhaps my December 12 date was wrong).  Unfortunately I can't seem to find the app versions in the git log—they must have been kept separately—does *any*body know which date we should be looking at?

**Comment by ssb22** [comment]
When trying to build with `./gradlew assembleDebug` I got "java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0".  [According to StackOverflow](http://stackoverflow.com/questions/37312404/getting-error-when-trying-to-run-new-project-in-android-studio-2-2-1) this can be worked around by downgrading the gradle requirement to 2.1.0 instead of 2.2.2 in the `build.gradle` file. I tried that and was told to also change the `distributionUrl` in `gradle/wrapper/gradle-wrapper.properties` to `gradle-2.10-all.zip` (K-9 set it to 3.1).  After making this edit and setting `ANDROID_HOME`, I got the message "failed to find target with hash string 'android-24' in: /usr/local/android".  So I changed 24.0.3 to 23.0.3 in `gradle.properties`, and it threw "java.lang.IllegalStateException: buildToolsVersion is not specified." A Google search for that error message shows a few potential solutions but none of them seem to be applicable here.

**Comment by cketti** [comment]
You probably need to update to JDK 8.

**Comment by ssb22** [comment]
JDK 8 refuses to install.  I'll probably have to set up some kind of VirtualBox image first.

**Comment by ssb22** [comment]
OK, here's what I did:
* Start with Debian 8 (Jessie) installed in VirtualBox
* As root, add a `jessie-backports` line to `/etc/apt/sources.list` (I used `deb http://ftp.uk.debian.org/debian jessie-backports main`) and do `apt-get update && apt-get install git openjdk-8-jdk && apt-get remove openjdk-7-jre openjdk-7-jre-headless`
* Go to http://developer.android.com/sdk and download `android-studio-ide-145.3537739-linux.zip` (it didn't work just to download `tools_r25.2.3-linux.zip`: that failed with "you have not accepted the license" during `gradlew`)
* From `android-studio/bin` run `./studio.sh`, don't import settings, custom install, Platform 25 (no choice).
* Configure / SDK Manager, remove Platform 25, add Platform 24, accept terms
* `git clone https://github.com/k9mail/k-9.git`
* `cd k-9`
* `export ANDROID_SDK=~/Android/Sdk`
* `./gradlew assembleDebug`
and *finally* it gives me a `k9mail/build/outputs/apk/k9mail-debug.apk` which I can copy back to my real box and run `adb -d install k9mail-debug.apk`, and K9 still opens OK on my Android 4.4 phablet, and yes I can still reproduce the missing buttons issue with this build.

Now all I need is a known "good" commit, and I can try a `git bisect`.

**Comment by ssb22** [comment]
And I just realised I have been looking only at the `master` branch, whereas the 5.2 releases are on a branch called `5.2-MAINT`. So I did a `git checkout -b 5.2-MAINT origin/5.2-MAINT` and I can finally see in the git log that Version 5.201 was released on December 30th in commit 1ef87e9f5e0c1f21ae8f69574c526fc1f78097f0 and Version 5.200 was released on December 26th in commit 74ea62853e6e135b32a0241446e6e3b4fe33164f.  I'm feeling rather tired now but at least I'm all set to start the `git bisect` another time.

**Comment by ssb22** [comment]
…except I did just look through the *branch* git log (in case there was something I would notice there that I didn't notice on the master log), and didn't see any relevant changes between 5.200 and 5.202.  Are we *absolutely sure* that 5.201 or 5.200 is the "good" version?  (I was hoping Jdjadu's post above means "version 5.201 was OK", but I'm rather afraid might mean "it was OK *until* I upgraded to 5.201", which means we have no idea which version they upgraded *from*.)

**Comment by ssb22** [comment]
Oh I see the comment has been changed (unless my memory is faulty) and it now clearly says Version 5.201 was bad.  And we have no idea which version they had before that :-( so we still don't have a known "good" version.

**Comment by philipwhiuk** [comment]
Yeah, the problem here for me is it's sporadic to reproduce and I believe we got the odd report of it in the beta. So potentially any change between the last 5.1 release and current. Which is, a lot.

The only things we really have to narrow it is:

* It's, to my knowledge only appeared on 5.2x
* It's, to my knowledge only appeared on message view / list
* It's related to the display the actionbar

However I have just found a small bug that may be causing it.

**Comment by ssb22** [comment]
The neighbour downstairs is doing midnight DIY and I can't sleep, so I tinkered a bit more.  On the master branch,
* Version at commit 942032f360a0dc20b562460bc5f9ab8c3976fe39 on December 10 still has the bug
* Version at commit 00e63fc8f1346328d58d9e926467ee2e66ffcb48 on December 5 still has the bug
* Version at commit de13e10be1423ebc03730aa211780b2141943bab on November 16 still has the bug
* Version at commit 54c0ac6e7b1d7b4e5f71e85b166a0935d6bd1310 on October 31 still has the bug
* Version at commit a2b545fc39fb80128b3353ef0308732496f7fed4 from September 30 still has the bug
* Version at commit dcd27d9f56547dd43f4fba35e683eee5602ee6cb from August 30 said "failed to find Build Tools revision 23.0.3" (the ADT let me install the Android 23 SDK instead of the Android 24 one, but not the Build Tools, and `ln -s` didn't fool Gradle) so I had to change it in `build.gradle`, and it *still* has the bug.

I certainly don't remember the bug being present that far back in the *release* version.  And yes I did check that the app on my phone really is being updated, and yes I am making sure to run the debug version not the release version (they are installed in parallel).  Unless it's something to do with the version of the Build Tools in use (which seems unlikely), this isn't making much sense….

**Comment by ssb22** [comment]
I did a `git pull` and I'm sorry to report your latest commit did *not* make the bug go away for me.  And it's gone quiet now so I'm really going to try to get to sleep, need to get up in the morning...

**Comment by JDJADU** [comment]
Yes, 5.201 was the first problematic version. I did not have 5.200 (it was not on Google Play or it was not offered to me). I do not have automatic updates but I update every time the upgrade is offered so I did not miss any available version.

I do appreciate your effort to solve the problem. The best result is to find the reason and fix it. On the other hand, if it is not easy or possible - what about to add a full redraw after displaying the message because we know that switching screen on/off or making a photo has a positive effect - error is gone. This can be also an option in Settings.

**Comment by ssb22** [comment]
I tried adding `mActionBarMessageView.invalidate();` and `invalidateOptionsMenu();` to `showMessageTitleView()` in `activity/MessageList.java` but it didn't help. Either I'm doing the wrong thing (we need to figure out how *exactly* to force the kind of redraw that happens when you take a screen shot) or I put it in the wrong place. I don't really know Android programming that well...

**Comment by ssb22** [comment]
Oh and here's an [unanswered StackOverflow question from 2012](http://stackoverflow.com/questions/9396840/get-the-actionbar-to-redraw-itself) about making action bars redraw themselves. Now it's 2017. This is not encouraging :-(

**Comment by philipwhiuk** [comment]
My guess is it'll be fixed by the Material changes if not before.

**Comment by JDJADU** [comment]
Version 5.203, the problem is still there, as expected.

**Comment by jimktrains** [comment]
I've noticed 2 things:

- If I toggle the power button to turn the screen on and off, the action bar? (bottom bar with prev/next delete, reply) comes back.
- If I hold the power button to get the screen shot/reboot menu, it comes back
- If I swap applications and swap back, it comes back

I don't know enough about the android drawing system to know what that means as far as where in the code to look. (or if it's even helpful at all).

**Comment by philipwhiuk** [comment]
Closing as duplicate.
