### ISSUE TITLE
Notifications sometimes show unread count and sometimes show new count

### ISSUE THREAD

**Issue by Hawk777** [thunderbird/thunderbird-android#2018]
In the past, a notification would always show the number of new mails (I don’t *think* it actually used the IMAP \Recent flag, rather it counted messages that are not \Seen and which K9 had not known about previously). 

Now, sometimes a notification tells me there is 1 new message, and sometimes it tells me there are over 300 (the number that are not \Seen, even if they are very old, I think).

**Comment by ArchangeGabriel** [comment]
Related to https://github.com/k9mail/k-9/issues/1885.

**Comment by Hawk777** [comment]
The title of that issue didn’t make it obvious (I did check the list first), but this might even be considered a duplicate of that ticket. I’ll leave that up to K9 devs though.

**Comment by philipwhiuk** [comment]
I think it's worth leaving it open. If the same fix solves both problems great, but I'd rather have a few more smaller tickets than huge ones that are hard to get fixes and difficult for new people to work on.

**Comment by elhennig** [comment]
The notification with unread messages shows up even if there are no new messages. I guess this behavior started when you introduced the option the filter by own messages and contacts.
In my opinion if would be better to have the choice to either show notifications for new, unread or both.

**Comment by EQXTFL** [comment]
I see similar things. Since the last update, the notifications are not updated in every case. Sometimes a notification will stay, even after the related message has been read or deleted. Do we know a way to reproduce this?

**Comment by Hawk777** [comment]
I always saw notifications staying even after the message was read (if the message was read in another client—if K9 is opened the notifications always disappeared right away), even before 5.200. This happened only occasionally, not all the time; AFAICT it seems to happen with roughly the same frequency now as it did then.

**Comment by ArchangeGabriel** [comment]
Actually I think there is a whole class of issues with notifications at the moment:

– Notifications showing unread messages instead of new messages. For me it seems to be linked with screen locking state: screen locked or unlocked, new messages arrives, the notification says the number of new messages. But if screen is locked, on unlocking it now shows the number of unread messages instead (and in all folders, not just INBOX).
– Notifications going to folder view instead of INBOX. This seems highly correlated to previous issue, since when this is happening when I have the number of unread messages. With new messages notifications instead, it works OK. Seems logical to me since it means going to the common root of unread messages.
– Notifications not being dismissed after message being read. This seems a different unrelated issue AFAICT.

**Comment by philipwhiuk** [comment]
@ArchangeGabriel Please don't add more issues into the same report. It makes stuff impossible to close and fix. We already have other issues for those ones.

On topic, the core problem here is that the behaviour is unspecified and the domain language unclear.

We need to review all notifications and use 'New' or 'Unread' correctly and decide what we actually want the behaviour to be.
