### ISSUE TITLE
Global display settings changes are not applied immediately

### ISSUE THREAD

**Issue by petko** [thunderbird/thunderbird-android#2136]
### Expected behavior
When I change some of the display settings (hiding the stars, showing the checkboxes) and go back to the current inbox, I expect the new settings to be applied to the current folder immediately.

### Actual behavior
If I am in a folder and change the global display settings and then go back to the folder, they are not applied.

### Steps to reproduce
1. Open an IMAP folder
2. Click ... > Settings > Global Settings > Display
3. Change an option, for example Hide Stars From the Message List
4. Click the back button on your phone
5. You will go back to the folder, but the stars are not hidden
6. In order to apply the settings you have to exit and folder and enter it again

### Environment
K-9 Mail version:
5.203

Android version:
4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by sukhbir-singh** [comment]
I am working on this issue.

**Comment by cketti** [comment]
Developer notes: A fix for this should call `Activity.recreate()` when the theme is changed in the settings screen.
Existing activities need to check in `onResume()` if a relevant display setting was changed since the last time the activity was resumed and call `recreate()` if necessary.
For some display setting changes simply invalidating affected views might be enough.
