### ISSUE TITLE
Problem with opening attach pics and Viewing embedded pics

### ISSUE THREAD

**Issue by TafCaf** [thunderbird/thunderbird-android#2699]
### Expected behavior
Open pictures to gallery / Show new embedded picture in email instead of some kind of stored picture

### Actual behavior
In the past I have had some file types not open to the correct app from K9 mail, but now even pictures (jpg) will not open with the right app or even give me a choice of app to open with.  I have double checked that the wrong apps are not “default” and have also cleared all defaults with no luck.

Also have an issue where an embedded preview picture is sent by my security cameras, but K9 keeps showing it as the same picture even though the security cam is sending different pictures (maybe with the same name?).

### Steps to reproduce
1. Have security cam auto send different pictures with the same name
2. Send embedded pictures with same name
3.  Try to view and open these pictures

### Environment
K-9 Mail version:  5.207

Android version:  4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):  pop3

**Comment by philipwhiuk** [comment]
In terms of the embedded previews, it's possible that the way the caching in the WebView works causes this.

In terms of the external opening, it's likely they don't properly support content URIs and assume there's a file to open, instead of an input stream. As for why you don't get a choice - that depends on what apps you have that claim they can handle the MIME types we provide.

**Comment by TafCaf** [comment]
So is there any way to change the "caching in the WebView" to fix this?

**Comment by philipwhiuk** [comment]
I'll have a look. Is it the same image being shown in different emails, or the same image being shown multiple times in a single email?

**Comment by TafCaf** [comment]
different images in different emails, but they show as the same image from one email to the next (I am guessing because the sending program doesn't change the name of it?)

**Comment by philipwhiuk** [comment]
Okay thanks. So we are doing the right thing in terms of providing different image files.

It looks like there's some API calls we can use:

```
webView.getSettings().setAppCacheEnabled(false);
webView.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
webView.clearCache()
```

**Comment by TafCaf** [comment]
Ooooh.  Um... do I need to know how to make that happen?

**Comment by philipwhiuk** [comment]
No, that's the point of my PR - to add them.

**Comment by TafCaf** [comment]
Oh!  Thank heavens.  I write code, but have no idea where I would put that.  LOL
Let me know when to do some testing on it.  :)

**Comment by Trogel** [comment]
I just tried it: Clearing the cache will actually cause external images to be lost after an orientation change. The reason is that network data is currently always blocked after a save/restore cycle; see also #2685.

I had to tweak it a bit, but now PR #2716 fixes this when combined with PR #2721.

**Comment by cketti** [comment]
There doesn't appear to be an easy way to disable caching of inline images on all supported Android versions. But given that the Content ID is required to be globally unique, I'd rather not waste more time on supporting this on older Android versions.

@TafCaf: Since you're on an Android version lower than 5.0 you won't benefit from the caching fix. You could work around this by long-pressing the image, then selecting "View image" to open the image in an external image viewer.

**Comment by TafCaf** [comment]
Okay.  Thank you a lot for looking into it.  I will try the “view image” option.

**Comment by cketti** [comment]
Since K-9 Mail 5.7xx only supports Android 5.0 and newer this issue can be closed.
