### ISSUE TITLE
Account Settings (PreferenceActivity) doesn't support in-app language feature

### ISSUE THREAD

**Issue by Meteor0id** [thunderbird/thunderbird-android#3013]
### Expected behavior
When switching from Dutch to English, all text is now shown in English.

### Actual behavior
Going into an existing account, and going into accunt settings, show everything in English except the title of the account settingsd menu, which is still shown in Dutch.

### Steps to reproduce
1. Set up K9 with the Dutch language
2. Switch to English
3. Close K9
4. Open K9
5. Close K.. nah just kidding
6. go into an existing account, settings, account settings
7. look at title and scream in amazement

### Environment
K-9 Mail version:
5.400

Android version:
7.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
That's because Android doesn't really support per-app language settings. It appears the system language is used when setting the screen title instead of the one configured in K-9 Mail.

We'll keep this in mind when doing the UI overhaul. Chances are switching away from `PreferenceActivity` will fix this bug.

**Comment by cketti** [comment]
This is no longer an issue in `master`.
