### ISSUE TITLE
tel URI links are stripped by HtmlSanitizer

### ISSUE THREAD

**Issue by ivenae** [thunderbird/thunderbird-android#3065]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
Click to call link does not work since a few weeks. A click to call link is a hyperlink which is opened by a dialer-application. For Exampel: `<a href="tel:004955555">55555</a>`

### Actual behavior
Tell us what happens instead
Link is shown as plain text

### Steps to reproduce
1. Create a new mail with html code` <a href="tel:004955555">55555</a>` in it
2. Check for new mails in an old version of k9, or in thunderbird and look for the link
3. Check with current k9 mail, link is shown as plain-text.

### Environment
K-9 Mail version: current 5.403

Android version:
7.0 (motorola) and 7.1.2 (lineage) verified

Account type (IMAP, POP3, WebDAV/Exchange):
does not matter

**Comment by philipwhiuk** [comment]
Our HtmlSanitizer has:

`.addProtocols("a", "href", "ftp", "http", "https", "mailto")`

We probably want to add

`.addProtocols("a", "href", "ethereum", "bitcoin", "rtsp")`

just to match our plaintext stuff in UriLinkifier.

As for TelURI, that and maybe even SIP seem like reasonably widely used standards for inclusion, especially on mobile.

I'm wary of this continuing with this approach though. Stuff like steam has a URI syntax. And there's the explosive growth of cryptocurrencies - how long before we add litecoin, heck even stuff like dogecoin. Where do we draw the line? Do we even try?

It would be nice if these were configured in Preferences rather than in code. Then people can just add and enable whatever they like.

There is for example a good case for not enabling links for Tel URIs on grounds of safety. One click and you're dialling a premium rate line.

I'm not sure what the best approach is here.

**Comment by philipwhiuk** [comment]
NB: Just adding tel and maybe sip to the whitelist is probably a regression fix. But it's kind of an ugly one.

**Comment by hfinp** [comment]
While I do use tel links on web pages, I have never seen it in legal non-spam emails yet.

**Comment by ivenae** [comment]
I use click-to-call Links in E-Mails i send to my own e-mail address from my PBX to my mobile phone to call back. The AVM Fritzbox router also make use of it.
I never got any spam mails with a click-to-call link in it, and the click to call link in K9 worked perfektly since i use android with K9 (2011).
I cannot understand why someone cut it off and want to tell me that it never should have worked.

**Comment by hfinp** [comment]
You're right, I just recognized the AVM router/Pbx does it like this. So keeping the tel links would be really useful.

**Comment by philipwhiuk** [comment]
Cutting it off was an accident. We switched to a newer HTML sanitisation system (we have to sanitise HTML to avoid running bits of JavaScript - it's a security issue). The newer parser also handles Microsoft Word style rubbish a lot better.

In the process the parser also restricted too much. We're adding them back in but now we have control over it we can make sensible decisions.

One of those is 'would a user be okay with a call being made' when clicking on an email link. Calling obviously costs money and spammers may not make it obvious.

Clearly your use case makes sense but I'd ideally also like to make work for everyone. Hence enhancement and bug.

**Comment by ivenae** [comment]
I just want to add the following thought:

While clicking an internet link my browser will directly open a website and maybe run exploited code, sending personal data, etc.

While clicking on a click-to-call link, the phone-number is handed over to the android dialer application. I have to proceed within the dialer application to call the number.

This might be different on a desktop-system, where i can configure my sip-dialer to directly call the destination number.

With this in mind, i would prefer making http-links non-clickable over the tel-links.
