### ISSUE TITLE
Reply always from default identity

### ISSUE THREAD

**Issue by asbach2** [thunderbird/thunderbird-android#3252]
### Expected behavior
I use three identities for one email adress, say A@domain.com, B@domain.com, C@domain.com.
The default is A@domain.com. So if I start writing an email, sender will be A@domain.com
If I'm going to reply an email which was sent to B@domain.com, the sender B@domain.com should be used.

### Actual behavior
This is what happend in the last.
Now I'm with v5.403 and sender is always A@domain.com.
I've no idea when the problem showed up the first time but I mentioned it two weeks ago. But I haven't updated K-9 for a long time before.

### Environment
K-9 Mail version: V5.403

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): POP3/IMAP

**Comment by ufdemt15** [comment]
I came here to post about the same thing. Granted you can click on the sending identify to change it, I would swear in the past there was a settings option to always default to the account you working from. I've been through every setting menu and can no longer find the setting. I'm it's a pain when you try to keep accounts separate but it defaults to another account because you forgot to change it.

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
