### ISSUE TITLE
Deleting messages in Trash doesn't work

### ISSUE THREAD

**Issue by terr72** [thunderbird/thunderbird-android#3355]
### Expected behavior
When deleting a message from the trash, it should be deleted from the server.

### Actual behavior
Deleting a message from the trash makes it only disappear locally in K9 Mail.
When the refresh button is hit afterwards, the messages show up again.
Deleting these refreshed entries finally delete the entries on the server as well.

### Steps to reproduce
1. Register a Yahoo account (might be related to other IMAP providers as well)
2. Use K9 Mail to move a message to the trash.
3. Switch to the trash, delete the message and hit the refresh button,
4. The message shows up again in K9 Mail. since it's still in the trash folder of the server.
5. Delete it for the second time to make it finally disappear both locally and remote.

### Environment
K-9 Mail version: 5.503

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by terr72** [comment]
My bug report seems to affect also non-Yahoo accounts since there are similar reports which were confirmed by other users: 
https://github.com/k9mail/k-9/issues/1748
https://github.com/k9mail/k-9/issues/2705

This should be pretty easy to reproduce even without a debug log.

**Comment by takiainen** [comment]
I can confirm this, I have the same issue. I'm using latest F-droid K9 version on Android Oreo.

**Comment by michaelof** [comment]
I can confirm this issue. Latest F-Droid K9 in Android 6.0

And this issue has an UGLY side effect: 

Although doing nearly nothing, as the emails are not deleted serverside, K9 needs an eternity to get the trash folder in sync with the server folder.

Yes, I've read https://k9mail.github.io/documentation/faq.html#anchor8, and yes, I have a cheap smartphone with just 1GB RAM, plus a for sure slow storage, as I'm using Adoptable Storage to extend the only 8 GB internal storage. 

So I'm fine that everything runs somewhat more "gemütlich" on my device.

BUT: 

One of my imap email accounts, own dovecot on my VPS, has ~ 35.000 stored emails. yearly archive folders. All history synced to K9, but only the first 32K foreach email.

When trying to delete from trash, as described above, the first "delete" - which doesn't delete anything on server, has some sort of exponential time consumption, at least on my phone. If I "delete" max. 10 emails in one shot, it takes ~1-2 minutes to be finished. I've tried today to delete 420 emails from trash today, this action is running now for more than 2 HOURS - this is crazy!

The described "refresh" after the local-only deletion takes an eternity, if there are server-side mails, also crazy. 

As a workaround, I'm deleting trash emails FIRST on the my server, e.g. by Thunderbird, takes milliseconds, or via Browser/Roundcubemails, also milliseconds. Then, with an empty trash, I "delete" all trash msgs in K9. Once they're are gone, I perform an refresh of the now empty-on-both-sides trash, whichs runs acceptable fast.

Refreshing existing local K9 trash mails with an empty server trash also takes an eternity, so I must delete (locally) instead of resfreshing.

And these HOURS-running jobs are only possible, if I have the time to let the smartphone ONLY do these  trash deletions. Any other app activity, e.g. a call, starting browser etc., will immediately swap out K9 and interrupt the Sync.

This
is 
painful
:(

**Comment by cekor** [comment]
Same here with same side effects.
Expected behaviour slightly less ambitious: deleting in K9mail should at least prevent locally deleted mails from popping up back again in K9 mail each time one refreshes it.
Actual behaviour: all deleted mails show back up locally after Refresh, but cannot be deleted at all, contrary to what Terr72 manages to do.It's been happening since I downloaded this version of K9 (hadn't updated in quite a while and don't really remember which version I had last).
Software versions : K9mail 5.0403 - Android 7.
Whether or not the deleted messages stay on the server (I have non Ya.hoo), the deleted messages shouldn't download again to the device - trash slowing down everything, not trashed, bandwidth useage absurd, etc..

**Comment by cschuber** [comment]
Additionally, emptying the Trash file on the server (that runs dovecot -- I run my own mail server downstairs) and selecting & deleting all items in the Trash folder in K9, the emails magically show up again even after the file has been emptied. The emails have been verified deleted through mozilla thunderbird but in K9 they persisted until I selected all emails in Trash and deleted them again.

It appears that K9 is not deleting email on the server, only locally. Next time it syncs it fetches them again. My workaround is to log into the server as root (my imap account's shell on the server is /usr/sbin/nologin as a security measure) and cp /dev/null Trash, then sync K9, select & delete all items in Trash in K9, then sync K9 again.

Hope this provides more information to diagnose this issue.

**Comment by justinacolmena** [comment]
On February 9, 2019 9:03:36 AM AKST, Cy Schubert <notifications@github.com> wrote:
>Additionally, emptying the Trash file on the server (that runs dovecot
>-- I run my own mail server downstairs) and selecting & deleting all
>items in the Trash folder in K9, the emails magically show up again
>even after the file has been emptied. The emails have been verified
>deleted through mozilla thunderbird but in K9 they persisted until I
>selected all emails in Trash and deleted them again.
>
>It appears that K9 is not deleting email on the server, only locally.
>Next time it syncs it fetches them again. My workaround is to log into
>the server as root (my imap account's shell on the server is
>/usr/sbin/nologin as a security measure) and cp /dev/null Trash, then
>sync K9, select & delete all items in Trash in K9, then sync K9 again.
>
>Hope this provides more information to diagnose this issue.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/3355#issuecomment-462065732

Just brainstorming from my own experience with this issue.

From the list of folders in an account, there is an option on the menu from the lower right corner to empty trash. That works. Otherwise, when a message is "deleted" from any other folder, it is not actually deleted, but moved to the trash folder, as one would expect.

There might to be a missing case in the code that falls through and attempts to trash a message that is already in the trash folder, although one would probably expect the "delete" option for an item in the trash folder to permanently delete it. The problem seems to occur at sync time, when messages no longer present locally are "moved to trash" on the server, even if in some cases they really should be permanently deleted.

Someone was apparently at one time coding for safety to save a copy of the message in cases of doubt, but IMAP is not that easy or trivial to code. I am able to confirm this issue because I tend to move in and out of internet service and sometimes read email, compose replies offline, and sync later.

-- 
Una Milicia bien regulada, estando necesaria a la seguridad de un Estado libre, el derecho del pueblo de tener y de portar Armas, no será infringido.

https://www.colmena.biz/~justina/contacto.php

**Comment by cschuber** [comment]
Indeed, empty trash does work. I didn't bother looking for that option in the folder view. :\

**Comment by michaelof** [comment]
Having been also affected by #3905, which has been a sdcard issue, and having a new "named brand" sdcard as a replacement for a no-name one, speed of deletions is MUCH faster now, same size on disk, same # of emails in folders etc. Much faster deletions, but still very slow. Only between 10-30 seconds, instead of hours, as before :-)

Everything else of this bug unchanged, as to be expected.

PLUS a new finding for this issue: 

When I set my TRASH IMAP folder to be a k9 "push" enabled folder, things are changing as follows:
- Additionally MUCH faster deletions, really nice!
- BUT: Result are always 2 (!) emails in TRASH, so deleted emails from normal folder are getting duplicated in trash.
- When deleting messages from trash, with push enabled they seems to be gone., manual sync does NOT get them again, as it's working falsely when trash set to no push. 
- BUT: Although they are "gone" from k9 forever, they are NOT deleted in IMAP.

So with push enabled for trash, you're getting your k9 trash emptied much faster. But never get your imap trash cleared.

**Comment by C-Cur** [comment]
I am having the same problem of items deleted from the the Trash on K-9 Mail still remain on the IMAP server Trash Folder. I am using K-9 Mail version 5.600 on Samsung Galaxy S5 Android Version 6.0.1 and all check boxes in Fetch are set to immediately delete emails from server.

**Comment by cketti** [comment]
Please create a new issue (including debug log) if this is still a problem with K-9 Mail 5.7xx.
