### ISSUE TITLE
Can't send email when connected to NordVPN

### ISSUE THREAD

**Issue by yaomtc** [thunderbird/thunderbird-android#3429]
### Expected behavior
When connected to a NordVPN server over TCP using their Android client (which I believe is a frontend to OpenVPN for Android), emails should probably send as normal. 

### Actual behavior
Emails do not leave outbox, but instead I get the "k9 mail errno exception isconnected failed" error. 

### Environment
K-9 Mail version: 5.403

Android version: 8.1.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (SSL/TLS port 493), SMTP (port 465)

**Comment by 8ak5sih222nnb9f6** [comment]
Same issue, using OpenVPN for Android 0.7.7. Android 7.1.2
IMAP (STARTTLS port 587). Works as soon as I disconnect from VPN.

K-9 Mail 5.600 (F-Droid)

**Comment by jpschewe** [comment]
I'm seeing something similar. If I connect using OpenVPN over the cell network, K9 mail works fine. However when I connect using OpenVPN over a wifi network (particularly at hotels), K9 mail times out or gives me the message "AUTHENTICATE PLAIN" on email mailbox rather than refreshing the mailbox. I'm using IMAP with SSL/TLS and SMTP with STARTTLS.

**Comment by jpschewe** [comment]
I grabbed the logs as specified in https://github.com/k9mail/k-9/wiki/LoggingErrors and found that the problem is the number of connections from my VPN to the mail server. So my report is not due to k9.

**Comment by yaomtc** [comment]
I don't have NordVPN anymore so I can't test this, so that's fine by me.
