### ISSUE TITLE
Trash not sync'ing correctly

### ISSUE THREAD

**Issue by lordkage** [thunderbird/thunderbird-android#3605]
The behavior changed after last release.

### Expected behavior
When a message is moved to the Trash, it is moved to the Trash locally and on the server. If a sync is issued on that folder, then the local Trash will reflect the changes of the server, including any recently moved messages.

### Actual behavior
The messages are being moved to the Trash, but when it is synchronized with the server, it is duplicating the messages locally. Then when the delete is issued from the server side and a subsequent sync happens on the Trash folder, the remote duplicates are removed, but the local duplicates remain. The server has no reference to the messages in the Trash, and as far as it knows, it is empty. However, K9 believes there are messages in the Trash folder. Repeated sync's do not remove them. Clearing messages locally will remove the duplicate messages.

### Steps to reproduce
1. Delete message
2. Sync Trash folder
3. Observe duplicate messages
4. Empty Trash via server (aka, another interface)
5. Sync Trash folder
6. Observer locally moves messages still appearing in Trash
7. Clear local messages from Trash folder
8. Messages are gone

### Environment
K-9 Mail version:
5.600

Android version:
8.1.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment]
Can you please record a debug log while deleting a message. See https://github.com/k9mail/k-9/wiki/LoggingErrors

Deleting a message in K-9 Mail first moves the message to the local trash folder. But as soon as the server command to move the message completes, the local message should be updated to point to the remote message in the Trash folder. From your description it sounds like the last step doesn't happen in your setup.

**Comment by CueHD** [comment]
This is happening to me as well. It is happening with two IMAP accounts just as described above. It only began doing this after the most recent update. If a log has not been provided already, I will try and generate one later this week when I am at my main laptop.

Environment
K-9 Mail version:
5.600

Android version:
8.0.0

Account type:
IMAP

**Comment by Heycz** [comment]
Delete msg commond:
UID COPY 1465203373 "Trash"
UID STORE 1465203373 +FLAGS.SILENT (\Deleted)

delete succuess,but when sync:
09-28 16:59:36.758 10282-10377/? V/k9: conn92385403>>> 5 SELECT "Trash"
09-28 16:59:36.767 10282-10377/? V/k9: conn92385403<<<#null# [0, EXISTS]

then the remoteMessageCount =0,so the ui list has no msg

**Comment by dclubb** [comment]
For those affected by this issue, were you able to figure out a workaround?

**Comment by CueHD** [comment]
I have found a work around. While deleting individual messages from the Trash folder in K9, the message is still in the trash folder on the server. However, both of the "Empty Trash" buttons do appear 
to remove the messages from the server.
The two buttons are:
From within an account's folder list, select the options menu and click "Empty Trash"
or
From the K9 account list, long press on an account and click "Empty Trash".

**Comment by tom-candle** [comment]
This is a very annoying bug, which hits me very hard, since I have several mail accounts. I usually delete a single message only.

Here are what I have to do to delete a message:
- Delete message. -> Message is duplicated in the trash, one is synced with the server, the other not.
- Delete both messages from the trash.
- Log in to the webmail, go to the trash-folder and finally delete the "marked as deleted" message.

Please fix this bug.

Possible related and/or duplicate: #4008, #3903, #3801, #3355

**Comment by tom-candle** [comment]
This is a very annoying bug, which hits me very hard, since I have several mail accounts. I usually delete a single message only.

Here are what I have to do to delete a message:
- Delete message. -> Message is duplicated in the trash, one is synced with the server, the other not.
- Delete both messages from the trash -> The synced message on the server is marked as deleted. The other message is really deleted.
- Log in to the webmail, go to the trash-folder and finally delete the "marked as deleted" message.

Please fix this bug.

Possible related and/or duplicate: #4008, #3903, #3801, #3355, #2705

**Comment by CueHD** [comment]
Another potential concern with this issue is what "Empty Trash" does. Preciously, I had been deleting items from the trash to remove them from both my device and the server. Now, I must use "Empty Trash" to do this. However when I empty trash from K9, it empties the enitire trash from the server, not only the messages located in K9.
While I realize that this is likely the desired outcome, it means that we currently have no easy way to remove messages deleted by K9 from the server without emptying the entire trash.

**Comment by daviwph** [comment]
It may be helpful to know that Version 5.600 appeared to be working normally when used with a GoDaddy IMAP server.  The duplicate trash issue developed when I move to a Network Solutions IMAP server.  Deleted mail is added to the Trash folder on the server as expected.  As the K9 trash folder updates, two of each deleted message appear.  When the Trash folder is purged on the server via a desktop client, the duplicate messages remain on the Trash folder on the phone.  I delete them by using "Clear Local Messages".  Other then this issue with the Trash folder, the Network Solutions IMAP server works normally.

**Comment by alexandre1985** [comment]
I also have the same problem that @lordkage posted on the opening post.

I don't know about using a "webinterface" as @wurstsemmel says. When I delete my message I do it on K9 and I always follow with an clearing of trash inside K9.

I believe that (when deleting an email) K9 moving the message to Trash folder **locally** could be removed and instead do an email move to Trash folder only on the server.
Then when viewing the Trash folder on K9, it could do a fetch of Trash folder emails from the server.

Doing so, it would not create duplicate emails inside the Trash folder when deleting email.

Thank you for the OpenSource solution of K9. This is the only issue that I have using it, so for me everything else that K9 delivers is good :wink:

**Comment by cketti** [comment]
This should no longer be an issue in K-9 Mail 5.7xx.

**Comment by lordkage** [comment]
Is that a beta version or a release version?

**Comment by cketti** [comment]
It's a beta version.
