### ISSUE TITLE
Crash / fc upon trying to export settings

### ISSUE THREAD

**Issue by elem089** [thunderbird/thunderbird-android#3614]
### Expected behavior
Having installed and configured K-9 V 5.600 I tried to export my settings

### Actual behavior
the app immediately crashes / closes with a pop-up letting me choose between "close app", "restart app" and "give feedback"

### Steps to reproduce
1. open app to the "accounts" screen
2. hit "3 bullets" then "export/import settings then export settings
3. app crashes right away

### Environment
K-9 Mail version: 5.600

Android version:
7,1,2 root / LineageOS 14.1

Device:
Sony Xperia X1c (amami)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP, 3 accounts

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by John579** [comment]
Hello cketti,
I am having the same problem with K9 Version 5.600 on aRedmi Note 2 with Android 5.0.2 LRX22G and MIUI 7.0. I am not a developer, but I followed your notes to get a debug log and got the following. Maybe this helps:

09-24 22:00:44.574 I/K9      (458): Registered: unmount receiver

09-24 22:00:44.576 I/K9      (458): Registered: shutdown receiver

09-24 22:00:44.587 V/K9      (458): Initializing observer: com.fsck.k9.provider.MessageProvider$1@301f0c58

09-24 22:00:44.730 I/CoreService(458): CoreService: com.fsck.k9.service.MailService.onCreate()

09-24 22:00:44.734 I/CoreService(458): CoreService: com.fsck.k9.service.MailService.onStart(Intent { act=com.fsck.k9.intent.action.MAIL_SERVICE_RESET cmp=com.fsck.k9/.service.MailService (has extras) }, 1)

09-24 22:00:44.742 I/MailService(458): MailService.onStart(Intent { act=com.fsck.k9.intent.action.MAIL_SERVICE_RESET cmp=com.fsck.k9/.service.MailService (has extras) }, 1), hasConnectivity = false, doBackground = true

09-24 22:00:44.746 D/CoreService(458): CoreService (com.fsck.k9.service.MailService) queueing Runnable 551617342 with startId 1

09-24 22:00:44.751 D/CoreService(458): CoreService (com.fsck.k9.service.MailService) running Runnable 551617342 with startId 1

09-24 22:00:44.753 I/MailService(458): No connectivity, canceling check for com.fsck.k9

09-24 22:00:44.763 D/CoreService(458): CoreService (com.fsck.k9.service.MailService) completed Runnable 551617342 with startId 1

09-24 22:00:45.134 I/CoreReceiver(458): CoreReceiver.onReceive Intent { act=com.fsck.k9.service.BroadcastReceiver.cancelIntent flg=0x10 cmp=com.fsck.k9/.service.BootReceiver (has extras) }

09-24 22:00:45.147 I/CoreService(458): CoreService: com.fsck.k9.service.PushService.onCreate()

09-24 22:00:45.151 I/CoreService(458): CoreService: com.fsck.k9.service.PushService.onStart(Intent { act=com.fsck.k9.service.PushService.stopService cmp=com.fsck.k9/.service.PushService (has extras) }, 1)

09-24 22:00:45.157 I/CoreService(458): CoreService: com.fsck.k9.service.MailService.onDestroy()

09-24 22:00:45.230 I/CoreService(458): CoreService: com.fsck.k9.service.PushService.onDestroy()

09-24 22:00:58.965 E/AndroidRuntime(458): Process: com.fsck.k9, PID: 458

09-24 22:00:58.965 E/AndroidRuntime(458): 	at com.fsck.k9.activity.Accounts.onExport(Accounts.java:1933)

09-24 22:00:58.965 E/AndroidRuntime(458): 	at com.fsck.k9.activity.Accounts.onOptionsItemSelected(Accounts.java:1265)

If you need more information, let me know. I am no dev, but I'll do my best :-)

ITMT, I would like to use the setting information to set up K9 on another phone. Until this problem is resolved, is there perhaps another way to accomplish this?

Cheers,
John 579

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
