### ISSUE TITLE
Ipv6 address not possible for server

### ISSUE THREAD

**Issue by paphko** [thunderbird/thunderbird-android#3676]
When setting up a new imap account, it is not possible to enter an ipv6 address like "2002:cc:d456:d300:654:33ff:fe33:65ea" as server address. The next button is simply not enabled. As soon as a colon is contained in the address, I cannot continue. Surrounding the ip with square brackets does also not work. It seems to me as a bug - or did I miss something?

**Comment by ByteHamster** [comment]
You could try to enter the ip with square brackets:

    [abcd:efab:...]

**Comment by paphko** [comment]
I tried that already, but the button is still not enabled...

**Comment by GoneUp** [comment]
It looks like the function for validation domains only supports domains or IPv4 addresses. Code is here https://github.com/k9mail/k-9/blob/3af2e6c022e11e2dc534f14cb1820895858d4376/app/core/src/main/java/com/fsck/k9/helper/Utility.java#L110

**Comment by realdadfish** [comment]
Normally entering a raw IPv4 or IPv6 address shouldn't be needed, but after switching phones I figured that my SMTP configuration no longer works. I suspect a broken IPv6 connection, because if I enter the IPv4 address of my server (and accept the certificate dialog), the SMTP connection test works. But due to the above error, I cannot really verify that it's IPv6-related actually.
