### ISSUE TITLE
Server search does not display message body older than set in "Sync messages from"

### ISSUE THREAD

**Issue by slimlv** [thunderbird/thunderbird-android#3685]
Server search allows to search the messages on imap server. The list of found messages returned. But message's body does not shown when "Sync messages from" is defined and the date of the message is out of range. This is pretty confusing. At least some notification should be displayed.
From IMAP conversation view there is issue as well: the app asks for message's body, then rejects it due "Sync messages from" setting, then repeat fetch/reject 50 times in loop

### Expected behavior
Message body is shown from Server side imap search with no influence of "Sync messages from" setting

### Actual behavior
the message is not shown from imap search due "Sync messages from" setting

### Steps to reproduce
1. set "Sync messages from" setting to "today" only
2. search for any old message
3. search on server
4. select any old message found
5. body is not displayed, no any notification about the "Sync messages from" setting, imap server flooded with FETCH requests

### Environment
K-9 Mail version: 5.6

Android version: 8.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by k9janer** [comment]
I can confirm this with K9-mail 5.600 on OnePlus 3 with Android 8.1.

In fact this feature hasn't worked for me for at least 3 years so it's not a new bug.

Personally I think this bug is quite severe as it forces you to increase the "sync messages from" time frame if you want a way to access older email which wastes storage space and also impacts k9 mails performance.

[k9log.txt](https://github.com/k9mail/k-9/files/2896626/k9log.txt)

**Comment by cketti** [comment]
Fixed by #4385
