### ISSUE TITLE
App crashes on opening inbox with wrong password

### ISSUE THREAD

**Issue by hendrikbl** [thunderbird/thunderbird-android#3691]
The app crashes after importing an account with the wrong password. After importing you are promted to input the password for the account. Though it seems that its not checked at all at that point so the app can't get the accounts folders and thus crashes when I try to open the inbox from the account list (or the unified inbox). 

### Expected behavior
Check password and show a wrong password notice either on account import or when opening the inbox.

### Actual behavior
The app just crashes.

### Steps to reproduce
1. Import Account from .k9s file
2. Input wrong password for the account
3. Try open the inbox of that account from account list/or unified inbox

### Environment
K-9 Mail version: 5.700-SNAPSHOT

Android version: 8.0.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
Developer note: since the app now starts in the message list, there needs to exist at least one folder that could be displayed. 
A proper fix would be to show a placeholder screen when there are no folders yet. For now we fall back to displaying the Outbox folder which is a local folder that should always exist. However, I believe there are still situations where the local Outbox folder isn't created. See issue #4352.

**Comment by Tobias-B-Besemer** [comment]
Note:
If it's a dup of #4376, then there is no import of any setting needed!
I created a new Acc, entered just any PW, because I didn't knew it at this moment and there was no option to switch (A other issue?), but I didn't imported any setting (file), so the second Acc is completely new!
