### ISSUE TITLE
K-9 mail version 5.600: export settings file empty.

### ISSUE THREAD

**Issue by Alfonico** [thunderbird/thunderbird-android#3712]
### Expected behavior
When exporting settings with version 5.600, the k9s resulting file should contain the settings.
This was the case when using K-9 Mail old version 4.804.

### Actual behavior
When exporting the settings the k9s file is created in the directory proposed by K9 (in my case SDCARD/Documents) without any error messages. But the file is empty (0 bit file).

### Steps to reproduce
1.Settings Import & Export
2.Export settings and accounts
3.Save proposed file without changing the proposed folder, i.e. SDCARD/Documentsd/k9_settings_export_2018-11-14.k9s

### Environment
K-9 Mail version:
5.600
Android version:
6.01

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by cketti** [comment]
This is probably because of a setting with an invalid internal value. Try going to all settings screens (global settings and account settings) and backing out via the back button. That should update the settings with valid values. Alternatively, uninstalling and reinstalling should fix the issue.

If the error persists after a reinstall please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
