### ISSUE TITLE
Account led colors not working

### ISSUE THREAD

**Issue by Ratchetrizzo** [thunderbird/thunderbird-android#4299]
In the old version, each account had a notification LED color according to the account color.  This beta version doesn't, everything is blue (this is a samsung note 9 running oreo).  I enabled all settings in notifications.

### Expected behavior
Bring back the multi account color notification LED account colors

### Actual behavior
All 4 of my accounts are blue 

### Steps to reproduce
1. Get email
2. Look at notification LED
3. See it's blue

### Environment
K-9 Mail version: 5.6 beta

Android version:
8.0

Account type (IMAP, POP3, WebDAV/Exchange):
Gmail IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by FAUguy** [comment]
Yes, I can agree that the individual LED Notification color is missing in 5.7 update.
I've been using the 5.7 update for the past day, and there are many features from the K-9 Mail that I use.
This includes the main screen showing all the E-Mail accounts in a list, now you have to use the left tab to select E-Mail accounts (takes more time). The icon shortcuts that were on the bottom of the screen are gone, and now have to stretch to the top of the screen to get the functions. Each account no longer has its own dedicated LED Notification Color, they are all now default Blue.
Because of this, I have to remove 5.7 and go back to using 5.6 despite it keeps saying Sync Disabled for my IMAP accounts (even with 15 min Polling selected).

**Comment by Ratchetrizzo** [comment]
Same here on 5.6 sync disabled and notifications Dont go away unless you manually swype them off the notification list.  Wish I never updated.

**Comment by Ratchetrizzo** [comment]
I put 5.6 back, and disabled folder poll frequency and left first class push on.
Everything works again except the LED colors, sometimes they're correct, but reds and yellows all show up as oranges..  Blues and greens show up correctly.
I'll stick with this until 5.7 has a official release with everything working properly

**Comment by xmiseggs** [comment]
If it helps, in my OnePlus 5T with version 5.709 when a new email arrives it does not activate the notification led (it does not show any color), any other application shows it and with colors that I can choose for each email account.

**Comment by Tagirijus** [comment]
I can confirm that the LED color is only one color now (here it is green). Would be nice if this could be fixed, in case it is even a bug. (=

**Comment by cketti** [comment]
This issue is now tracked under #5544
