### ISSUE TITLE
[5.701] Answer to e-mail without scrolling

### ISSUE THREAD

**Issue by Hustensirup** [thunderbird/thunderbird-android#4342]
I can't scroll inside the answer message tect Input. There is only one scrollbar for the whole message (with the message content I am answering to).

### Expected behavior
Scroll up and down like in the old k9 client.

### Actual behavior
You can't scroll upwards to the first line.

### Steps to reproduce
1. Click an e-mail to read it.
2. Click answer button And click answer.
-> Original Mail content is beneath the message content input.
3. Type tect inside the message content input and hit return/new line multiple times.
-> you can't scroll upwards to the first line.

### Environment
K-9 Mail version: 5.701
Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): POP3 + IMAP

**Comment by Voronoi-K9** [comment]
Same issue, really annoying.

**Comment by Hustensirup** [comment]
As a workaround you can select the text and scroll by selecting/unselecting the text, also save as draft and open again, the the scroll area is at least as high as the mail.

**Comment by PCigales** [comment]
Yes, this issue is very annoying. Closing and reopening the keyboard enlarges a lilttle the area of the mail that is being written, but to scroll up, it is necessary to press and swipe the cursor, so it is not convenient at all.
I hope this bug will be fixed soonly as it is one of the two worst current problems (the other one being that saving as draft is unusable because line breaks are lost when reopened, as far as I am concerned.

**Comment by johnyradio** [comment]
Example:

![Screenshot_20191223-020839](https://user-images.githubusercontent.com/6564280/71374433-87503680-256f-11ea-95e4-2b47bdeacf95.png)
