### ISSUE TITLE
Previews of image attachments are not displayed, regardless of settings

### ISSUE THREAD

**Issue by Viss** [thunderbird/thunderbird-android#4935]
No matter what settings are set, I cannot get graphical attachments to appear in-line. 
I have several security cameras that email photos from when movement is captured, and instead of showing me the actual images, k9 shows me these grey boxes with icons. 

How can I force k9 to actually show me the images? I'm using the most recent version available in the /releases section here on github.

**Screenshots**
![Screenshot_20200907-123053](https://user-images.githubusercontent.com/1756255/92413764-75ff8800-f106-11ea-8f1e-c4334c615831.jpg)

![Screenshot_20200907-123157](https://user-images.githubusercontent.com/1756255/92413772-7dbf2c80-f106-11ea-8342-fb537b1020d4.jpg)

**Environment**
 - K-9 Mail version: 5.718
 - Android version: 10
 - Device: Oneplus 7 pro
 - Account type: IMAP

**Comment by cketti** [comment]
That's probably because the camera doesn't use the proper MIME type (i.e. `image/jpeg`) for the attachments. 

We'll add some code to make image previews work if the MIME type is `application/octet-stream` (which basically says "I don't know what kind of content this is") and the file extension is a known value for a supported image format. Hopefully that will make things work for you.

Still, you should report this as a bug to the vendor of your security camera.

**Comment by Viss** [comment]
These images are from an axis camera, and I'll report this to them as well.
