### ISSUE TITLE
Permanent crash after settings import

### ISSUE THREAD

**Issue by rixx** [thunderbird/thunderbird-android#5000]
**To Reproduce**

1. On my old phone, I exported my settings for the global settings and one of the two accounts (regular imap/smtp, no shenanigans).
2. On the new phone (Android 11, throws a "your app is only for older Android versions"), I import the settings at the initial screen
3. k-9 closes (or re-opens the file app, it's not entirely clear to me)
4. Trying to open k-9 again leads to an immediate crash, repeatedly
5. Only deleting all app data helps

Adding my account manually leads to a smoothly working k-9, but every attempt at using the settings import produces the behaviour above.

I couldn't retrieve screenshots for obvious reasons, but [here](https://drop.rixx.de/QQiu/) is an anonymised version of the export. (Also note that both accounts are included, even though I'm fairly certain that I selected only one.)

**Comment by cketti** [comment]
From the description I deduce you're using K-9 Mail 5.600.

The app crashes because it can't create the message database on external storage (this feature doesn't work anyway, see https://forum.k9mail.app/t/external-storage/313/3). Make the following change to fix the issue:
```diff
-        <value key="localStorageProvider">ExternalStorage</value>
+        <value key="localStorageProvider">InternalStorage</value>
```

You may also want to switch to the beta version which contains a lot of fixes and won't show the warning dialog when run on Android 11. See [How do I become a beta tester?](https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68)

**Comment by rixx** [comment]
Manually configuring worked fine for me, I just wanted to report this in case it's unknown and/or you wanted to work around it. Thank you for the fast reply!
