### ISSUE TITLE
Port isn't changed when switching account types

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#5088]
**Describe the bug**
With PR #5085 merged it's possible to start account setup, but then before finishing the setup go back and change the account type. This will keep the original port number.

**To Reproduce**
1. Go to settings and click "Add account" or use the onboarding flow to add an account
2. Enter email address and password for a domain that needs to be manually configured
3. Select "IMAP"
4. Enter correct server settings and press "Next"
5. Use back button twice to go back to the account type selection screen
6. Select "POP3"
7. Notice that the 'Port' input field still contains the port configured in step 4

**Expected behavior**
Use the default port number for the selected account type.

**Environment (please complete the following information):**
 - K-9 Mail version: 1259d372b6ae7f2f9cfdc5cdbfd373f0a0691d8b

**Comment by Monkey-Matt** [comment]
I've done some testing of this and found it applies to other fields as well, e.g. username/password. Effects both incoming and outgoing. 
It's due to the way account settings are saved at each step and then restored upon returning to each screen.

I could reset the port every time you go from AccountSetupAccountType -> AccountSetupIncoming but I don't think that's a complete solution.

In my opinion if you make some changes on the incoming/outgoing setup and then go back to account type selection, then go into the incoming screen again it should not have any of your changes and instead have the defaults for all fields like the first time you navigated to the incoming screen. I'm currently working on how to achieve this.
