### ISSUE TITLE
Mark as read icon out of sync 

### ISSUE THREAD

**Issue by Slion** [thunderbird/thunderbird-android#5142]
**Describe the bug**
Mark as read button icon always showing closed envelope after selecting a message.

**To Reproduce**
1. Go to message list
2. Click on either read or unread message
3. Message is shown and tool bar shows closed envelope even though message is now read.
4. Tap mark as read button, icon is toggled to open enveloped even though message is now unread.
5. Go back to message list see how your message is indeed still unread, which is correct.

**Expected behavior**
Mark as read button icon should be in sync with message status.

**Screenshots**

**Environment (please complete the following information):**
 - K-9 Mail version: 5.729
 - Android version: 9
 - Device: F(x)Tec Pro1
 - Account type: IMAP

**Comment by cketti** [comment]
The button doesn't show the current state of the message. It's an action button. So if it shows the closed envelope, the action that is performed when the button is clicked is "mark as unread".
With the default settings K-9 Mail marks a message as read when opening it for viewing. So you should always see the closed envelope icon in the toolbar at first.

**Comment by Slion** [comment]
I don't get it:
Opened envelope == Read
Closed envelope == Unread

Why would it then show the closed envelop when I open a message? It should be the opened envelope.
ATM it shows opened enveloped when unread and closed enveloped when read which counterintuitive.

**Comment by cschreib** [comment]
I came here looking if anyone had reported that this choice of icon is counter-intuitive; and found this issue. I also happen to think it is counter-intuitive: even if this is an action button, one would expect it to display the current state. 

Think of a tick box: when ticked, it is shown as "ticked", and you can tap it to untick it. It is not shown as "unticked" because the action would untick it.
