### ISSUE TITLE
Behaviour after selecting multiple emails

### ISSUE THREAD

**Issue by richardshakeshaft** [thunderbird/thunderbird-android#5220]
In an inbox (including unified) if you select multiple emails and Mark as read our delete them, the inbox remains in select multiple mode, so when you tap another email to open, it's added to the non existent selection rather than behaving as expected.

V5.733

**Comment by cketti** [comment]
For "mark as read" this is intentional. Maybe the user wants to move the messages to another folder afterwards. It'd be annoying having to select all previously selected messages again. Whereas it's just one tap to exit selection mode if marking those messages as read is all the user wanted to do.

After using the "delete" action selection mode should be exited. This is working as expected on all of my test devices. Can you provide more information on how to reproduce the issue? And/or record a video of the behavior you're seeing?
