### ISSUE TITLE
gmail account setup issues

### ISSUE THREAD

**Issue by poldi171254** [thunderbird/thunderbird-android#5295]
I'm running V 5.733 and while investigating [https://github.com/k9mail/k-9/issues/4202](url) I found that I cannot connect to (brand new account setup) the gmail server unless I allow **Access for less secure apps** on my gmail account in Google.

I had the same issue with thunderbird, but could (eventually) connect by choosing OAuth2 as the Authentication method.

I found two issue when setting up the account:

1) If I try the automatic setup I get and Authentication failure
![Setup Failure](https://user-images.githubusercontent.com/43848359/117738960-9311cb00-b240-11eb-98ba-c4da71feecf5.png)

2) If I choose the manual config, I get past the above issue, but now have the problem that OAuth2 is not available as an authentication method 
![noOAuth2](https://user-images.githubusercontent.com/43848359/117739225-34008600-b241-11eb-937c-d3c714daa012.png)

**Comment by cketti** [comment]
The issue tracker is used to organize work. Please don't create a single issue for multiple bugs. Please use the issue template, so important information ends up in a predictable place. We also ask for the expected behavior for a reason. Sometimes issue reporters misunderstand what the intended behavior should be.

It's not clear to me what you believe are bugs in K-9 Mail in this case. Can you please elaborate?

**Comment by poldi171254** [comment]
I logged the tow issues together as the behaviour of the first (clearly) affecst the second and I couldn't think of an easy way to show that (potential) link

The bug for the first issue is that it indicates an authorization failure (username or password) which it is not. The issue seems to be that Gmail only allows authorization via OAuth2, so the message should reflect this; even better would be to carry on to the next screen, where the Authentication is specified, but I think that fails (Bug) as 'List<ImapResponse> responses = authenticate();' doesn't recognise the OAUTH2 
[autent-fail.txt](https://github.com/k9mail/k-9/files/6462953/autent-fail.txt)

**Comment by poldi171254** [comment]
Had a closer look at this and have a few questions.
Did connection to gmail via OAuth2 ever work. I can't seem to find the place where the token provider is specified

**Comment by cketti** [comment]
> The bug for the first issue is that it indicates an authorization failure (username or password) which it is not. The issue seems to be that Gmail only allows authorization via OAuth2, so the message should reflect this;

Well, all we know is that authentication has failed. The message "username or password incorrect" certainly should be changed, because it's only one possible explanation. We do include the error message returned by the server, but in the most user-unfriendly way possible. In this case the server response text is "Invalid credentials (Failure)". From the response you can't infer it's because the server only allows OAuth2 (in fact, Gmail supports AUTH PLAIN just fine, if you allow "less secure apps" and create an app-specific password).

> even better would be to carry on to the next screen, where the Authentication is specified, but I think that fails (Bug) as 'List responses = authenticate();' doesn't recognise the OAUTH2

K-9 Mail doesn't support OAuth2. See #655.

**Comment by poldi171254** [comment]
Looks like a pull request for this already exists, so suggest to close this and use issue #4832 in future

**Comment by Sunspark-007** [comment]
To be able to log into gmail you need to generate an app password in google account security settings and use it with K-9. You cannot use your regular password.
