### ISSUE TITLE
Latest version 5.800 locks up Motorola phone on install

### ISSUE THREAD

**Issue by cniggeler** [thunderbird/thunderbird-android#5439]
Initiated install of the latest version via Play Store updates on Motorola one 5g ace running Android 9. Device locked up! Had to hold down volume+power key to get it back.

Also have K-9 installed on an old Samsung Note 3 running Android 5, but before installing 5.8 in the same fashion, shut down the running K-9 first. No issues.

Suggestions: Close existing K-9 first before installing, or inform user they must do so before proceeding.

**Comment by Happy86** [comment]
Hi,

same here with a Nokia 7 Plus (Android 10). After the download finishes the device will just freeze (after a few minutes the device will reboot, kernel panic?). 


> Suggestions: Close existing K-9 first before installing, or inform user they must do so before proceeding.

Opening the K-9 Mail App-Details and forcing the app to quit is necessary for the update to succeed. 

Thank you very much for the suggestion. :-) 


Unfortunately I do not how to extract crash dumps on Android. 


Best regards, 
Andreas

**Comment by SkryptX** [comment]
Hi, same here with a Oneplus 6T on Android 10. Even with Force Quitting K-9 does not seem to work. Can't install at the moment.

**Comment by cketti** [comment]
Android itself is responsible for installing the updated app. And of course it stops the old app before installing the new version. That's not something the user has to do (or can prevent).

The device locking up or crashing is always a bug in the operating system. The most an app should be able to do is crash its own process.

Closing this issue because there's really nothing we can do about this.

**Comment by SkryptX** [comment]
I have never seen any app crash on update in all the years I used Android. Maybe the APK is somehow corrupted or something. Please look into it again or try to give us hints to how we can supply logs which would help debug the problem.

**Comment by cketti** [comment]
An app is not involved in installing itself. No app code is running during that process. If there are any log messages, they are specific to your Android version.

**Comment by SkryptX** [comment]
Interestingly it just worked now, when I tried again... It makes no sense, but it probably was some Android magic happening. Still very weird. Maybe because the last update was so long ago, it was a bit rusty 😋

**Comment by kevlar700** [comment]
Fails to install and logs back in with phone starting message on Nokia 6.1. requires a reboot to get the fingerprint reader working again. I have also never seen an app do this but also understand that it should not be possible for an app to crash the OS.

In any case, I can't update to the latest k9-mail.

**Comment by cketti** [comment]
Uninstalling, then reinstalling the app usually works.

**Comment by seniorm0ment** [comment]
I am having the same issue on Android 10 LGv40, this seems to be a common issue by many users of various devices based on this repos closed issues,
in which I have with NO issues witg other apps except K9. I would suggest looking into it more instead of dismissing it as an OS issue or just saying to reinstall because that can be a bit inconvenient. It shouldn't be freezing on updates.

**Comment by cniggeler** [comment]
OP again. I have to agree with @seniorm0ment. This is software, after all, and I find it difficult to claim it's **never** the software and **always** the OS. I mean, at the very least, the OS finishes the install and starts the app, and couldn't that be the point the system gets locked up?
