### ISSUE TITLE
Multiple notifications while reading emails on another device

### ISSUE THREAD

**Issue by mthu** [thunderbird/thunderbird-android#5445]
**Describe the bug**
When reading emails on another device (IMAP IDLE enabled on mobile), the new notification sounds on every new email marked as read (total new mail count is decreased as I am reading emails).

**To Reproduce**
1. Enable IMAP IDLE on mobile
2. Wait for some new emails (more than one), notification properly appears on mobile (with sound)
3. Read some of the new emails on another device (e.g. desktop)
4. As soon as some of the mail is marked read on server (number of new emails is changed), new notifications pops making sound.

**Expected behavior**
I think the proper solution is not to make a sound again, update the existing notification instead (which should result to no-sound update). Unless another fresh email arrives - this would raise a new notification with sound.

**Environment:**
 - K-9 Mail version: 5.800
 - Android version: 9
 - Device: Sony Xperia XZ1 Compact
 - Account type: IMAP with IDLE (Dovecot IMAP server)

**Comment by NickJH** [comment]
As far as I can determine, the notification happens when I delete something on a PC. The PC is using IMAP and and when deleting, it marks the e-mail read (if it is not already) then moves it to the Deleted/Trash folder. If I do an immediate delete (shift and delete in Thunderbird, my desktop client) I do not appear to get a notification (which is great!).
