### ISSUE TITLE
Marking a message as "unread" no longer available

### ISSUE THREAD

**Issue by insilmaril** [thunderbird/thunderbird-android#5460]
**Describe the bug**
Beginning with version 5.800 it is no longer possible to mark a message as unread. This still should be possible very easily, both in the message view and also in message lists.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.800
 - Android version:  11
 - Device: Samsung S10 
 - Account type: IMAP

/* sorry if I overlooked an existing issue */

**Comment by mjnewton** [comment]
When viewing the message, or long-pressing a message in the mail list, the 'Mark as unread' is the envelope icon that appears in the action bar. Similar, marking it as read again is the open envelope icon that appears. I know; it's not very intuitive (otherwise I wouldn't be explaining it!) and I only found it by accident!

**Comment by insilmaril** [comment]
Ah, thanks! That's really not self explaining, I would have expected the envelope to trigger a "compose mail" action.

**Comment by mjnewton** [comment]
> Ah, thanks! That's really not self explaining, I would have expected the envelope to trigger a "compose mail" action.

Now you mention it, I think that's exactly why I was clicking it before then realising what it actually did.

**Comment by cketti** [comment]
Closing this issue since the functionality is not missing. I created #5480 with a proposal on how to avoid the confusion.
