### ISSUE TITLE
Number and list of starred messages no longer accessible

### ISSUE THREAD

**Issue by mueller-physics** [thunderbird/thunderbird-android#5467]
The number of starred messages in an account (or folder) is no longer displayed next to the number of unread messages.

Accessing a list of all starred messages in an account seems no longer possible, viewing all starred messages in a single folder seems possible only by using the 'star' sorting parameter, which is rather cumbersome.

This breaks workflows that use the star to keep track of important messages stored in different (e.g. project-specific) folders.

**Comment by andrewfg** [comment]
Design proposal below..

![k9-quick-filter](https://user-images.githubusercontent.com/893994/127669166-f175f976-7939-42e2-84a2-8b93b5c9c4a1.png)

**Comment by ProfessorDey** [comment]
I can concur that I used this feature heavily and the account list page in general for quickly checking important messages or rapidly finding billing invoices I was paying. The proposed layout would at least aid in restoring that usability, though horizontal alignment would be better for likelihood of hitting the right button.

Though as an additional note, the placement of the star in the message list view overlaps with the scrollbar, at least on my device which has curved edges, making it very difficult to mark an item as important without scrolling by accident.

**Comment by Kyoshiro-san** [comment]
This issue is a bit more than the one you linked, as this one includes the **display** of unread / starred emails.

I must say I used this quite extensively as I have sieve filtering to sort my mail and when on mobile I tend to check only "unread mail from all folder" previous feature.

Is the feature planned for a comeback soon ?
Is it possible to revert to previous version without removing config and data ?

Thank you so much for your work though, the new design looks quite nice :-)

**Comment by cketti** [comment]
Displaying the number of starred messages is supported in 5.900+. Only displaying starred messages will be supported once #4330 is implemented.
