### ISSUE TITLE
K-9 Mail draining battery after latest update

### ISSUE THREAD

**Issue by funkpunkt** [thunderbird/thunderbird-android#5487]
There's been a significant increase in battery usage after the latest update. K-9 Mail is now #1 in the battery usage list on my device

**Comment by cketti** [comment]
I'm curious. How did you manage to create an issue without using the issue templates? https://github.com/k9mail/k-9/issues/new/choose

Also, you didn't provide any information that would be helpful to track down what could be causing this. 
1. What version of K-9 Mail are you using? 
2. What device are you using?
3. What Android version? Is it a custom ROM?
4. How many accounts have you set up? What's the configuration (periodic sync, push, manual refresh only)?
5. What does "significant increase" mean. Can you quantify that? How do you use your device? (If nothing else is running it wouldn't be surprising that K-9 Mail is the top battery user)
6. Can you provide a debug log? See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by funkpunkt** [comment]
Hi and thanks for picking this up so quickly.

> I'm curious. How did you manage to create an issue without using the issue templates?
I just clicked the button "new issue" on my mobile browser and got an empty text box with no instructions.

Info:
1. Version 5.800
2. Google Pixel 4
3. Android 11 (as provided by google)
4. 3 accounts, periodic (15 min)
5. On a usual day the device battery lasts from about 7am (100%) to 8pm (10%). After the update the battery reaches power saving level (15%) between 2pm and 3pm. Before the update K-9 Mail was so far down the list that I didn't ever notice it. After the update it's no. 1 in the list. 
6. not at the moment

Hope this helps to narrow down the issue.

**Comment by cketti** [comment]
Checking three accounts every 15 minutes shouldn't be that much of a battery drain. 

1. Do you by any chance also have Push enabled? `Settings > [Account] > Fetching mail > Push folders` set to anything other than `None` for any account?
2. What is `Settings > [Account] > Fetching mail > Poll folders` set to? You might accidentally checking all folders instead of just the Inbox.

**Comment by funkpunkt** [comment]
There's one thing I'd like to point out before we go into details:
I did not change any settings at least over the past 10 months. The problem occurred at the same time when the update which also changed the design was installed. Everything worked fine before the update.

About your questions:
1. I must have overlooked that before when I checked the sync period. Push folders is set to "main folders".
2. set to "main folders", too

**Comment by cketti** [comment]
Unfortunately, knowing that everything worked fine in 5.600, but doesn't in 5.800 doesn't help in narrowing down what part of the app is causing the problem. Too many things have changed. 

My guess is that the push code is causing the problems. Please try disabling push and see how this affects your battery drain. 
See [How to configure Push?](https://forum.k9mail.app/t/how-to-configure-push/1102) to learn how to disable Push.

**Comment by funkpunkt** [comment]
I disabled push for all 3 accounts a few hours ago, leaving pull interval at 15 minutes. Battery looks normal up to now.

**Comment by Kcchouette** [comment]
Hello
I have same problem with version 5.800 (5.600 was fine). Battery usage since full charge from this version of K9-mail is **92%** on my mobile.

I have android 10 stock version, I had set up 2 accounts

Regarding discussion from above, I have disable push (like [this](https://forum.k9mail.app/uploads/default/original/1X/320ada729af7fc92a28b1964a3b0743c7772f13f.png)), I'm charging my phone and I'll give you feedback

**Comment by cketti** [comment]
@funkpunkt: Glad that fixed it for you. It sounds like you don't need Push, so I'd understand if you consider this matter closed.
However, I'd be interested to learn why Push is misbehaving. It would be very helpful if you could re-enable Push and grab a debug log after Push has been active for 30 minutes.

**Comment by funkpunkt** [comment]
Hi again.

I can confirm that this is related to the push feature. I re-enabled push about 2 hours ago and the battery usage graph has become about twice as steep since then. K-9 Mail has come back to the top of the list, too.

> so I'd understand if you consider this matter closed

Well, in fact I'd rather like to have push working again. Now that incoming mails appear with a delay of up to 15 minutes, i realized how convenient push was ;-)

> It would be very helpful if you could re-enable Push and grab a debug log

I'll try to provide a debug log later today.

**Comment by funkpunkt** [comment]
I've got a log file now.

First of all, the logcat command produces a few thousand lines of log each time it is run but the time span covered varies from 20 seconds to a few minutes. Is that what you need or did something go wrong?
Additionally I found out that disabling push for the account that's responsible for most of the log lines and leaving it on for the other two reduces power consumption a lot. I can't tell if it's back to normal or if it still increased but at least it's much less annoying.

Second, how do you want me to send the log file? I don't want to post it to the public. It contains personal items.

**Comment by cketti** [comment]
You can send the log to cketti@gmail.com

**Comment by Jowat97** [comment]
![img](https://user-images.githubusercontent.com/45443409/127796010-2642416a-ceec-4b0b-95d9-b07aac337311.jpg)

I can confirm this. The battery drain increased significantly since I updated from 5.400 to 5.800 (F-Droid).
I am using one account and set the update-rate to 30 min. I rarely open the app myself. I just need it so get notified if I receive an e-mail. So all the battery drain just came from background activities. I have changed nothing in the settings, as I updated the app but nevertheless the battery dran increased. Seems like it has something to do with your new method of background sync.
I am running Android 10 Stock ROM.

Btw, my system always give me a notification, that K-9 is using to much battery and I should stop it from background activities.
Unfortunately I had to uninstall K-9 and switch to an alternative, until this get solved. If you need and information etc. let me know.

**Comment by Kcchouette** [comment]
with PUSH, my battery was empty in 1 day and 9 hour, 92% of K-9 mail.
Without PUSH, my battery is not empty after 1 day and 21 hour, K-9 mail usage is 1%

**Comment by cketti** [comment]
In order to fix the bug we need someone to record a debug log while Push is enabled. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by funkpunkt** [comment]
> 
> 
> You can send the log to [cketti@gmail.com](mailto:cketti@gmail.com)

Sorry for the delay. I was quite busy yesterday. You've got mail containing 3 log files now.

**Comment by cketti** [comment]
I've received the log. Thanks :+1:

The problem is that the server doesn't support the IDLE extension, so Push doesn't work for that account. Unfortunately, the code is not doing the right thing in that case and K-9 Mail ends up sending a command to the server over and over again.

**Comment by EkriirkE** [comment]
I am still experiencing huge consistent battery drain for the last month, I've put K9 into restricted mode and that seems to have curbed it but I no longer get reliable email alerts doing so.

It is also consuming huge mounts of my mobile data all of a sudden.  It tops my phone's stats for both data and power for the last month

**Comment by codethief** [comment]
I enabled push notifications about a year ago, and switched to a Pixel 8 in December. Since then (which of course coincided with updating to the latest K-9 version) I have seen constant heavy battery drain. K-9 is almost always the # 1 app in the "battery usage" list. My IMAP server is Dovecot, so IDLE should work.

**Comment by codethief** [comment]
Update: I disabled push yesterday and enabled polling (with a frequency of 15min). Unfortunately, my battery is still being drained. According to the battery stats, today I used K9 for 5min but it accounted for 43% of battery.
