### ISSUE TITLE
push notification doesnt work all the time

### ISSUE THREAD

**Issue by cyrusmajor** [thunderbird/thunderbird-android#5553]
I have Samsung s21 ultra and android version is 11.
I just updated k9 mail to version 5.8.02 and I am having problems with push notifications. Sometimes emails are not received unless I open the app and pull down manually to fetch new email. Note: I do see the @ icon for push notifications in the notification bar so that tells me k9 email is looking for new emails. 
This doesn't happen all the time. Sometimes it does fetch the emails properly and notifies. Seems like its a bug. Please let me know when it will be fixed

**Comment by cketti** [comment]
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by Swyter** [comment]
In my case to fix it I had to make it look up for all folder categories, seems like the problem was that the folder categories weren't correctly configured, so by default it only waits for first-class messages, and not even the inbox is set to that.

**Comment by cketti** [comment]
> In my case to fix it I had to make it look up for _all_ folder categories

Selecting all folders for Push is not a great option. See https://forum.k9mail.app/t/how-to-configure-push/1102 for more details.

**Comment by Swyter** [comment]
@cketti Thanks for the heads up. Funnily enough I saw the push folder classification strings while reviewing and refurbishing most of the Spanish translation this morning. I think the inbox should be made first-class automatically when IDLE is enabled no matter what, or at least make the user more aware of it in the small push screen. Because it didn't work until I arrived at this, I understand the functionality is pretty powerful, but there has to be a more direct way of pointing the user.

For example, if there are no push folders configured throw an error pointing to the right place.

**Comment by Swyter** [comment]
Seems like all these folders were set as first class from the start, but push notifications only work when I set the look-up to all.

**Comment by 2Abendsegler** [comment]
> I just updated k9 mail to version 5.8.02 and I am having problems with push notifications.

I had the same problem with version 5.806. I have just deinstalled and reinstalled version 5.806 and have set only the following (and the account of course):
1. Activate the push functionality:
`Account settings / Fetching mail / Push folders = Only 1st Class folders`
2. Change background synchronisation: 
`General settings / Network / Background sync = Always`

After that, the automatic notification of a new mail worked as expected.
