### ISSUE TITLE
smtp mail.routing.net unable to open connection

### ISSUE THREAD

**Issue by Saturo78** [thunderbird/thunderbird-android#5680]
**Describe the bug**
Error Message:
Unable to open connection to SMTP server

**To Reproduce**
try to set the smtp server für mail.routing.net

**Expected behavior**
Should work, with FairMail everything works fine

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806
 - Android version: [e.g. 8]
 - Device: [SG7]
 - Account type: [IMAP]

**Comment by cketti** [comment]
Seems to work fine for me. Please provide detailed steps on how to reproduce the error. Ideally also a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors).

**Comment by Saturo78** [comment]
I have set the exact same smtp values in K-9 and FairMail (copied it)
FairMail works fine. With K-9 i always get the error message 

SocketTimeoutExeption: failed to connect to mail.routing.net

I won´t install software on my pc to extract the logfiles, sorry.

Why there isn´t a option to send the logfiles via K-9.

I am really frustrated after years of using K-9.

Maybe the best solution would be using FairMail in the future?

**Comment by cketti** [comment]
FairEmail is a different app. There is not necessarily a one-to-one mapping between what you enter there and what needs to be entered in K-9 Mail.

Since you're getting a `SocketTimeoutExeption` this is most likely not a bug in K-9 Mail, but a configuration or network problem. Make sure you're using the proper server settings (including port numbers and security options) for your provider. If you're still running into problems try asking for help in the [support forum](https://forum.k9mail.app/). Maybe someone using the same provider can help you out.

**Comment by Saturo78** [comment]
Thank you very much! This really helps me a lot. When everything works fine with Thunderbird, FairMail and Samsung Mail it could't be a fault of K-9 Mail, of course.

So you get another 1 Star Rating in Playstore and FairMail get + 1 Pro Members

¡Muchas Gracias!
