### ISSUE TITLE
Deleted mail in notification bar doesn't disappear

### ISSUE THREAD

**Issue by fabastrid** [thunderbird/thunderbird-android#5691]
On the latest beta 5.902, when I receive a mail, I open the notification window on my Samsung with Android 11, delete the mail, but the mail doesn't go away, I need to slide it away. If I open K-9 I see that the mail was correctly deleted.

**Comment by PhoenixIV** [comment]
This may be the same issue or cause: If I delete an email from my inbox without opening it the push notification remains.

**Comment by cketti** [comment]
Please check if this is still an issue when using the latest beta version: https://github.com/k9mail/k-9/releases/tag/5.910

**Comment by PhoenixIV** [comment]
No. Not an issue anymore. Notifications disappear when I open the folder - even before I can select the message.

Thanks for inviting me to the beta program. Glad to remain in it.

**Comment by michaelblyons** [comment]
I think this may be back. I received multiple notifications, went to my inbox, and deleted several mails without opening them. The notification for one of the mails remained in the status bar.

**Comment by PhoenixIV** [comment]
@michaelblyons which version are you using?


> Please check if this is still an issue when using the latest beta version: https://github.com/k9mail/k-9/releases/tag/5.910

**Comment by michaelblyons** [comment]
I'm on 5.910, yes. I'm not 100% sure of my actions, but I think it went like this:

- Notice the ✉️ icon in status bar
- Expand the notification to see multiple emails.
    - There are actually more unread emails than show up in the notification (if that's helpful).
    - If there's a state where clicking on the notification takes you to an inbox (not to an individual email), that's the state it was in.
- Click the notification. I believe it brought me to the inbox, because I was surprised to see 6-8 unread emails. The notification had shown maybe 4-5?
- I selected some from the inbox and deleted them.
- I think at this point, I clicked into an email, read it, deleted it, which took me to the next email.
- I read this email, clicked "back" to the inbox, where one remaining email was unread.
- Notice notification bar still has ✉️, but it lists two emails:
    - The unread one
    - One of the ones from the initial mass-delete

I do not know if the still-lingering email was one of the ones shown in the very first notification, or if it was one of the "overflow" emails.

**Comment by cketti** [comment]
@michaelblyons: This sounds like a related, but different issue.

When you tap a summary notification (multiple notifications grouped together) and a message list view is opened, all notifications for that account should be removed right away. If that doesn't work, it's a bug. When this happens again, please create a new issue with detailed information on what was showing exactly, what actions you performed in which order, etc.

I believe the original issue has been fixed. So I'm closing this issue.

**Comment by PhoenixIV** [comment]
Now I also got very, very weird behavior. See https://github.com/k9mail/k-9/issues/5897

**Comment by Cris--** [comment]
I have the same problem. After deleting emails  in Thunderbird corresponding notifications didn't disappear.

Android 16 AOSP
Thunderbird 17.0
