### ISSUE TITLE
No longer syncing IMAP changes with error "om.fsck.k9/com.fsck.k9.activity.MessageList EXITING"

### ISSUE THREAD

**Issue by binarydad** [thunderbird/thunderbird-android#5701]
Randomly, it seems, changes from my desktop mail client don't immediately sync to K9, such as flags, deletions, read, etc, until I swipe from the to to refresh. Other instances are just fine. 

I noticed this error when debugging:
```
win=Window{11a1a35 u0 com.fsck.k9/com.fsck.k9.activity.MessageList EXITING} destroySurfaces: appStopped=true
win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=4
caller=com.android.server.wm.AppWindowToken.destroySurfaces:871
com.android.server.wm.AppWindowToken.destroySurfaces:852 com.android.server.wm.WindowState.onExitAnimationDone:5419
com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262
com.android.server.wm.AppWindowToken.onAnimationFinished:2413
com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2
```

I have to force quit the app for it to work again. Thanks.

**Comment by cketti** [comment]
The log entry is not from K-9 Mail. I can't tell if the app crashed, the app was stopped because of a low memory condition, or the `MessageList` activity was simply exited by the user (but the process is still running).

If you want to give us a realistic chance of tracking down the problem, please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

Also, please provide relevant information asked for in the issue template. What K-9 Mail version are you using? What Android version are you using? How is your account configured (I assume it's an IMAP account configured to use Push, but we shouldn't have to guess). If you are using Push, what message does the ongoing notification display?

**Comment by cketti** [comment]
Closing because no additional information was provided.
