### ISSUE TITLE
searching for sender name don't show results for github notifications emails

### ISSUE THREAD

**Issue by rms-joe** [thunderbird/thunderbird-android#5776]
**Describe the bug**
searching for sender name don't show results for github notifications emails
( from: name < notification @ github.com > )

**To Reproduce**
1. search for a sender name of a notification mail from github

**Expected behavior**
find and show the according emails

**Screenshots**
visualization of the problem :)
---BEGIN---

----END----

**Environment (please complete the following information):**
 - K-9 Mail version: 5.806

**Additional context**
cketti: seems to be caused by the way we store sender information combined with some unexpected behavior of sqlite

**Comment by cketti** [comment]
We use ASCII 0 (NUL) in the `sender_list` column of the `messages` database table (see `Address.pack()`). This is a bad idea and leads to everything after the first NUL character not being found in a search.

See https://sqlite.org/nulinstr.html

**Comment by parkerfath** [comment]
> **Additional context** cketti: seems to be caused by the way we store sender information combined with some unexpected behavior of sqlite

Interesting - I was running into this bug as well, e.g. getting emails from my Realtor, where his is normally displayed, but the true "from" address is a generic address that auto-sends me matches to my listing criteria.

I would be willing to look into how this could be fixed, but I first should ask the obvious question: why hasn't it already been done? Is splitting these two fields into separate columns likely to be a massive refactor? Or is there some other major blocker in the way?

Or, rather than splitting, an "easier" way might be to just leave the sender_list column as-is and create a new column with just the display name, no nul characters, and that could be added to the criteria in MessageList.kt. Thoughts?

**Comment by cketti** [comment]
The `sender_list` column can contain a list of addresses. So switching to a column for the (single) sender's display name and one for their email address is not going to work.

The proper way to fix this is probably to have a separate table for email addresses associated with a message (there's also the columns `to_list`, `cc_list`, `bcc_list`, and `reply_to_list`). However, that is most likely not an easy change and will require quite a bit of work and testing.

The quick fix might be to switch from using ASCII 0 as a separator to e.g. ASCII 1.

**Comment by parkerfath** [comment]
Interestingly, yeah, switching it to ASCII 1 does seem to solve this. :) 

I'm putting the changes together, trying to think about how the data could be migrated from the old way, or handled in a backward-compatible way. It's my first time poking around the codebase, so it might take me a bit. :)

**Comment by cketti** [comment]
Database migrations can be found here: https://github.com/k9mail/k-9/tree/main/app/storage/src/main/java/com/fsck/k9/storage/migrations

**Comment by parkerfath** [comment]
Thanks! I think I have an idea how to do it. Hopefully can post a PR sometime tomorrow night.

**Comment by parkerfath** [comment]
PR posted; see above. Let me know if there are any other things I need to take care of; this would be my first contribution so I hope I've followed the testing/style/etc. guidelines.
