### ISSUE TITLE
Can't connect to POP3 server (IONOS, GMX, maybe others)

### ISSUE THREAD

**Issue by ungutknut** [thunderbird/thunderbird-android#5879]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.806

### Where did you get the app from?

Google Play

### Android version

8.0

### Device model

Shift 5me

### Steps to reproduce

Open K-9 mail inbox; start refreshing the view manually.

### Expected behavior

K-9 is supposed to load new mails. Or at least give some error message saying that something's wrong.

### Actual behavior

Nothing. K-9 shows the reload-icon for a second and nothing else happens. Checking the inbox settings reveals an actual error message which I try to translate from German: "Unable to finish setup. Connection to server not possible. (Unable to exectute pop3 command)"

But my server settings are fine. I didn't change anything and other mail clients work ok using the same settings. I also checked if sending a message works: It does.

Restarting the app doesn't help; restarting the phone doesn't help. Currently K-9 is useless for me.

**Comment by cketti** [comment]
Related:
- https://forum.k9mail.app/t/no-pop3-email-from-ionos-unable-to-execute-pop3-command/4017
- https://forum.k9mail.app/t/fetching-mails-from-gmx-stopped-working-certificate-error-configuration-fails-starttls-not-available/4021

When establishing a connection K-9 Mail sends an `AUTH` command without arguments, trying to figure out which authentication mechanisms are supported. 

https://github.com/k9mail/k-9/blob/de15580e400b8101a10d824fbc6e8a111373880d/mail/protocols/pop3/src/main/java/com/fsck/k9/mail/store/pop3/Pop3Connection.java#L178-L211

The server software used by (at least) GMX and IONOS doesn't support this command and closes the connection after receiving the command due to "too many errors".

We'll probably release a beta version fixing this issue later today.

**Comment by ungutknut** [comment]
Thanks for the fast reply! Impressive that you've already figured it out. And indeed it's a GMX account in my case too.

BTW: It'd be great if there was some error message telling me when a connection wasn't successful. 

Some months ago there was another bug in K-9 where it wasn't showing an error after smtp server certificate changed. Several messages, I believed I've sent, weren't actually sent. This time it was K-9 making me believe there are no messages for days after I got suspicious and checked the server settings.

**Comment by cketti** [comment]
The latest beta version should fix the issue.

See https://forum.k9mail.app/t/beta-k-9-mail-5-910/4035

**Comment by mmueller-kaffeeschluerfercom** [comment]
I also stumbled on this, and also on following:

> BTW: It'd be great if there was some error message telling me when a connection wasn't successful.

There's #1058.

I think that a very basic error notification is still better than none. I need to know if my email system does not work, even if it's "just" on the phone.
