### ISSUE TITLE
HTML code in message preview

### ISSUE THREAD

**Issue by PhoenixIV** [thunderbird/thunderbird-android#5889]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

8.1.0 LineageOS

### Steps to reproduce

I found https://github.com/k9mail/k-9/issues/640
which was resolved years ago, so I decided to create a new issue.

I have emails in my inbox that display html tags in the preview, but not in the body (where it is formatted).
This is true for only one contact. Other html mails are previewed without tags.

### Expected behavior

No tags

### Logs

I am happy to provide detailed info about the mails concerned in private (may contain sensitive information)
If you would point out specific sections from the mail source that I can post here I will happily do so.

**Comment by cketti** [comment]
This is most likely because the plain text part of the message contains HTML tags. And we use this part to extract the preview text. It looks fine when viewing the message because we use the HTML part to actually display the message.

Can you attach the source of such a message to confirm this?

The proper fix in K-9 Mail is to extract the preview text from the message part that we actually display. I created #5890 for that.

**Comment by PhoenixIV** [comment]
I can confirm there is HTML in the plain part of the email. I checked with Thunderbird and thumb-upped https://github.com/k9mail/k-9/issues/1018

I hope that will be enough? I may also send you that email, but I do not see the need for it anymore. I try to keep it secret.

**Comment by cketti** [comment]
Thanks for confirming. In that case changing the way we extract the preview text (#5890) is the right thing to do. Closing this issue.
