### ISSUE TITLE
Error when sending a mail 

### ISSUE THREAD

**Issue by muessjoeh** [thunderbird/thunderbird-android#5912]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.910

### Where did you get the app from?

Google Play

### Android version

10

### Device model

Samsung Galaxy A6+

### Steps to reproduce

1. Type a mail
2. Press on 'send'
3. Sometimes, an error window pops up that the key service cannot be connected
4. Click on the sender mail address and change it to itself. In other words, it has not changed at all.
5. Now, the send button works 

### Expected behavior

It should send without any error 

### Actual behavior

It gives an error. This happens around 70% of the time. So, this happens not always.

**Comment by cketti** [comment]
Please keep in mind that someone reading your bug report doesn't know how you've configured your K-9 Mail. Make sure to include all relevant information in the steps to reproduce the issue. Please also include the exact text of error messages or a screenshot of them.

Since you've mentioned a "key service" I'm guessing you have end-to-end encryption enabled. K-9 Mail includes your public key in all outgoing messages. However, it doesn't store this information itself. The key is managed by OpenKeychain. So K-9 Mail has to connect to the app when sending a message.

I'm guessing the Android version on your device marks OpenKeychain as inactive when its UI hasn't been started in a while. This could prevent K-9 Mail from talking to the app. This is a common problem with Xiaomi devices (see https://forum.k9mail.app/t/how-do-i-make-k-9-mail-work-with-openkeychain-on-xiaomis-miui/82). It might also be a problem with Samsung devices. See https://dontkillmyapp.com/samsung

Anyway, this is just guessing. To have a chance at finding out what's going on we need a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
