### ISSUE TITLE
sleep mode is enabled outside the configured time

### ISSUE THREAD

**Issue by saber716rus** [thunderbird/thunderbird-android#5919]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

11

### Device model

Redmi note 8 pro

### Steps to reproduce

turned on the sleep mode, set the time to turn on the sleep mode

### Expected behavior

the sleep mode is activated only according to the schedule and in the configured time interval.

### Actual behavior

enabled outside of the configured time.

**Comment by saber716rus** [comment]
![Screenshot_2022-02-15-11-17-28-648_com fsck k9](https://user-images.githubusercontent.com/22714555/154023827-4f37b038-111f-4bc6-aa00-951094df052d.jpg)
there is a photo-video screenshot of the problem.

**Comment by saber716rus** [comment]
[](https://disk.yandex.ru/i/jOhadKf-CU0zCg)

**Comment by saber716rus** [comment]
https://disk.yandex.ru/i/jOhadKf-CU0zCg video screenshot of the problem

**Comment by cketti** [comment]
I believe that by "sleep mode" you mean the setting that is called "quiet time". It doesn't prevent the app from checking mail, it only suppresses notification during quiet time.

I looks like the Push notification contains the text "Спящий режим до тех пор, пока не будет разрешена фоновая синхронизация". That's "Sleeping until background sync is allowed".
So the app is not using a Push connection because background sync is currently disabled for the app. You can change that by setting *Settings → General settings → Network → Background sync* to *Always*. Or, if it is set to *When 'Auto-sync is checked*, enable "auto-sync" in your Android settings, usually found under "accounts".

PS: Next time please switch the app language to English when recording a video or taking a screenshot.

**Comment by saber716rus** [comment]
yes, you're right, it's not a bug. thank you, you can close it.
