### ISSUE TITLE
Incorrect encoding of the email text / Torrent tracker SoftPilot.win

### ISSUE THREAD

**Issue by D3ZOXY** [thunderbird/thunderbird-android#5951]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.912

### Where did you get the app from?

F-Droid

### Android version

12 | KOSP 2.3 Unofficial

### Device model

Realme X2 CN (RMX1991)

### Steps to reproduce

1. Wait for an email from this tracker.
2. Open the email and see that the encoding of the text of the email is incorrect.
![Screenshot_20220226-175547_Nova Launcher](https://user-images.githubusercontent.com/47178587/157188524-d7328604-0aa4-4feb-b25b-a0b2f1ffa5d4.png)
![Screenshot_20220226-175559_Почта K-9](https://user-images.githubusercontent.com/47178587/157188568-430168f7-50c6-4acd-8315-1fc7997045b9.png)

### Expected behavior

Emails received from SoftPilot.win have the correct text encoding.

### Actual behavior

Emails received from SoftPilot.win have the incorrect text encoding.

**Comment by cketti** [comment]
Can you attach the message source? 

Chances are the email is not properly declaring the character set that is used. That would be a bug in the software creating the message, not one in K-9 Mail.
Many email apps attempt to guess the character set in order to display the message as intended. K-9 Mail doesn't do that. So the message being displayed "correctly" in other apps is not an indication that the message isn't broken.

**Comment by D3ZOXY** [comment]
[Uploading SoftPilot.win_Broken_Email.zip…]()

**Comment by cketti** [comment]
This ZIP only contains an HTML document. I was looking for the whole message source, including email headers.

**Comment by D3ZOXY** [comment]
How do I get it?

**Comment by D3ZOXY** [comment]
[Uploading SoftPilot.win_Broken_Email.zip…]()

**Comment by D3ZOXY** [comment]
Thanks.
Yes, I will inform the authors of the site about it.
