### ISSUE TITLE
Message displays only single line

### ISSUE THREAD

**Issue by edemeulle** [thunderbird/thunderbird-android#598]
When reading through messages in inbox via IMAP, I typically tap archive to move to next item. Frequently, K9 shows the next message nearly blank with only one line of text visible.  Swiping up/down scrolls the message through this one line area. Tapping previous, then next causes the message to be displayed normally. Currently on Android 5.0.2 on Nexus 7 and K9 5.004. Please let me know what additional info would be helpful.

**Comment by AMDG2** [comment]
:+1: I also have the same issue !

**Comment by olivercarl** [comment]
On https://code.google.com/p/k9mail/issues/detail?id=6604 there is a long list of affected users already.
Seems started with Android 5.0 (different phones). Small help: rotated the phone (and optionally rotate right back).
However, I have doubts that this project is still alive, as there is no reaction to such a severe usability issue since Android 5.0 came out... :-(

**Comment by inducer** [comment]
FWIW, there's a description of a posse patch on the Google code page.

**Comment by ssieb** [comment]
This is fixed in the next version.  You can get it now at https://github.com/k9mail/k-9/releases/tag/5.005

**Comment by inducer** [comment]
Any chance of a pre-release (5.10x) with that fix in it?

**Comment by cketti** [comment]
Done. https://github.com/k9mail/k-9/releases/tag/5.106

5.005 should be available via Google Play shortly.

**Comment by inducer** [comment]
Thank you!
