### ISSUE TITLE
Something is wrong with K9's handling of attachments.

### ISSUE THREAD

**Issue by ulrichloose** [thunderbird/thunderbird-android#5995]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.914

### Android version

10

### Device model

Levono tab, ulefone

### Steps to reproduce

It's about an email that contains calendar.ics as an attachment. That will show up correctly as an attachment.  

This is the case with three of my devices, all with Android 10 and the latest K9 version from the main branch. A test in the Gmail app shows no problems.

### Expected behavior

If you click on the attachment, the calendar app should open

If you download the file, it should be saved under calendar.ics

### Actual behavior

When you click on it, the option "Open with" is displayed.
Only programs that can display .txt files are displayed.

If you download the file, it will be saved under calendar.ics.txt.

I suspect some problem with text/calendar as mimetype and .ics is wrongly treated as a text file.

**Comment by cketti** [comment]
Can you provide the raw data of the message (including headers)?

**Comment by ulrichloose** [comment]
Thank you for your prompt reply!

The demand for the raw data made me suspicious and that's exactly what I looked at. I now have the strong suspicion that the sender sent the mail incorrectly and that K9 is not doing something wrong:

--e6de0272f6950574528fb0ae98407b19b8a4663b766082f22a2b589ee445
Content-Disposition: attachment; filename="calendar.ics"
Content transfer encoding: base64
Content type: text/plain; name="calendar.ics"

K9 only evaluates the content type: text/plain and so K9 behaves correctly. The sender of the mail should have entered text/calendar there?!

As a test, I sent myself the same attachment from Apple Mail and it says in the header

--Apple Mail=_39A51940-3E44-4408-A915-924C9C04532C
Content-Disposition: attachment;
filename=calendar.ics
Content type: text/calendar;
x-unix-mode=0644;
name="calendar.ics"
Content-Transfer-Encoding: quoted-printable

and K9 handles the mail correctly.

I'm just a little "unsure" because both apple mail and gmail android handle the calendar.ics attachment correctly, even if the mime type is text/plain. So they seem to be evaluating the .ics extension...

No error that needs to be corrected, but a correct procedure that other mail programs handle a little more loosely...

**Comment by cketti** [comment]
Unless the content type is `application/octet-stream`, K-9 Mail will use the original file name and type when saving the file using Android's system dialog; same when viewing a file. As you've experienced first hand, this doesn't always lead to the desired result. 
It's probably your Android version that added the `.txt` suffix to the provided file name in the "save" system dialog. You should be able to edit the file name at the bottom of the screen before saving the file. This will at least increase the chance that the desired content type will be derived from the file extension when opening the file from a file manager. Document providers (apps like Google Drive and Dropbox that can hook into the save screen) are given the original content type, though. So this is not guaranteed to work.

The best way to get rid of this issue is to get the sender of the message to use the proper content type.
