### ISSUE TITLE
Account listed multiple times

### ISSUE THREAD

**Issue by pellenilsson** [thunderbird/thunderbird-android#615]
I have three email accounts, which were before listed like this:

```
AccountA
AccountB
AccountC
```

After long-pressing the last account and choosing "Move up", I got two copies of the account that I tried to move, like this:

```
AccountA
AccountC
AccountB
AccountC
```

This state persisted after restarting the app (I think, the app was not listed in task manager), but problem went away after restarting phone, and `AccountC` is now in the middle as expected. Problem is not reproducible, I can now move them around as I please. When I had the problem I moved the account shortly after creating it.

K-9 Mail version: 5.004
Android version: 4.4.2
Phone: LG G2

**Comment by philipwhiuk** [comment]
K-9 Mail version: commit id 74c6e764338d312dab49bb6e5499ee82d2c86c83
Android version: 6.0.1
Phone: Nexus 6P 

I added a new account and was able to reproduce it.

It doesn't appear to be a bug with what Account.move does. Here we see, after account creation we have 3 entries in the list before the move is applied, and three after. Yet we see the new account (4b6) is duplicated in the view.

03-30 17:10:25.150 30217-31323/com.fsck.k9.debug V/k9: Old list:[
   e4cc752c-2b4c-4efb-bd57-4adb84e7340e, 
   4b6a0947-3ec4-4584-b466-305d3552c27e, 
   eb9542ac-a17f-418d-81bd-23578a2f3382]
03-30 17:10:25.150 30217-31323/com.fsck.k9.debug V/k9: New list:[
   e4cc752c-2b4c-4efb-bd57-4adb84e7340e, 
   eb9542ac-a17f-418d-81bd-23578a2f3382, 
   4b6a0947-3ec4-4584-b466-305d3552c27e]

The bug is actually in Preferences. We are (for a reason I can't fathom) keeping a reference to the new account and adding it at the bottom both in `newAccount` and when `loadAccounts` is called. The issue seems to be that the new account is already in the list of `accountUuids` at this point so we add it twice in `loadAccounts`.

I think the quick fix is to add an if() check so that we only add it to the list if it doesn't already exist. It's nulled after this point anyway.
