### ISSUE TITLE
fdroid app changelog belongs to V. 6.202 NOT V. 6.302 

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#6293]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

1.15.2 (fdroid app)

### Where did you get the app from?

F-Droid

### Android version

9

### Steps to reproduce

1. open fdroid app
2. update or search for k9 app

unfortunatly fastlane has gone crazy......

ps. i will not update :: unless some critical bug has been fixed or if there is some issue with my present version

### Expected behavior

1. show release notes of stable or unstable
2. show both version release notes

### Actual behavior

showing release notes of stable

### Logs

![k9 fdroid app screenshot](https://user-images.githubusercontent.com/109575325/189494877-048a1830-1659-4212-9bf1-1558e9345c81.jpg)

**Comment by cketti** [comment]
I'm not sure what you're asking for. I can't see anything wrong with the data in our repository. If anything is not working like it should, please report it to the F-Droid project.

**Comment by jindam-listserv** [comment]
@cketti 
* **[Version 6.302 (2022-09-05)](https://thundernest.github.io/k-9/changelog_main_branch.xml)**
 * Fixed moving to next/previous message when sorting the message list by read/unread or starred/unstarred
 * Fixed a crash when a third-party app shared a file to K-9 Mail without granting access to it
 * Keep some more attributes when sanitizing HTML
 * A lot of internal changes and improvements
 * Updated translations
 
* **[Version 6.202 (2022-07-26)](https://thundernest.github.io/k-9/changelog_6.2-MAINT_branch.xml)** 
* Increased timeout when sending messages because some users have reported problems with sending large attachments
* Allow all URI schemes in HTML links
* Fixed display bug with search in general settings
* When composing messages don't hide Cc and Bcc fields if they contain incomplete email addresses
