### ISSUE TITLE
Email I reply to show up twice in the Sent folder

### ISSUE THREAD

**Issue by Donkey-Doug** [thunderbird/thunderbird-android#6337]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.305 (but also older versions)

### Android version

Android 12 (LineageOS)

### Device model

Xiaomi Mi 9T Pro

### Steps to reproduce

1. Reply to an email
2. Go to sent folder
3. The reply is shown twice

### Expected behavior

Show reply once

### Actual behavior

Shows replies twice

### Logs

-

**Comment by cketti** [comment]
Some providers automatically put sent messages in the Sent folder. In those cases you should disable uploading sent messages in K-9 Mail. You can find the setting under *Settings → [Account] → Sending mail → Upload sent messages*.

In the future please use the [forum](https://forum.k9mail.app/) to ask for help. You'll be redirected here in case the behavior turns out to be a bug.

**Comment by Donkey-Doug** [comment]
This solved the issue. Thanks
