### ISSUE TITLE
Notification error on checking for new mail

### ISSUE THREAD

**Issue by Chesshur** [thunderbird/thunderbird-android#6492]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.201

### Where did you get the app from?

Google Play

### Android version

Android 9

### Device model

Samsung Galaxy J3 (SM-J337v) 

### Steps to reproduce

1)Set notifications to any other sound except default notification sound
2) wait for set fetch interval to check for new mail.

### Expected behavior

Have set notification sound to play and receive new message notification 

### Actual behavior

Received the following error notification with no sound whatsoever instead of new messages notification

![39c424e3302f606d745a6b61357ffbaff951c9c8](https://user-images.githubusercontent.com/16483615/204039932-f86eeac8-a2d4-442f-9df4-8c46e9a800f7.jpeg)

I have to open the app and manually check for new mail when notification sound is not set to the default sound. 

### Logs

[k9mail-logs (2).txt](https://github.com/thundernest/k-9/files/10094660/k9mail-logs.2.txt)

**Comment by cketti** [comment]
The system is returning the following error when the app tries to post a notification:
```
java.lang.SecurityException: UID 10162 does not have permission to content://media/external/audio/media/3196 [user 0]
```

It's unclear why the system would allow you to pick a notification sound and then report an error when the app tries to use it with a notification. But Android versions from Samsung sometimes have these weird errors.

I assume you used K-9 Mail's settings screen to set the notification sound. Instead of doing that, tap *Messages* under *Notification categories* to get to the system screen to configure notifications. Then change the notification sound there. Please let us know if that works.

<img src="https://user-images.githubusercontent.com/218061/204042978-fac2d335-8424-45de-87e6-a75bb78d8921.png" alt="image" width=300>

**Comment by Chesshur** [comment]
I set the sound to a different one using my phone's notification settings on the phone's 
settings menu instead of through the app or the app info screen and that seems to have fixed the bug for now.

**Comment by Chesshur** [comment]
It happened again! It appears that I have to set the sound through the phone's settings constantly  now for it to push notifications other than the default sound. Here's the latest debug log. 

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/10095063/k9mail-logs.txt)

**Comment by cketti** [comment]
Whenever you change any of vibration, notification light, or sound inside the app you have to go to the system screen and select the desired notification sound again. If possible, avoid updating notifications from inside the app.

From reading reports on the internet I believe it's possible that this bug in Android 9 only occurs when an app that didn't declare support for Android 9 is updated to an app version that does declare support for Android 9 (or newer). So you could try uninstalling the app, then reinstalling, and see if that makes a difference.

**Comment by cketti** [comment]
I don't see an easy way to fix this. It doesn't seem to affect a lot of users. I don't think it's useful to keep around an open issue for this.
