### ISSUE TITLE
Not prompting for new password when changed elsewhere

### ISSUE THREAD

**Issue by fmatorras** [thunderbird/thunderbird-android#6744]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.509

### Where did you get the app from?

Google Play

### Android version

12

### Steps to reproduce

1. have different mailboxes on k9
2. change the password of one of them outside k9 (ie web or thunderbird on windows)
3. try to access to new emails on the mailbox

### Expected behavior

realise the password has changed and prompting a request for writing a new one.

### Actual behavior

nothing, it just stops dowloading new messages without any notification or error message

**Comment by cketti** [comment]
K-9 Mail should display an error notification in that case. Can you record a debug log while trying to sync a folder after changing the password outside of K-9 Mail.

See https://github.com/thundernest/k-9/wiki/LoggingErrors

**Comment by fmatorras** [comment]
Hi, thanks for having a look. It does not display anything.  Log attached, the mailbox with changed pass is "ifca"
[k9mail-logs.txt](https://github.com/thundernest/k-9/files/10972070/k9mail-logs.txt)

**Comment by cketti** [comment]
Thanks for the log.

When the initial authentication fails, K-9 Mail falls back to using the LOGIN command. In your case, the server closed the connection instead of sending a negative response to that LOGIN command. K-9 Mail treats this as intermittent connection problem and silently ignores it.

I'll update the code to return the original authentication error if any non-authentication error occurs during the LOGIN fallback.

**Comment by fmatorras** [comment]
thanks!
