### ISSUE TITLE
URL parsing in plain text mails: parenthesis character at the end

### ISSUE THREAD

**Issue by Djfe** [thunderbird/thunderbird-android#6754]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.509

### Where did you get the app from?

Other

### Android version

13

### Device model

Pixel 7 Pro

### Steps to reproduce

Open mail containing the following plain text:
```
(Github issue: https://github.com/thundernest/k-9/issues/6754)
```

### Expected behavior

Thunderbird parses this as:
(Github issue:[ https://github.com/thundernest/k-9/issues/6754](https://github.com/thundernest/k-9/issues/6754))

### Actual behavior

K-9 parses this as:
(Github issue: [https://github.com/thundernest/k-9/issues/6754)](https://github.com/thundernest/k-9/issues/6754%29)

Yes, parenthesis might be valid in certain cases, but in mails people should escape them or use %29 instead.
It's far more likely that the link was placed inside parenthesis and the closing parenthesis at the end isn't part of the url.

**Comment by cketti** [comment]
Browsers don't encode parentheses in URLs when copying them to the clipboard. Unless all of them do, I don't think URL detectors should assume a valid character in a URL doesn't belong to the URL.

I've created issue #6756 to make this situation less likely when composing messages with K-9 Mail.

**Comment by Djfe** [comment]
What do you mean by that? 😅
That you will only fix this for composing mails but don't see a solution for viewing received mails?
Is it the senders fault, if other mailclients like thunderbird interpret the following links as intentioned? (this is about plain text mails only)
![Screenshot_20230314-164107~2](https://user-images.githubusercontent.com/5685512/225056233-13077fef-aa79-4e97-988e-e35729c1a4a7.png)

overall: what speaks against making parenthesis a character that needs to be encoded in plain text mails? the rfc? yes browsers won't encode these characters therefore valid links with parenthesis wouldn't have encoded parenthesis. unless a user encodes them manually
about practicality: github allows URLs to contain parenthesis, but not if they end with a parenthesis
It's not a clean solution: but your code could strip a closing parenthesis from the end of a url only and most cases would work fine, I think.

overall it's up to you :)
Thanks for taking a look

I like your proposal/solution for composing mails with <> encoded links 👍

**Comment by Djfe** [comment]
I just noticed something: why are the dots after the closing parenthesis blue? They are not (recognized as) part of the link.

**Comment by cketti** [comment]
> Is it the senders fault, if other mailclients like thunderbird interpret the following links as intentioned? (this is about plain text mails only)

The plain text doesn't contain information on what URL was intended. Humans can mostly tell what the sender intended, machines can not. It's the sender's fault for including ambiguous text. The fix for this is to use angle brackets when composing the message, not asking every software in the world to use the same guessing algorithm to parse ambiguous text.

> overall: what speaks against making parenthesis a character that needs to be encoded in plain text mails? the rfc? yes browsers won't encode these characters therefore valid links with parenthesis wouldn't have encoded parenthesis. unless a user encodes them manually

What's easier? Surrounding a URL by angle brackets or remembering the URL-encoding of `(` and `)`?
And you don't have to look hard to find URLs ending in a parenthesis. Example: https://en.wikipedia.org/wiki/Disambiguation_(disambiguation)

Of course you can start counting matching parentheses (like GitHub apparently does), because unmatched ones are rare in URLs. But that doesn't solve the problem. It only makes it slightly smaller; and the code much more complex.

**Comment by Djfe** [comment]
thanks
