### ISSUE TITLE
Disappearing message toolbar

### ISSUE THREAD

**Issue by glocalglocal** [thunderbird/thunderbird-android#6770]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.509

### Where did you get the app from?

F-Droid

### Android version

7

### Device model

Moto G4

### Steps to reproduce

1. Open message
2. Click on a link inside the email, View webpage in Firefox, and share the link from within Firefox
3. Open tasks and select K9 to return to the email I was reading4. 

### Expected behavior

It would show the email I was reading earlier with the usual buttons as before I followed the link that took me to Firefox. 

### Actual behavior

The buttons are not there any more. To get them back I have to return to the list of messages and reopen the message. 

![image](https://user-images.githubusercontent.com/16408198/225974090-03f7c6ff-3367-43d8-bf43-41fcf5693586.png)

I think this started happening in the last two versions. It happens quite often but I can't reproduce it every single time. When it happens I think it is always after I left the message and returned to it.

**Comment by cketti** [comment]
This is most likely because Firefox or another foreground process needs a lot of memory and the system is killing apps in the background. K-9 Mail didn't properly save its state and so restoring the app will lead to the message view menu items not being added to the toolbar.

This should be fixed in the next beta, K-9 Mail 6.511.
