### ISSUE TITLE
Message view: Account chip not displayed when viewing messages in a thread (from Unified Inbox)

### ISSUE THREAD

**Issue by csant** [thunderbird/thunderbird-android#6824]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.600

### Where did you get the app from?

Google Play

### Android version

13

### Steps to reproduce

1. Go to Unified Inbox
2. Click on a message which is not in a message thread.
3. Enjoy the restyled message view.

1. Go to Unified Inbox
2. Click on a message which is part of a message thread - you'll be taken to the thread view
3. Click on a message in the thread view
4. Enjoy the "old" message view instead of the restyled one.

### Expected behavior

I would expect the new message view to be consistently seen in every message view.

### Actual behavior

When I click on a message, which is not in a message thread, in the Unified Inbox, I see the new message view, with indication at the top which account the message comes from.

When I click on a message in the Unified Inbox which takes me to the thread view (i.e. the view listing all messages from the same thread) and then click on the message, I still see the old message view (without the indication of the account). The account is shown in the thread view (at the top, but with a simple, unstyled display), but not in the final message view.

**Comment by mhf1998** [comment]
Hello @cketti .
We have thoroughly tested and replicated the bug scenario, and it has occurred for us on the following device and software configuration:

Phone Model: Samsung A6
Android Version: 10
K9 App Version: 6.702
App Source: F-Droid

Unified Inbox -> Click on a message which is not in a message thread -> Restyled message view :
![1](https://github.com/thundernest/k-9/assets/34542204/704bef9d-6c53-4350-8b48-196070a7751c)


Unified Inbox -> Click on a message which is part of a message thread - you'll be taken to the thread view -> Click on a message in the thread view -> "old" message view instead of the restyled one:
![2](https://github.com/thundernest/k-9/assets/34542204/0916deaa-a908-4b9a-9c8f-b7863256cc29)
