### ISSUE TITLE
IMAP folders are empty

### ISSUE THREAD

**Issue by Wolf35978** [thunderbird/thunderbird-android#6980]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.705

### Where did you get the app from?

Google Play

### Android version

13

### Device model

OnePlus 8 pro

### Steps to reproduce

Go to folder in IMAP account and open it. No mails are visible.

### Expected behavior

Mails should be visible. The folder isn't empty. There are 230 unread Mails indicated.

### Actual behavior

Some folders are empty. But not all of them. Interesting thing: If you use the search function the mails found get visible. If you delete the searched word the folder is shown as empty again.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/11738784/k9mail-logs.txt)

**Comment by Wolf35978** [comment]
After changing amount of messages to show from 100 to 50 and back the messages now are visible again. It's a bug anyway.

**Comment by fnxweb** [comment]
I have the same with the same, latest beta.  This workaround did not work for me, to make mine visible I had to change _all time_ to _last month_ (I also have local copies set to 1,000, although I don't have that many emails in my Inbox).  Just changing that to 50 [keeping _all time_] didn't help me.

**Comment by cketti** [comment]
@Wolf35978: Thanks for the debug log :+1:

Your folder contains a message with at least one email address that has a local-part (the part before the `@`) that exceeds the allowed 64 characters. We recently added another parser for email addresses that is stricter than what we had before. Combined with some other errors this leads to the behavior you're seeing.

This bug will be fixed in the next beta version. Until then you should be able to (partly) work around the bug by disabling *Settings → General settings → Display → Show contact names*.

**Comment by Wolf35978** [comment]
Cool! Thank you for the quick response!
