### ISSUE TITLE
Return to message list upon "Mark as unread"

### ISSUE THREAD

**Issue by eltos** [thunderbird/thunderbird-android#7081]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

When using the "Mark as unread" action from the message view, I always immediately afterwards return to the message list using the back button.

### Suggested solution

Using the "Mark as unread" action should automatically return to the message list, just like the "Delete message" action does (if the respective setting is enabled, or go to the next message if that setting is enabled).

**Comment by cketti** [comment]
We've talked about this internally and decided we will add a new setting to specify the navigation behavior after a message has been marked as unread by the user. The options we want to support are:
- Stay on the current message (current behavior)
- Return to message list (requested behavior)

When removing a message (delete, move, spam, archive) we also support moving to the next or previous message. However, since the current message is not disappearing when marking it as unread, we see no reason to also support these options.

Since it's unlikely we'll add more options later, I suggest we make this a toggle and use the name "Return to list after mark as unread".
