### ISSUE TITLE
Text Selection broken on k9 mail 5.006 (latest available in Google store)

### ISSUE THREAD

**Issue by hpi3k** [thunderbird/thunderbird-android#710]
After tapping on next inside email message, text selection indicators show up but they are broken. Choosing text with them  result in simultaneous scroll of screen. 
Replicable on both Samsung Galaxy Grand Neo JB 4.2.2 and LG 3G S 4.4 KitKat

**Comment by cketti** [comment]
Is this the same as issue #716?

**Comment by buttercookie42** [comment]
It does sound similar, but not quite the same, because I don't remember having any problems clicking on links.
Zooming out on the other hand does help somewhat, because it makes it less probable that the message will be able to scroll.

Basically it's this problem: I long tap a word - the text selection handles appear. I then tap one of the selection handles. If I try moving them left/right, everything's fine: Just the selection handles move while the message remains still. Only when I'm nearing the edge of the screen does the message start scrolling as well, as expected.
If on the other hand I'm trying to move the selection handles up or down, the whole message starts scrolling immediately, meaning it's almost impossible to select more than one line of text. Landscape or portrait mode doesn't make any difference as long as the message is large enough to scroll vertically in both orientations.

In case it's relevant, I'm using a Samsung Galaxy S3 Mini with Android 4.1.2.

**Comment by hpi3k** [comment]
I concur with everything what buttercookie42 said. It's exactly like this.

**Comment by hpi3k** [comment]
Just for clarify, I made a typo in first post (LG G3 s instead LG 3G S)
