### ISSUE TITLE
Often Cannot click or select text or links

### ISSUE THREAD

**Issue by jssh** [thunderbird/thunderbird-android#716]
Often when I open an email I cannot click or select text or links. If I adjust the screen by zooming in or out, it then works fine. Been having this issue for a year, since v 5. Now in 5.006, Android 4.4.4

**Comment by techyjt** [comment]
I have the exact same issues.

**Comment by cketti** [comment]
What devices and Android versions are you using?

**Comment by jssh** [comment]
I've had it on multiple devices. Last was a Original moto x, currently Droid Turbo on Android 4.4.4 now.


-------- Original Message --------

**Comment by techyjt** [comment]
I have had it happen on a LG D950 running Android 4.4.2.  Also on a Samsung Galaxy S5 4.4.4.

**Comment by doublehp** [comment]
Android 4.4.2
All K9 versions since 18 months
HTC One M8

When a message contains an URL link, tapping on it works best is message is zoomed out (when text is small). The more you zoom in to be able to read content of message, the less chance you have to get link open on tapping it. I have tried to tap at begin of link, end, first line, last line ... it just won't open.

This is specific to K9. It's not a tactile issue, because I never had that problem in an web browser.

**Comment by philipwhiuk** [comment]
We are using a WebView pretty much directly here. I can't see that we are going to be able to fix this.

**Comment by doublehp** [comment]
On 13/04/16 01:43, Philip wrote:
> We are using a WebView pretty much directly here. I can't see that we are
> going to be able to fix this.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/k9mail/k-9/issues/716#issuecomment-209151426>
> 

Tap to click is a basic feature of tactile smartphones since nearly 10
years. Having to spend over 30s to resize things, leave mail, and open it
again is almost as if I had to stop and leave my car and lock it from
outside to be able to change the gear on motorway ...

Whatever you use has to be open source, or don't use it. Just fix it.

When it turns me out of nerves, I switch for an other mail reader !!!

JUST TO TAP ON A LINK

-- 
 >o_/ DEMAINE Benoît-Pierre (aka DoubleHP) http://benoit.demaine.info/
If computing were an exact science, IT engineers would'nt have work \_o<

"So all that's left, Is the proof that love's not only blind but deaf."
(FAKE TALES OF SAN FRANCISCO, Arctic Monkeys)

**Comment by philipwhiuk** [comment]
Many other apps embed web content in them similarly. Is it just K-9 you see this on?

**Comment by doublehp** [comment]
On 13/04/16 13:14, Philip wrote:
> Many other apps embed web content in them similarly. Is it just K-9 you
> see this on?
> 

I do not know if/which other apps may use your WebView stuff, but, only K9
is troubling me about tapping links. When other apps are non reactive,
it's usually either because the whole system is slow, or because my wall
charger is making the touch layer erratic ... and then, it affects all apps.

But K9 issue, it's happening even away from charger, and system is
reactive, or only K9 is running (all other apps forced killed).

Only thing customed on my phone: I changed my DPI using Xposed (root).
This bug always ennoyed me in K9, since the first days using it; bug is
stable (once in 3 or 4 times); always needs to zoom out the message;
usually works best when full zoom out, and trying to tap on small text;
the more I zoom to tap on bigger letter, the less it works. That's why I
thought it could be related to DPI ... but that's not an acceptable
behaviour. Tap works in all DPI and zoom in web browsers (HTC, Chrome,
Opera, Firefox) and other mail readers (HTC, Gmail) and contact editors
(which may contain URLs - but is not resizable by pinch).

-- 
 >o_/ DEMAINE Benoît-Pierre (aka DoubleHP) http://benoit.demaine.info/
If computing were an exact science, IT engineers would'nt have work \_o<

"So all that's left, Is the proof that love's not only blind but deaf."
(FAKE TALES OF SAN FRANCISCO, Arctic Monkeys)

**Comment by k9user** [comment]
I still have this problem on my LG Aristo using Android 7.0

**Comment by cketti** [comment]
It appears to work fine for most users. I haven't been able to reproduce this on any of my devices.
Chances are it's a WebView issue we wouldn't be able to fix anyway.
