### ISSUE TITLE
Mail gets stuck in outbox

### ISSUE THREAD

**Issue by sgeklorer** [thunderbird/thunderbird-android#7228]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Nokia 5.3 (TA-1234)

### Steps to reproduce

Use K9 for a while.
At some point over time send an email, discover that it wasn't sent.
Find the message stuck in the outbox.
To get the message to send, move it to drafts and send again: it works.

This happens to me roughly once every 2-3 months.
It may have a correlation with being on a poor network, but I can't be sure (am always in and out of poor networks so it certainly does not happen every time). I also don't understand how poor network access would result in corruption of the outbox message, which is stored locally on the device.

### Expected behavior

K9 should send the emails.
K9 should show an error that an outbox message has not been sent/can't be sent (possibly after trying a certain number of times, or for a certain duration of time).

### Actual behavior

The emails sit in the outbox and are not sent.
There are no notifications that an error has occurred.

### Logs

10-10 08:26:55.404 18342 18390 I MessagingController: Running command 'sendPendingMessages', seq = 250 (background priority)
10-10 08:26:55.449 18342 18390 I MessagingController: Scanning Outbox folder for messages to send
10-10 08:26:55.450 18342 18390 V MessagingController: Skipping sending message K9LOCAL:3dd5bb9a-2b40-4958-b26b-8ad4a9c6f384 (reason: error)
10-10 08:26:55.451 18342 18390 V MessagingController: Skipping sending message K9LOCAL:10b0d963-c088-4db1-b86d-b042a69224a3 (reason: error)
10-10 08:26:55.456 18342 18390 I MessagingController: Command 'sendPendingMessages' completed

There is nothing special about the two emails, one is a reply, one is new, one has attachments, one does not, one is to a single recipient, the other is to a small group.

**Comment by cketti** [comment]
K-9 Mail should already show an error notification when a message couldn't be sent. In this case it should also include an error message with more information on what went wrong. Make sure that you haven't disabled the "Miscellaneous" notification category in Android's notification settings for the app. You can get to the relevant screen via *Settings → [Account] → Notifications → Miscellaneous*.

If you upgrade to the beta version, the log will also contain the error message.

We're using issue #4602 to track improvements to how we handle send failures.

If it turns out that it was a configuration issue that prevented you from seeing the error notification, please close this issue. If not, please try to reproduce this error while recording a debug log, preferably using adb so old log messages won't get overwritten.

**Comment by sgeklorer** [comment]
Thank you for pointing me to issue #4602 - that seems to be very similar to what I am seeing, except their log does not include "reason: error", probably due to a version difference.
I can see in the settings that these "miscellaneous" messages are indeed disabled, so that fixes that and I'm happy to close this issue and let #4602 stand.
