### ISSUE TITLE
Add new option for "To" field in message header

### ISSUE THREAD

**Issue by BillH99999** [thunderbird/thunderbird-android#7301]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

I have 8 different email accounts defined in K-9 Mail. I use the Unified inbox.

It would really help if when I open a message sent to me in one of the accounts if it said the account name or email address in the header. Now it just says “me” which isn’t helpful at all.

### Suggested solution

Could an option be added to show the actual account name or email address so that I don’t have to constantly click on the header to see what the account is? I know the accounts are color coded, but who can remember the colors of 8 different email accounts.

**Comment by cketti** [comment]
When using the Unified Inbox the account name is displayed at the top of the screen. You can name an account however you like, including the email address of that account.

![image](https://github.com/thunderbird/thunderbird-android/assets/218061/2a2deb4b-6a5c-4a17-8067-7d2bba19611c)

If an account contains multiple identities the name of the identity is displayed (e.g. "to Secondary Identity" instead of "to me").
