### ISSUE TITLE
Import Settings from Desktop (Filter, ...)

### ISSUE THREAD

**Issue by SannyQ** [thunderbird/thunderbird-android#7319]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.710

### Problem you are trying to solve

I would like to see the possibility later to be able to take over the filters from the desktop. If that is already possible now, I would have liked to know.

### Suggested solution

I would like to see the possibility later to be able to take over the filters from the desktop. If that is already possible now, I would have liked to know.

**Comment by cketti** [comment]
K-9 Mail currently doesn't support message filters. See #908. 

This is an item on our roadmap: https://developer.thunderbird.net/planning/android-roadmap
Also, support for Thunderbird Sync to sync the filters between devices.

Closing this issue because we don't need a separate one to track these features.
