### ISSUE TITLE
New account setup crashes 

### ISSUE THREAD

**Issue by WebZakenAdvies** [thunderbird/thunderbird-android#7392]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.711

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Fairphone 4 

### Steps to reproduce

goto settings
click add account
fill in: xx@efkasoft.nl
click: next

### Expected behavior

Next step

### Actual behavior

Screen returns to settings, nothing done (no new account added)

### Logs

beginning of crash
11-28 15:18:11.121 24488 24488 E AndroidRuntime: FATAL EXCEPTION: main
11-28 15:18:11.121 24488 24488 E AndroidRuntime: Process: com.fsck.k9, PID: 24488
11-28 15:18:11.121 24488 24488 E AndroidRuntime: java.lang.IllegalArgumentException: Not a valid domain name: '_dc-mx.5a4e1a90e527.efkasoft.nl'
11-28 15:18:11.121 24488 24488 E AndroidRuntime: 	at app.k9mail.core.common.net.Domain.constructor-impl(Domain.kt:6)
11-28 15:18:11.121 24488 24488 E AndroidRuntime: 	at app.k9mail.core.common.net.DomainKt.toDomain(Domain.kt:10)
11-28 15:18:11.121 24488 24488 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.MiniDnsMxResolver.lookup-R1J1zPY(MiniDnsMxResolver.kt:14)
11-28 15:18:11.121 24488 24488 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.SuspendableMxResolver$lookup$2.invoke(SuspendableMxResolver.kt:10)
11-28 15:18:11.121 24488 24488 E AndroidRuntime: 	at app.k9mail.autodiscovery.autoconfig.SuspendableMxResolver$lookup$2.invoke(SuspendableMxResolver.kt:9)
11-28 15:18:11.121 24488 24488 E AndroidRuntime: 	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)

**Comment by cketti** [comment]
As part of the autoconfig process, K-9 Mail performs an MX loookup on the email domain. The MX record for `efkasoft.nl` points to `_dc-mx.5a4e1a90e527.efkasoft.nl`. That's a valid DNS name, but not a valid host name (underscores are not allowed). We didn't account for that possibility and that's why the app is crashing. We'll fix that by ignoring invalid MX records.

There's a good chance quite a few mail servers will refuse delivery to your domain. You might want to fix your MX record.
