### ISSUE TITLE
After a message is deleted, it does not immediately appear in the Trash folder

### ISSUE THREAD

**Issue by tdboorman** [thunderbird/thunderbird-android#7401]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.712

### Where did you get the app from?

Other

### Android version

13

### Steps to reproduce

1. Select an email in the Inbox.
2. Click on the trash can icon.
3. View the list of messages in the Trash folder.

### Expected behavior

The deleted email should immediately appear in the list of messages in the Trash folder.

### Actual behavior

The deleted email does not appear in the list of messages in the Trash folder until they are refreshed by swiping down.

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/13530716/k9mail-logs.txt)

**Comment by cketti** [comment]
This is because the app ignores `COPYUID` in untagged responses to the `UID MOVE` command (example A). In K-9 Mail 6.712 the `COPYUID` response code is only supported in a tagged response (example B).

Example A (from the log):
```
C: 223 UID MOVE 16481 "Trash"
S: * OK [COPYUID 1613389978 16481 15212] Moved UIDs.
S: * 23 EXPUNGE
S: 223 OK Move completed (0.009 + 0.000 secs).
```

Example B:
```
C: 17 UID MOVE 1737 "[Google Mail]/Trash"
S: * 29 EXPUNGE
S: * 28 EXISTS
S: 17 OK [COPYUID 8 1737 4366] (Success)
```

PR #7403 adds support for the `COPYUID` response code in untagged responses.
