### ISSUE TITLE
doesn't ask to accept self-signed certificate

### ISSUE THREAD

**Issue by mapausch** [thunderbird/thunderbird-android#7619]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.715

### Where did you get the app from?

F-Droid

### Android version

11 (LineageOS 18.1)

### Steps to reproduce

1. add account
2. enter data for a IMAP server that uses a self-signed certificate

### Expected behavior

K-9 mail should ask if I want to accept the self-signed certificate that gets presented by the IMAP server.
According to docs, K-9 should ask for confirmation.

### Actual behavior

don't get a dialog presented that asks for confirmation.
Instead I get a "Network error" (Read timed out).
IMAP server (dovecot) logs: Disconnected: Connection closed (no auth attempts in 60 secs): user=<>, rip=--redacted--, lip=--redacted--, TLS handshaking: Connection closed, session=<DEADbeefow0RZ77AqLKZ>
[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14230543/k9mail-logs.txt)

P.S.: with thunderbird on Linux I can login to the IMAP server. So seems to be and issue with K-9 mail, not on IMAP side.

**Comment by cketti** [comment]
Thanks for the bug report. If nothing else, it shows we need more debug logging.

If K-9 Mail displays a network error instead of a certificate error, it's very likely the app doesn't even get to the point where it receives the certificate chain from the server during the TLS handshake. This can have a multitude of reasons. 

Some things to try:
1. Use different networks (mobile vs. WiFi) and check if it makes a difference
2. Make sure you have the transport security mode right (try switching from *StartTLS* to *SSL/TLS* or the other way around)
3. Use the following settings to provoke a certificate error: Server: self-signed.badssl.com, Security: SSL/TLS, Port: 443, and dummy values for the other fields. If that doesn't work, your environment (Android version or network) are behaving in unexpected ways.

If you post the server settings, we could have a look ourselves.

**Comment by mapausch** [comment]
You are right.
K-9 Mail didn't even receive the certificate during TLS handshake.
Reason was, that the host OS had a smaller MTU configured than my test VM. So I assume that this scrambled something between VM and K-9.

Sorry for wasting your time, and many thanks for your immediate support and valuable input.
