### ISSUE TITLE
Issues with Google?

### ISSUE THREAD

**Issue by Vj9977** [thunderbird/thunderbird-android#7621]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

Very 6.6

### Where did you get the app from?

F-Droid

### Android version

Ver 12

### Device model

Motorola g play

### Steps to reproduce

Just follow the auto setup and you will see what I mean?

### Expected behavior

Does initiate handshake with Google?

### Actual behavior

Doesn't initiate handshake with Google?

**Comment by cketti** [comment]
Setting up a Gmail account is working fine for me.

Please update your initial post to include the exact version number of K-9 Mail and include a detailed description of what you're doing and what behavior you're observing. If there's an error message, please post it here.

**Comment by wartum** [comment]
Due to rather vague description I'm not sure if that's the same issue, but I've got something that seems similiar:

1. After opening K-9 I see welcome screen, i click next
2. I'm filling my gmail address in the form and click next
3. Click "Sign in with Google" button (Not sure if that's how actually button is labelled in english, I'm translating on the fly)
4. I'm redirected to google sign in page
5. Email adress is already filled, so I click Next
6. I fill my password and click next
7. I'm getting 2FA notification so I click "Yes, it's me"
8. Now K-9 screen is just full black, showing only URL in the bottom. No errors, just waiting indefinitely. If i choose the option "Open in firefox" it's also not getting opened, which indicates that may not be actually problem with K-9

The URL it gets stuck on has the form: https://accounts.google.com/v3/signin/challenge/dp? and then a long list of parameters.

**Comment by wartum** [comment]
Apparently it was google's problem. I tried to connect my account today and the issue was gone. K9 itself didn't get any update so I assume google just fixed authentication

**Comment by khurozov** [comment]
> Due to rather vague description I'm not sure if that's the same issue, but I've got something that seems similiar:
> 
> 1. After opening K-9 I see welcome screen, i click next
> 2. I'm filling my gmail address in the form and click next
> 3. Click "Sign in with Google" button (Not sure if that's how actually button is labelled in english, I'm translating on the fly)
> 4. I'm redirected to google sign in page
> 5. Email adress is already filled, so I click Next
> 6. I fill my password and click next
> 7. I'm getting 2FA notification so I click "Yes, it's me"
> 8. Now K-9 screen is just full black, showing only URL in the bottom. No errors, just waiting indefinitely. If i choose the option "Open in firefox" it's also not getting opened, which indicates that may not be actually problem with K-9
> 
> The URL it gets stuck on has the form: https://accounts.google.com/v3/signin/challenge/dp? and then a long list of parameters.
> 
> I initially downloaded the app from f-droid but, later tried with play store version and there's not difference, still the same issue. K-9 version is 6.603

I also having this problem like this. After confirming sms code app is tuck on google.com page. 
K-9 version is 6.803
