### ISSUE TITLE
Earthlink IMAP not working

### ISSUE THREAD

**Issue by fix4all** [thunderbird/thunderbird-android#7818]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.802

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Samsung S23

### Steps to reproduce

The following is the test sequence executed immediately after enabling logging:
From "Suspect Email" folder in K-9.
Deleted two messages.
Waited about 10 seconds.
Refreshed the folder and the messages reappeared.

### Expected behavior

Permanently delete the messages from the Earthlink server.

### Actual behavior

IMAP appears to be mirroring and displaying the folders based on the CLASS settings, yet syncing is not working correctly. Whatever I do in Webmail reflects in K-9, yet not the other way.

Any deletions in K-9 does not reflect in Webmail even after much elapsed time. The classes are correct. Syncing does not work in 1st or 2nd class folders. PUSH option is selected for the folders first and/or second class.

Verified that SMPT side (Port 587/StartTLS) is working. Also tried without security enabled.

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/15245928/k9mail-logs.txt)

**Comment by cketti** [comment]
You've probably configured a trash folder. So deleting messages from the folder "Suspect Email" will move them to the trash folder.

Until K-9 Mail 6.900, the app checked the source and destination folder for existence before moving a message. This was done using the STATUS command.

The command fails on Earthlink's IMAP server. From the log:
```text
>>> 22 STATUS "Suspect Email" (UIDVALIDITY)
<<<#22# [NO, Requested Object does not exist]
```

However, the folder does exist and opening it for reading (and presumably writing) works just fine. Again, from the log:
```text
>>> 25 EXAMINE "Suspect Email"
<<<#null# [FLAGS, [\Answered, \Flagged, \Draft, \Deleted, \Seen]]
<<<#null# [OK, [PERMANENTFLAGS, []],  ]
<<<#null# [2, EXISTS]
<<<#null# [0, RECENT]
<<<#null# [OK, [UIDVALIDITY, 1566965055],  ]
<<<#null# [OK, [UIDNEXT, 6321],  ]
<<<#25# [OK, [READ-ONLY], Completed]
```

K-9 Mail aborts the move operation due to the "NO" response to the STATUS command. Currently the app doesn't report this as an error to the user. But we already have an issue to add/improve error reporting.

Checking the source and destination folder for existence before performing a move operation doesn't add any value. That's why we recently removed that code. Please check out the current beta version (6.901) to see if that works for you and report back.

@fix4all: Can you please report the bug in Earthlink's IMAP server to them? It should be enough to point them at this issue.

**Comment by fix4all** [comment]
Yes, 6.901 resolved the issue!

Shall I simply forward the email to the Earthlink dev's or support with a brief explanation?

So, to be clear, is it the STATUS command/implementation that the IMAP server is not compliant with or lacks thereof?

Thank you!
Greg

-----Original Message-----
