### ISSUE TITLE
Crash in EmailProvider with unified inbox

### ISSUE THREAD

**Issue by tablet-theo** [thunderbird/thunderbird-android#783]
Hello,

when I select only one or more mails in the common inbox and click DELETE K9 crashes every time. When I do that in single folder, e.g. the inbox, it works.
I already tried to uninstall and reinstall K9 - no change, same problem.
Can anyone help me or does have the same problem?

I use K9 version 5.006, Android version 5.0 on a LG G3.

Thanky you for your help, tips & tricks.

**Comment by cketti** [comment]
To be able to fix the bug we need to know where exactly the app crashes. Android writes that information to the system log. Please follow these instructions to get us this information: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by tablet-theo** [comment]
Hello cketti and thank you for the answer.
I treid my very best to follow the instructions to create the log.
Step 1: Activate Debug Logging in K-9 Mail: OK
Step 2 OK
Step 3:
- Using adb: Can't find a downloadable file für PC, the links show no downloads (http://ady.my/viewer/platform-tool/index.html).
- Using aLogcat: Installed, configured and run as described but it shows nothing.

Why is it sooo complicated??? I thought i activate the debuggin and get just a normal logfile e.g. on the sd card...... :-(

**Comment by ChrMa** [comment]
Hello,

I also have trouble deleting emails. In 99% of the cases, K9 just crashes. However when it comes up again, the emails I tried to delete are actually gone.

While recording the following log, I deleted three emails. For some reason, the first two deletes worked without crashing K9. When deleting the third one (starting 21:55:37.577), it finally crashed.
https://gist.github.com/ChrMa/a0dc39051f0fd67a41cd

I did a few test runs, so K9 crashed and restarted only moments before I started capturing this log. This might be the reason, why it didn't crash on the first two deletion attempts.

I'm using K9 version 5.006 on a Galaxy S4 with Android 5.0.1.

**Comment by tablet-theo** [comment]
Hello ChrMa,

nice to here there are others having same problems. May you could give a short instruction how to create the requiered debug-log? The instructions I get follwing cketti's link are very complicated.

Thanks.

By the way: With my K9 the mails are sometime deleted, when restarting K) but sometime they're not. Strange...

**Comment by tablet-theo** [comment]
One thing more for others having problems with K9: To siedestepthe probleme I tried out the mail app "Touch Down". It is allmost detailed like K9 but not for free.

**Comment by ChrMa** [comment]
Hello tablet-theo,

recording a debug-log is not exactly easy. You have two options:

1. Record the log directly on the device using an app like aLogCat or CatLog. However, with Android version 4.1 or higher you would have to root your device to make this work. I didn't try this, since I didn't want to root my device.
2. Record the log from a computer using USB. For this you will need to :
  1. Download and install Android Studio or the standalone SDK tools (https://developer.android.com/sdk/installing/index.html). I already had Android Studio installed, so I have no experience with the standalone tools.
  2. Install the SDK platform tools using the SDK Manager (https://developer.android.com/sdk/installing/adding-packages.html).
  3. Find the adb command line tool (mine was in C:\Users\USERNAME\AppData\Local\Android\sdk\platform-tools).
  4. Enable USB debugging on your device (http://www.howtogeek.com/129728/how-to-access-the-developer-options-menu-and-enable-usb-debugging-on-android-4.2/).
  5. Connect your device to the computer.
  6. Use adb command line tool to record log as described (https://github.com/k9mail/k-9/wiki/LoggingErrors).

To be honest, I didn't use the exact command line from the k-9 wiki. Instead I used this approach:

1. Set up everything on the device (in this case: start K9).
2. Enter `adb logcat -c` to clear any log entries.
3. Enter `adb logcat -v time k9:V "*:S" AndroidRuntime:E > k9-log.txt` to start logging.
4. On the device do whatever has to be logged (in this case: delete mail).
5. Give it a few more seconds so it has time to flush everything to the log file.
6. Stop the adb process using ctrl-c.

Hope that helps.

**Comment by tablet-theo** [comment]
Hello ChrMa,

thanks for the detailed howto. I followed each step exactly but in the end, the k9-log.txt is empty...

I think I will accept the crashes or wait for the next update hopeing it will fix my problem.

Thanks anyway.

**Comment by ChrMa** [comment]
Hello tablet-theo,

since you already installed the Android development tools and drivers and unlocked the (more or less) secret debugging menu in Android, you're basically past the hardest obstacles in obtaining a log. I would suggest trying one more thing before giving up.

With your phone disconnected from your computer, start the `cmd` shell, go to the folder containing the adb executable and  enter `adb devices`. If this is the first time you are using adb since rebooting the computer, you'll see

    List of devices attached
    * daemon not running. starting it now on port 5037 *
    * daemon started successfully *

If the daemon was already running, you'll just see

    List of devices attached

Now unlock your phone, connect it to your computer and wait for ten seconds. Your phone should ask you, if the computer is allowed to use USB debugging, except if you checked the "Always from this computer" checkbox the last time you were asked.

When your computer has been granted access and you enter `adb devices` you should see something like

    List of devices attached
    xxxxxxxx        device

Where  `xxxxxxxx` is an 8 digit hexadecimal number identifying your phone. If instead you get

    List of devices attached
    xxxxxxxx        unauthorized

you didn't give your computer permission to access the phone. In this case disconnect and then reconnect your phone. This will make you phone ask for authorization again.

If everything is set up correctly, try entering  `adb logcat`, which should print a huge amount of debugging info from all kinds of processes on your console. You can stop it with ctrl-c.

Now you can try `adb logcat -v time k9:V "*:S" AndroidRuntime:E` to check, that you get some debugging data from K9 itself. If all you get is

    --------- beginning of system
    --------- beginning of main

even if you play around with K9, you probably need to check the "Enable debug logging" checkbox in the "Debugging" section of K9's "Global Settings".

If everything works, you can try the `adb logcat -c` followed by `adb logcat -v time k9:V "*:S" AndroidRuntime:E > k9-log.txt` sequence as described above. Another possible sequence is

1. Set up everything.
2. Enter `adb logcat -c`.
3. On the device do whatever has to be logged.
4. Enter `adb logcat -d -v time k9:V "*:S" AndroidRuntime:E > k9-log.txt`.

This time adb logcat will terminate on its own, once the whole logcat buffer has been downloaded. 

The first sequence is better for long logfiles, that might be larger than the phone's internal log buffer. The second sequence might be better for shorter logfiles, since it is less likely to lose some lines at the end.

Hope that helps.

**Comment by Zwen23** [comment]
Hi, I saved a log of a k9 crash after deleting a message:
http://www.zwen.de/files/2015-10-07-21-36-37.txt
(Taken with logcat, filtered by "k9").

**Comment by marcelser** [comment]
Same problem here too. When I select mails for deletion in unified inbox (especially when selecting multiple mails) in 99% of the cases K-9 crashes. Here's the output from aLogCat filtered by k9 and AndroidRuntime.

[alogcat.2016-05-19-16-25-16+0200.txt](https://github.com/k9mail/k-9/files/272771/alogcat.2016-05-19-16-25-16.0200.txt)

This issue is really killing my nerves.

**Comment by philipwhiuk** [comment]
Filtering by K9 is removing a significant chunk of the Exception making this harder to debug.

```
10-07 21:34:07.205 E/AndroidRuntime(6219): Process: com.fsck.k9, PID: 6219
10-07 21:34:07.205 E/AndroidRuntime(6219): 	at com.fsck.k9.provider.EmailProvider$SpecialColumnsCursor.getLong(EmailProvider.java:776)
10-07 21:34:07.205 E/AndroidRuntime(6219): 	at com.fsck.k9.fragment.MessageListFragment.computeBatchDirection(MessageListFragment.java:2317)
10-07 21:34:07.205 E/AndroidRuntime(6219): 	at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:3467)
10-07 21:34:07.205 E/AndroidRuntime(6219): 	at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:108)
```

There are missing lines between the 1st and the 2nd detailing the actual exception.

**Comment by marcelser** [comment]
Nope, my log lines are filtered exactly as described in the manual on how top create logs by regex (k9|AndroidRuntime) in aLogcat. You can see in the log I attached that both classes are present. 

Am 19. Mai 2016 23:37:29 MESZ, schrieb Philip <notifications@github.com>:
>Filtering by K9 is removing a significant chunk of the Exception making
>this harder to debug.
>
>```
>10-07 21:34:07.205 E/AndroidRuntime(6219): Process: com.fsck.k9, PID:
>6219
>10-07 21:34:07.205 E/AndroidRuntime(6219): 	at
>com.fsck.k9.provider.EmailProvider$SpecialColumnsCursor.getLong(EmailProvider.java:776)
>10-07 21:34:07.205 E/AndroidRuntime(6219): 	at
>com.fsck.k9.fragment.MessageListFragment.computeBatchDirection(MessageListFragment.java:2317)
>10-07 21:34:07.205 E/AndroidRuntime(6219): 	at
>com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:3467)
>10-07 21:34:07.205 E/AndroidRuntime(6219): 	at
>com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:108)
>```
>
>There are missing lines between the 1st and the 2nd detailing the
>actual exception. The lines are prefixed by 'AndroidRuntime' instead of
>k9 so they are filtered unless the line of the stacktrace actually
>contains one of our classes.
>
>I suspect the same is true to a worse extent in the second case.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/783#issuecomment-220453481

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Kaiten Mail gesendet.

**Comment by philipwhiuk** [comment]
I was commenting regarding @Zwen23 's log - which is the only one that actually appears to have recorded the crash at all.

**Comment by ChrMa** [comment]
No worries, here is a new log taken using K9 5.010 on Android 5.0.1. This one has not been filtered at all. Crash happens on line 8828 (timestamp: 05-21 21:20:23.985).

[k9-log2.txt](https://github.com/k9mail/k-9/files/276008/k9-log2.txt)

**Comment by philipwhiuk** [comment]
Thanks!

```
05-21 21:20:23.985 E/AndroidRuntime(18893): java.lang.IllegalStateException: Couldn't read row 923, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.database.CursorWindow.nativeGetLong(Native Method)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.database.CursorWindow.getLong(CursorWindow.java:524)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.database.CursorWrapper.getLong(CursorWrapper.java:106)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.database.CursorWrapper.getLong(CursorWrapper.java:106)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at com.fsck.k9.provider.EmailProvider$SpecialColumnsCursor.getLong(EmailProvider.java:776)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.database.CursorWrapper.getLong(CursorWrapper.java:106)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.database.CursorWrapper.getLong(CursorWrapper.java:106)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at com.fsck.k9.fragment.MessageListFragment.computeBatchDirection(MessageListFragment.java:2317)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:3467)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at com.fsck.k9.fragment.MessageListFragment.onLoadFinished(MessageListFragment.java:108)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.content.Loader.deliverResult(Loader.java:144)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.content.CursorLoader.deliverResult(CursorLoader.java:109)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.content.CursorLoader.deliverResult(CursorLoader.java:42)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.os.Looper.loop(Looper.java:145)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at java.lang.reflect.Method.invoke(Native Method)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
05-21 21:20:23.985 E/AndroidRuntime(18893): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by cketti** [comment]
Please create a new issue if this is still a problem with K-9 Mail 5.7xx.
