### ISSUE TITLE
Create a FAQ for common issues and solutions

### ISSUE THREAD

**Issue by wmontwe** [thunderbird/thunderbird-android#7879]
Some users may struggle with common issues and solutions that are not well-documented. To improve the user experience and reduce the number of duplicate issues, I propose we create a FAQ section either here in the repository or at a webpage where users have easy access.

**Comment by wmontwe** [comment]
Possible content: 

- https://github.com/thunderbird/thunderbird-android/issues/7866#issuecomment-2133686004
- https://github.com/thunderbird/thunderbird-android/issues/7845#issuecomment-2120591242

**Comment by KillYourFM** [comment]
It was proposed that we continue adding content to the [K-9 Mail FAQ](https://forum.k9mail.app/c/faq/6) until a dedicated section can be created on Mozilla Support or the Thunderbird website. This will help to facilitate replies on Google Play Store and other platforms with limited character counts. 

cketti will grant me administrator access so that I can help, and we can add/edit questions and answers in Notion.

**Comment by wmontwe** [comment]
> It was proposed that we continue adding content to the [K-9 Mail FAQ](https://forum.k9mail.app/c/faq/6) until a dedicated section can be created on Mozilla Support or the Thunderbird website. This will help to facilitate replies on Google Play Store and other platforms with limited character counts.
> 
> cketti will grant me administrator access so that I can help, and we can add/edit questions and answers in Notion.

Then we just need to add a link to our readme and issue templates to point users to [K-9 Mail FAQ](https://forum.k9mail.app/c/faq/6).
