### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by iulko** [thunderbird/thunderbird-android#7918]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

0

### Problem you are trying to solve

Alot of people use the email on phone more like a read only/notification device type usage with sometimes a quick reply to an email. They dont want to delete or move emails by mistake etc because their main device is PC where they organise stuff and have their email rules and filters.

### Suggested solution

I would like to intoduce a read-only mode for IMAP servers.
This would work in a way that only thing that works is sending emails.
Deleting emails, moving them to a different folders etc would not work in this mode.

**Comment by cketti** [comment]
We've discussed this internally and came to the conclusion that we don't want to add a read-only mode.

If you're worried about accidentally deleting a message, you can configure the app to prompt for confirmation before deleting a message. You can find the setting under *Settings → General settings → Interaction → Confirm actions*.

If you're worried about accidentally triggering actions using swipe gestures on the message list, you can disable them under *Settings → General settings → Interaction → Swipe actions*.

If you don't need the archive or spam action, you can change the respective settings to *None* under *Settings → [Account] → Folders* and the archive and spam buttons will disappear from the user interface. 
Please note that the same DOES NOT work for the delete action. If you set the trash folder to *None*, messages will be deleted from the server immediately instead of being moved to the trash folder.

You can also remove the "delete" button from notifications under *Settings → General settings → Notifications → Show 'Delete' button*.
