### ISSUE TITLE
HTML formatting in notifications

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#7955]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

moto g40 fusion

### Steps to reproduce

When we receive a notification with some sort of HTML formatting, in the notification it show's the HTML text as it is without the formatting
![Screenshot_20240617-093947-080](https://github.com/thunderbird/thunderbird-android/assets/147328890/51a42562-c1b3-4d14-bba3-9dcce347c19f)

### Expected behavior

Shows the notification with formatting

### Actual behavior

Shows the notification without formatting

**Comment by cketti** [comment]
Currently the app extracts the preview text shown in notifications from the `text/plain` part. Some senders create broken emails and use HTML in that part. 

In your case it seems to be Markdown (`[This is a link](https://domain.example/path)`). K-9 Mail replaces URLs in the preview with `…`. The closing parenthesis is detected as part of the URL. That's why you end up with `[Proton Mail](…`

Extracting the preview from the `text/html` part already is on our (very long) to-do list. See #5890.
