### ISSUE TITLE
Difference between read and unread e-mails not easily noticeable anymore

### ISSUE THREAD

**Issue by wb9688** [thunderbird/thunderbird-android#7980]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.902

### Where did you get the app from?

F-Droid

### Android version

13

### Device model

moto g52

### Steps to reproduce

1. Open the app.

### Expected behavior

The difference between read and unread e-mails should be easily noticeable.

### Actual behavior

Since the last update, the difference between read and unread e-mail is not as easily noticeable anymore and I have to actively look, which takes a lot more effort, to notice which ones are read and unread, so that is not very great.

**Comment by wmontwe** [comment]
The Material 3 theme in 6.9xx versions is still in alpha state and we're working on fine tuning it.

Did you experience this for the light or dark theme, or both?

**Comment by dom6770** [comment]
I'm on 6.903 and I second this. I can barely see which mail is unread or read. I'm using dark mode:

![image](https://github.com/thunderbird/thunderbird-android/assets/11932291/1559af39-80e3-40bf-a67c-c3db8364aa5d)

**Comment by nclm** [comment]
Just re-adding the two screenshots from #8234 to have a visual reference of how it was solved in K9 compared to current Thunderbird:

**K9 6.804**
![k9 screenshot](https://github.com/user-attachments/assets/7baab7e1-1a5f-456d-87ba-77cbfe3c64c1)

**Thunderbird 8.0b1**
![thunderbird screenshot](https://github.com/user-attachments/assets/0a7de8b7-6b94-4cb6-9bcb-d7a3a8f7835c)

**Comment by nclm** [comment]
Hi, I know this is marked as solved but I still encounter the issue. 

I tried again Thunderbird (now 11.0b2) to see. I’m still stuck with old K9  6.804 because of the low contrast difference between read and unread messages in current Thunderbird.

Screenshots:

<img src="https://github.com/user-attachments/assets/6ee2dcd7-d2f6-4f2b-8bfa-d32b001a9f36" width="350"> <img src="https://github.com/user-attachments/assets/4e440a3c-53d0-4aca-b67a-e1051c034789" width="350">

**Comment by nclm** [comment]
@cketti Hi, sorry for the ping, just writing because you’re the one who marked this as solved. Maybe it was at some point and there was a regression since, or something else got in the way, but as can be seen in the new screenshots above, it isn’t solved as of v11.0b2. Could we reopen the issue? Thanks! :)

**Comment by kewisch** [comment]
Current open issue for this is #8448, please follow there :) We've updated the colors as per design's suggestions but this means some regressions for the message list until we have time to refactor it a bit more.
