### ISSUE TITLE
email content with image can not open and save

### ISSUE THREAD

**Issue by bigger945** [thunderbird/thunderbird-android#813]
### Expected behaviour

Receive a email with a image,k9 look good,with a image in content view and a image in the attachment view. 
But  1.can not open when click open btn(cause the attachment mime type:application/octet-stream)
       2.when long click the image in content view,pop the menu for view or save the image,two func does not work(cause the uri may be correct)
### Actual behaviour

1.the image should be open exactly 
2.when long click the image,the image should be view or open
### Steps to reproduce

1.get a mail with photo in content
2.open k9 to view this mail
3.click the save btn in attachment view/ long click the image in content view to show the menu option for view or open the image.
### Environment

K-9 Mail version:
check out from github 25.9.2015

Android version:
4.3
Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by cketti** [comment]
Those are two different issues.

1. K-9 Mail already tries a lot of things in order to find an app that can view a particular attachment. Especially if the MIME type is `application/octet-stream`. See [AttachmentController#getBestViewIntentAndSaveFileIfNecessary()](https://github.com/k9mail/k-9/blob/da51bdf1b34f49acf1188acdbda654e4b893df2c/k9mail/src/main/java/com/fsck/k9/ui/messageview/AttachmentController.java#L168).
I have no idea why this doesn't work for you. But given that you've managed to build K-9 Mail from `master` I'm hopeful that you can find out and let us know or even provide a fix. 

2. I created issue #818 for this bug.

**Comment by jiang11958** [comment]
which app? you can open a image type is 'application/octet-stream'.
