### ISSUE TITLE
Title wraps within word in "Improve the Experience" screen

### ISSUE THREAD

**Issue by kewisch** [thunderbird/thunderbird-android#8257]
![image](https://github.com/user-attachments/assets/3d5b397c-a0b9-4833-a8f0-a579ff1b4d51)
On more narrow phones like the Fold, the title wraps. I think we should (to an extent) allow the title to shrink so that Thunderbird fits in one line. I'm not sure there is an easy way without forcing the whole text to fit into one line.

**Comment by sens-sens** [comment]
Hi, I'm new to contributing and currently learning Android development.
I believe I can help address this issue. I would like to suggest implementing a solution where the title can shrink proportionally on narrower devices like the Fold, to fit within a single line without affecting the rest of the UI. Would it be okay for me to work on this issue?

**Comment by ryanleesipes** [comment]
@sens-sens please work on it, pull requests welcome!

**Comment by sens-sens** [comment]
The code for the top app bar has inconsistent padding values.

```kotlin
Row(
    modifier = Modifier
        .fillMaxWidth()
        .padding(
            start = MainTheme.spacings.half,
            end = MainTheme.spacings.quadruple,
        )
        .then(modifier),
    horizontalArrangement = Arrangement.Center,
    verticalAlignment = Alignment.CenterVertically,
)
```

Since the row items are arranged to the center, we can reduce the end padding from `MainTheme.spacings.quadruple` (32 dp) to `MainTheme.spacings.half` (4 dp).

This change will provide consistent padding across the app bar while ensuring there’s enough space for the word "Thunderbird."

I've searched for other ways to reduce the size, but as far as I know, those options would modify the theme contents and font size, leading to increased complexity.

Most common foldable phones have a width of about 2.5 inches, so reducing the padding might help fix the issue. On larger screens, there will still be space after the word "Thunderbird" since the items are centered. I tested this in the preview functionality of Android Studio, as I don't have access to foldable emulators.

Can I proceed with this change and create a pull request?

**Comment by wmontwe** [comment]
We could move the title below the icon to give it enought room, the design was optimized for K-9 Mail which is way shorter.

**Comment by cketti** [comment]
We have talked about this internally and decided to
* only display the brand name (Thunderbird), not the app name (Thunderbird Beta),
* use a composable that shrinks the text size if necessary so it fits in the available space.

Future improvements could include displaying the text below the icon on very small/narrow screens. However, we don't want this to be the default.
