### ISSUE TITLE
ThunderBird for Harmony next

### ISSUE THREAD

**Issue by Shura23** [thunderbird/thunderbird-android#8281]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b2

### Problem you are trying to solve

I hope you guys can develop a Harmony next version of ThunderBird. Harmony next is a mobile phone operating system independently developed by Huawei in China, and this system cannot use Android software. Therefore, it is recommended to develop a Harmony next version of ThunderBird.

### Suggested solution

Harmony next can be said to be the world's third independent mobile operating system. The more operating systems, the more fierce the competition between operating systems, which is only good for users, and in the field of mobile operating systems, it has been monopolized by Android and IOS, which is not a good thing for users. If you can, develop a Harmony next version of thunderbird and contribute to the world's third-largest mobile operating system

**Comment by CaidenBlock** [comment]
This seems entirely outside the scope of this project, asking android devs to make an app for a completely different platform with an IDE and documentation only available in Chinese is a monumental ask considering how Mozilla didn't even have the resources to develop an android client from scratch.

**Comment by Shura23** [comment]
> This seems entirely outside the scope of this project, asking android devs to make an app for a completely different platform with an IDE and documentation only available in Chinese is a monumental ask considering how Mozilla didn't even have the resources to develop an android client from scratch.

https://developer.huawei.com/consumer/en/doc/
This is the English version of the Harmony development documentation

**Comment by Shura23** [comment]
> This seems entirely outside the scope of this project, asking android devs to make an app for a completely different platform with an IDE and documentation only available in Chinese is a monumental ask considering how Mozilla didn't even have the resources to develop an android client from scratch.

I'm just making a suggestion. Mozila can decide whether or not to adopt my suggestion based on her own situation. Harmony's development documentation is available in English. This is the English version: https://developer.huawei.com/consumer/en/doc/

**Comment by CaidenBlock** [comment]
> Harmony's development documentation is available in English. This is the English version: https://developer.huawei.com/consumer/en/doc/

Unfortunately, none of the Next documentation is available in English, and none of the English SDK documentation has been updated since API 9. There is no documentation on the required native libraries for NEXT.

Even WeChat is only launching a beta now despite having over a full year of access to NEXT and an actual need for a NEXT app, "developing the native version of WeChat for HarmonyOS NEXT feels like creating the first version of WeChat all over again, with many issues requiring hands-on learning with documentation".

It is unrealistic for android developers to consider this at all considering the differences between the platforms.

And, even if Mozilla did miraculously find the money and people to develop this app despite the fact they couldn't even do that for Android, I can't forsee it could gain *any* market share within China.
