### ISSUE TITLE
Please include release notes in GitHub releases

### ISSUE THREAD

**Issue by williamdes** [thunderbird/thunderbird-android#8294]
### Steps to reproduce

Wait for a new release

### Expected behavior

Have notes
![image](https://github.com/user-attachments/assets/9c9620ab-cf67-432c-8bd2-bd49120e1b85)

### Actual behavior

No more notes
![image](https://github.com/user-attachments/assets/f4035f4b-57e0-47f0-b85f-657fc1b45732)

### Solution

Mark the release as draft and publish it later

**Comment by kewisch** [comment]
Thanks for calling this out. We're working on automating all the things which will include release notes. The release notes are added shortly after the release is published. I know this means it might not be in the email, but this will have to suffice for now. Since we're on it I'm going to close this issue, if you still experience this when the final release is out please let us know!

**Comment by williamdes** [comment]
Solved in https://github.com/thunderbird/thunderbird-android/releases/tag/K9MAIL_8_0b4

Thank you!
