### ISSUE TITLE
Support for resent

### ISSUE THREAD

**Issue by Rzdpai** [thunderbird/thunderbird-android#8402]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b4

### Problem you are trying to solve

https://resend.com/emails

### Suggested solution

https://resend.com/emails

**Comment by kewisch** [comment]
Can you provide more detail on what this is? I can't really see that from the login page so far.

**Comment by Rzdpai** [comment]
> Can you provide more detail on what this is? I can't really see that from the login page so far.

https://resend.com/
resent can send emails that end with a domain name (like rzdpai@rzdpai.top), but it's not an enterprise mailbox, and the official docs say to install the resent plugin.

**Comment by kewisch** [comment]
What would supporting this look like? It sounds like this is a provide that does mass emails via API, similar to sendgrid and others. How would this work from the email client? Are you saying that we should implement a custom account type that would allow sending emails via REST API instead of IMAP?

I think that would be out of scope for the moment, we could revisit this if at some point in the future we have add-ons support and pluggable providers.

**Comment by Rzdpai** [comment]
> What would supporting this look like? It sounds like this is a provide that does mass emails via API, similar to sendgrid and others. How would this work from the email client? Are you saying that we should implement a custom account type that would allow sending emails via REST API instead of IMAP?
> 
> I think that would be out of scope for the moment, we could revisit this if at some point in the future we have add-ons support and pluggable providers.

https://resend.com/docs/introduction

**Comment by kewisch** [comment]
As mentioned, custom account types are out of scope for the moment. Thank you for taking the time to file the issue though!
