### ISSUE TITLE
automatically downloading new mails after 15min doesnt work

### ISSUE THREAD

**Issue by retroHodor** [thunderbird/thunderbird-android#8412]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b4

### Where did you get the app from?

Google Play

### Android version

13

### Device model

moto g54

### Steps to reproduce

1. go to acc settings
2. set receive mails to automatically 15 minutes

### Expected behavior

download new mails after 15minutes

### Actual behavior

doing nothing

**Comment by rezazarchi** [comment]
It might be due to Android's battery optimization rules (e.g., Doze mode) or device resource limitations.
To potentially reduce battery optimization restrictions, you can try going to the App Info settings, then to the Battery section, and selecting Unrestricted. The exact location of this setting may vary across different Android versions.

**Comment by retroHodor** [comment]
I checked all the battery optimization setting , but the setting sare on unlimited. But its still not working! ahhh

**Comment by retroHodor** [comment]
hidden synchronisation has to be activated too. then it works.
