### ISSUE TITLE
Unable to update expired user cert

### ISSUE THREAD

**Issue by hyc** [thunderbird/thunderbird-android#8428]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b3

### Where did you get the app from?

Google Play

### Android version

EMUI 14.2.0

### Device model

Huawei P60 Pro

### Steps to reproduce

1. Remove expired user certificate from Settings / Security / Encryption and Credentials / User credentials
2. Install new certificate
3. Select new certificate in K-9 Account settings / incoming server settings
4. K-9 always stops and says "The client certificate is no longer valid"

### Expected behavior

K-9 should have used the new certificate.

### Actual behavior

![Screenshot_20241028_182800_com fsck k9](https://github.com/user-attachments/assets/77157bcd-0429-4318-a9f1-8801dcf6c27a)

**Comment by hyc** [comment]
I can't get into any other settings now because I tried removing and re-adding the account but the account fails to add and I can't get any further into using the app.

**Comment by cketti** [comment]
Also, you might have to force stop and restart the app for the new certificate to be picked up.

**Comment by hyc** [comment]
The same certificate is working fine in Seamonkey. I've already restarted the app and restarted the phone. No luck.

**Comment by hyc** [comment]
I was able to import settings that I'd exported from a while back, so I can get into the app and turn on debug logs.
[k9mail-logs.txt](https://github.com/user-attachments/files/17547771/k9mail-logs.txt)

Doesn't help much.

**Comment by cketti** [comment]
The log shows that a certificate is expired (`Certificate expired at Sat Sep 14 17:40:38 GMT+01:00 2024 (compared to Mon Oct 28 19:15:36 GMT 2024)`). It happens shortly after loading the certificate chain from Android's key store. So if you're getting the old certificate instead of the new, it's an issue with Android, not the app.

Please note that this is not necessarily the expiration date of the actual client certificate. It could be any other certificate in the chain.

**Comment by hyc** [comment]
OK. Yes I found that I had the old CA cert. Thanks for looking into it. Sorry for the bother.
