### ISSUE TITLE
Clarify when searching locally vs on the server

### ISSUE THREAD

**Issue by shelvacu** [thunderbird/thunderbird-android#8438]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.904

### Problem you are trying to solve

I am trying to search emails (more specifically, find specific emails based on a piece of text I know they contain). When none are found (because by default only local emails are searched) I was confused and thought the search was broken.

### Suggested solution

When searching, show a short description of what is being searched at the top of the search results, e.g. "Local search of folder **Business**, 5 results found." and possibly even a button "Search all emails on server".

Alternatively the search function could always search on the server, but I suspect that would break other workflows

This does use up some screen real estate; it might make sense to have an default-disabled option to hide this text.

**Comment by shelvacu** [comment]
>  I have used the search function to see if someone else has already submitted the same feature request

I tried my best, unfortunately just "search" as a keyword seems to bring up nearly every issue

**Comment by kewisch** [comment]
Can you give 8.0b5 or later a try? The icon has been changed so it is now more apparent how to trigger a server search. Or am I misunderstanding your issue?

**Comment by shelvacu** [comment]
The icon is an improvement for sure, but I'd still hope for something a little more. When I do a search I expect it to search on the server and found the behaviour surprising. However I suspect there are others with the opposite expectations. It would be helpful to explicitly say where/how the search was performed.

**Comment by kewisch** [comment]
The current icon helps differentiate search modes, but clarifying expectations in user documentation or support docs could improve understanding. Ideally, the server content is indexed locally so that the local search will provide all results and server search is the exception. There are a few other issues open on improving the indexing so that this wouldn't be a concern. I'm going to close this issue for the meanwhile since we're not planning to change the icon at the moment, but we can re-evaluate that when indexing is improved. Thanks for taking the time to file this issue!
