### ISSUE TITLE
IMAP Idle Not Working

### ISSUE THREAD

**Issue by Ian1Chong** [thunderbird/thunderbird-android#8461]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Sony Xperia 1iii

### Steps to reproduce

![Screenshot_20241101-123722](https://github.com/user-attachments/assets/34e307d7-6722-4fd4-b2a0-e3044b9da55a)
Even with IMAP IDLE refresh set at every 2 minutes, it does not synchronize and pull in new email for over 5 minutes. With K-9 Email it was instant.

### Expected behavior

With K-9 with IMAP IDLE refresh set at every over 10 minutes, synchronization and pulling down new emails it was instant.

### Actual behavior

Now it takes about 5 minutes for manual refresh (by swiping down on Inbox) before synchronization happens.

**Comment by kewisch** [comment]
What type of permissions do you have granted to Thunderbird? Do you have the alarms and notification permission granted for example? Are you also experiencing this with K-9 Mail 8.0?

**Comment by Ian1Chong** [comment]
Thunderbird has permissions for everything.

![Screenshot_20241102-021413](https://github.com/user-attachments/assets/9669f5c2-3b6c-46ce-9d50-7d02f7e47fdd)

![Screenshot_20241102-021413](https://github.com/user-attachments/assets/75709b1e-1e24-4b85-9b00-1e49644e8174)

**Comment by galmok** [comment]
I just want to pitch in here with my experiences. Fort new, IMAP IDLE has always dropped working sooner or later. I usually have to open the app and force a refresh to get it going again. It doesn't detect that the IMAP connection has been closed.

**Comment by cketti** [comment]
Did you enable push for the inbox under *Manage folders → Inbox → Enable Push*?

If you did and it still doesn't work, please record a debug log and attach it here. See https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors

**Comment by galmok** [comment]
I would like to offer a debug log, but I cannot trigger this problem at will. I havent looked closer to when the connection is lost; I just force a refresh. I have two email programs configured for this exact problem. The other app uses a poll scheme and is reliable, but usually somewhat delayed. K-9 can be nearly instant, or doesn't show emails arriving at all.

And yes, push is enabled; always has been.

**Comment by pvones** [comment]
> Now it takes about 5 minutes for manual refresh (by swiping down on Inbox) before synchronization happens.

Check my issue #8079 _Manual checking for new messages sometimes takes up to 3 minutes_ Isn't it the same?

I can reproduce it almost always when travel and walk the city, using public transport and subway. I have already captured many logs.

**Comment by Ian1Chong** [comment]
Yes, that is what I'm getting.  It will sync and pull down new messages every 5 minutes, even though I've set IDLE connection refresh to 2 minutes. Push/IMAP Idle worked perfectly when it was K-9 Mail.

**Comment by pvones** [comment]
How did you set the Account / Fetching mail / Folder poll frequency? To Never or some time period?

**Comment by Ian1Chong** [comment]
I set it to every 15 minutes, which is the shortest interval. Would a different setting make push mail work like in K-9?

**Comment by pvones** [comment]
I think it somehow conflicts with the push notifications. I had the value 3 hours, now I am testing Never.

**Comment by pvones** [comment]
@cketti Is there any way to check whether the push notification receiver is running? I can make it stop working almost every day on two different devices.

Steps:
1. Connect to home Wi-Fi (for hours, push notifications works)
2. Connect to mobile Internet (push notifications works)
3. After 10 minutes connect to Wi-Fi (push notifications works)
4. After 10 minutes connect to mobile Internet (push notifications stops working)

Since that the push notifications no longer work. You can manually check for the new messages only by the swipe down on Inbox, but when a new email arrives, nothing happens. I enabled the detailed logging, there was no record at the time when the new email was sent and supposed to be received.

The only way to restore the notifications is to go to Settings / Applications / Thunderbird, push the Force Stop button and start the Thunderbird again.

I can reproduce it many times with the 8.1 version.

**Comment by pvones** [comment]
The issue persists in 8.2 too.

**Comment by Ian1Chong** [comment]
Thank you very much @kewisch & @cketti
IManage folders → Inbox → Enable Push has made it work. This has been an anoyance since migrated from K-9. Thank you very much!

**Comment by galmok** [comment]
So, should I open a new ticket regarding IMAP IDLE not working? 

I have IDLE refresh at 24 minutes (default) and push is enabled. 

But I have the frequency for fetching emails set to never. I figured IMAP IDLE supercedes this, right?

**Comment by Ian1Chong** [comment]
No thank you. IMAP Idle now works as it did in K-9. I did not know that I also had go to [Settings] > [Manage folders] > [Inbox] > [Enable Push]

<img width="822" alt="Image" src="https://github.com/user-attachments/assets/3ddbc638-33e5-4519-a266-3e0b68fe79d2" />

**Comment by galmok** [comment]
Ok, but IMAP IDLE still doesn't work for me. Must be a different reason.

**Comment by Ian1Chong** [comment]
Did you try the suggestion from  @kewisch & @cketti ?
[Settings]  →  [Manage folders] → [Inbox] → [Enable Push] like on the screenshot ?

**Comment by galmok** [comment]
I never had it disabled.

**Comment by Ian1Chong** [comment]
These are screenshots of my other related settings if that helps...
![Image](https://github.com/user-attachments/assets/43a75480-436b-4e36-bda8-01c28e0f49aa)
![Image](https://github.com/user-attachments/assets/69f05f66-6566-4b96-a562-ab59d6a51eb8)
![Image](https://github.com/user-attachments/assets/92646afe-5d5a-454a-b98d-276fa544f213)

**Comment by galmok** [comment]
As mentioned, Folder Poll Frequency (I see it in Danish: frekvens for hentning af mails) is set to never, and I have now increased the IDLE connection renewal to 60 minutes from 24 minutes (just tried it at 6 minutes and that wasn't a success).

I don't think this has ever worked for be, and I am now using a different email provider (same problem).

I already had the Alarms $ Reminders enabled. But thanks for the reminder. 

Due to this being unreliable, I have configured Samsungs own email program that polls, just to be sure to get a (delayed) notification that I have unread emails.
