### ISSUE TITLE
Special characters in the account name get replaced with � 

### ISSUE THREAD

**Issue by techmanwalker** [thunderbird/thunderbird-android#8468]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

Google Play

### Android version

Android 14 / LineageOS 21 GSI (custom ROM)

### Device model

Samsung Galaxy A14

### Steps to reproduce

1. Click the pencil button.
2. Switch to an account with special characters in its name, like an accent (e.g. Ángel)
3. Type anything and send the mail to another test device you have access to
4. In the second device, open another email client and open the mail you just sent

### Expected behavior

My name would be shown correctly in the other device (this one was sent using FairEmail)

![IMG-20241101-WA0004](https://github.com/user-attachments/assets/3c4cbbb4-cdd7-47f2-a799-8156173de22d)

### Actual behavior

The Á in the account name gets replaced with a � (this one was sent using Thunderbird for Android)

![IMG-20241101-WA0003](https://github.com/user-attachments/assets/0e368c9f-0837-4817-8694-5a5a0ddb4cf1)

**Comment by kewisch** [comment]
Could you share the full email sources if possible? You may need Thunderbird Desktop to export the email sources. I wonder if this is an encoding issue, or a display issue.

**Comment by TechManWalker** [comment]
Sure, here it is:

https://pastebin.com/NH1F6qHu

**Comment by cketti** [comment]
@Chaphasilor This is a different issue that is caused by the sender not providing a proper `text/plain` part. See also #5890

**Comment by cketti** [comment]
From the posted message source:

```text
From: =?UTF-8?Q?=EF=BF=BDngel_Navarro?= <**hidden for privacy reasons**@gmail.com>
```

`EFBFBD` is the UTF-8 encoding of the replacement character (�). So this character is part of the message and the app is displaying exactly that.

I don't think FairEmail is employing any magic to fix that. It's more likely that it is configured to display the name from your Contacts app instead of the name from the email source. You can configure Thunderbird for Android  to do the same under *Settings → General settings → Display → Show contact names* (this might slow down displaying the message list).

You should also contact the sender and tell them that their client is probably misconfigured.

**Comment by TechManWalker** [comment]
## Ok, I think I found the real problem. 
Turns out that when you use the "Export to Mobile" button, Thunderbird somehow messes up the encoding while **transferring the account names**. This does not happen when adding an account from TB for Android itself because it prompts for the account name after logging in.

After digging in the Edit Identity settings, my name is written with the replacement character instead of the proper Á:

![Screenshot_20241103-162741_Thunderbird Beta](https://github.com/user-attachments/assets/13e01132-bd14-4419-945c-32a403558b38)

So that's exactly what was getting encoded in the emails. After **manually changing the identity name** from there (�ngel for Ángel), the newly sent emails display the sender name correctly.

**P.D:** None of all FairEmail, Gmail or TB for Android/Linux are displaying contact names, I don't even have contacts with email details. They all are showing the name that was encoded into it.

### FairEmail: 
![Screenshot_20241103-163134_FairEmail_1](https://github.com/user-attachments/assets/1a6c3f79-6d5c-4e7e-8a33-c565a07438a0)

### Gmail:
![WhatsApp Image 2024-11-03 at 16 40 31](https://github.com/user-attachments/assets/076c739c-748f-4955-92b8-4658f3573ece)
![WhatsApp Image 2024-11-03 at 16 41 43](https://github.com/user-attachments/assets/49b623f7-0004-4cc4-bcb4-c381ac9c0f34)

### Thunderbird for Linux:
![Captura de pantalla_20241103_163451](https://github.com/user-attachments/assets/5d0eff48-e66d-4bbf-a8fb-824af99db652)
![Captura de pantalla_20241103_163530](https://github.com/user-attachments/assets/e89ae590-e14d-435f-8f07-5d0dceb88c39)

**Comment by cketti** [comment]
Apologies, I missed the fact that it was your display name. Not one from a random message you received.

This was probably caused by a bug in the "Export for Mobile" feature of Thunderbird desktop. See https://bugzilla.mozilla.org/show_bug.cgi?id=1928114
