### ISSUE TITLE
Thunderbird não atualiza com o wifi 

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#8542]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird  / k-9 Mail

### App version

8.1

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Samsung A54

### Steps to reproduce

Acontece quando eu tento atualizar as pastas. Tentei no thunderbird, thunderbird beta e no K9, não estão atualizando. Não sei se esse é o problema, mas as pastas atualizaram nos dados da operadora e no wifi não. Não achei nada falando sobre isso e configuração 

### Expected behavior

Que as pastas atualizem quando eu clicar no ícone de atualizar.

### Actual behavior

Os e-mails não chegam. Não sei se esse é realmente o problema, os e-mails chegam nos dados.

**Comment by kewisch** [comment]
Hi, I'm not 100% sure I understand what the issue is here, would you mind repeating in English?

**Comment by fbiof** [comment]
I used Google Translate. I installed Thunderbird, but it has trouble updating folders. Sometimes the update on cellular data is better than on Wi-Fi. Since it wasn't updated properly, that is, it was searching for emails on the server, I tried installing Thunderbird Beta and K9. They all have this problem when updating. The servers were configured automatically and are working, I don't believe that's the problem.
Fábio Ferreira

12 de nov. de 2024 08:43:39 Philipp Kewisch ***@***.***>:

**Comment by kewisch** [comment]
Can you explain further how you are updating the folders, are you using manual refresh? Or are you expecting push to auto-update the folders? Maybe you could try logging some errors:

https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors
