### ISSUE TITLE
Serious drafts glitch since last update

### ISSUE THREAD

**Issue by kurupted** [thunderbird/thunderbird-android#858]
I'm having an issue where if I create or edit a draft, it saves fine, and then shows up in the folder fine (with a preview of the message body), but when I click it from that folder view, it is blank when it opens. Nothing I can do after that will make it open correctly (ie refreshing the folder). The draft still appears on my other devices (pc) without error. If I make an edit then to the blank message, and it asks me to either save or discard, saving will still overwrite the correct draft, and discard will delete it from the server. If I simply click Back to go back to the folder list, and then open and re-save the draft on my pc, it will refresh  in k9 and I can open it ok. This issue is not happening every time I open drafts, but is often now. Had no issues prior to updating to the new version (a few weeks ago?), and has been happening ever since.

**Comment by kurupted** [comment]
Btw, running Android 4.4.4 on a Droid Maxx.

**Comment by cketti** [comment]
1. What K-9 Mail version are you using?
2. Please use another email client to retrieve the message source of the draft and post it here.

**Comment by kurupted** [comment]
After having not seen the bug in a long time, I encountered it again. Latest version of K-9.

I don't want to post the whole message source publicly. Can I email it to you?

**Comment by kurupted** [comment]
After having not seen the bug in a long time, I encountered it again. Latest version of K-9.

I don't want to post the whole message source publicly. Can I email it to you?

Also, now when I go to my PC and edit and save the draft, the message disappeared from K-9. It's still on the server and in my email client on PC but I can't get it to show back up in K-9 even after clicking Refresh in the folder view.

**Comment by kurupted** [comment]
Update: After clicking Clear Local Messages and refreshing, the messages all appear and work correctly

**Comment by JustAnonymous** [comment]
I understand that this bug is closed, but I am having the same issue as kurupted on K9Mail 5.203 on Android 5.1.1. I compose a draft, then save it. When I come back later to finish, I click on the mail under the drafts folder, the text is gone in the compose window.  However, I can see it fine in thunderbird and in the mail list in K9 just prior to re-opening the compose window.  Should this maybe be re-opened?

**Comment by staples1347** [comment]
I am using K9-Mail 5.206 and when this happens, logcat reports: "The identity field from the draft contains an invalid LENGTH/OFFSET".

I am able to replicate the issue by creating a html draft on an IMAP server in Thunderbird that has a signature, and then open and save the email in k9-mail.  This creates the invalid identity field error.  To then fix the issue, open the email in Thunderbird again and either remove the signature lines from the email or add newlines after the signature.  After that k9-mail will be able to edit and save the draft email without getting an incorrect length error.

**Comment by staples1347** [comment]
It looks like creating any email in Thunderbird with the bottom line set as Preformat will cause this problem.  On my setup, Thunderbird signatures are created with Preformat style so that's why I see the problem with a Thunderbird signature.

This causes k9-mail to set the length identity field to 1 character higher than what the real text length should be.

I have attached a file with an example email from Thunderbird that will cause k9mail to create the off-by-one length value when it makes changes to the email: [draft_email_with_preformat_text.txt](https://github.com/k9mail/k-9/files/951554/draft_email_with_preformat_text.txt)

**Comment by Chris78** [comment]
I also think this should really be reopened, as I'm having the exact same issue with drafts opening blank, if they were edited and saved just before in k9mail. I'm using k9mail 5.6 on LineageOS 15.1, some build from december 2018.

Further, if I have a very large draft mail on the server, it gets truncated by k9 when I open it for editing.

And finally I think there should be an option to cancel editing, i.e. discard the changes, not the whole draft. Imagine you delete something unintentionally and have only the options to discard everthing or save your changes.

I would be very happy to see these issues fixed, because I really like k9mail very much. So, thanks in advance. :)

**Comment by kurupted** [comment]
I second the "cancel changes" option. I hate when I accidentally type a 
letter or something and then have to re-save the draft, which changes 
the timestamp. I use my drafts folder to store various notes and things 
permanently, and I don't want an old note I'm reading to be moved up out 
of order and to lose the original date info.

On January 6, 2019 8:03:39 AM CST, Chris78 <notifications@github.com> 
wrote:

    I also think this should really be reopened, as I'm having the exact
    same issue with drafts opening blank, if they were edited and saved
    just before in k9mail. I'm using k9mail 5.6 on LineageOS 15.1, some
    build from december 2018.

    Further, if I have a very large draft mail on the server, it gets
    truncated by k9 when I open it for editing.

    And finally I think there should be an option to cancel editing,
    i.e. discard the changes, not the whole draft. Imagine you delete
    something unintentionally and have only the options to discard
    everthing or save your changes.

    I would be very happy to see these issues fixed, because I really
    like k9mail very much. So, thanks in advance. :)

    —
    You are receiving this because you authored the thread.
    Reply to this email directly, view it on GitHub
    <https://github.com/k9mail/k-9/issues/858#issuecomment-451744012>,
    or mute the thread
