### ISSUE TITLE
Add an option to move the account buttons in the sidebar back to top

### ISSUE THREAD

**Issue by allo-** [thunderbird/thunderbird-android#8610]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

8.1

### Where did you get the app from?

F-Droid

### Android version

14

### Device model

Pixel 8

### Steps to reproduce

In the new sidebar design, the account icons are always visible on the left, reducing the space in the sidebar for folder names quite a bit. In the old design with the accounts at the top (scrolling out of view when looking for a folder), the space was better used, at least on phones (I did not compare it on table devices).

It would be nice to have an option to use the old design. Then one could either have the accounts to the left (probably useful if you switch between accounts often) or to the top, which is useful if you switch less often and want more space for the sidebar content.

### Expected behavior

Design since 8.0.

### Actual behavior

Previous design.

**Comment by kewisch** [comment]
While I understand that you preferred the old design, maintaining two different drawer layouts and implementations would be quite a bit of work that would take away from other important projects. For those who don't switch accounts often, there is an option to hide the accounts sidebar. For those who do so more often they'd likely keep it enabled and switch as needed. I'd like us to avoid too many settings, as each new settings requires migrations, extra testing for both states, etc.

We're certainly continuing to look at incremental drawer improvements, there are a bunch of things we could do with a little more time, but is not as simple as "make it the way it was before". I appreciate that you've taken the time to file this issue, but since we can't bring back the old design as is I'm going to close this one.

**Comment by allo-** [comment]
I just thought I am probably not the only one (and someone has to open the bug) and as the old implementation is probably still usable, there would only need to be a switch.  
Perhaps you could look into making the current implementation take up less space? What about having the account icons in a rectangle at the top left, and freeing up the space below the rectangle? The current sidebar is mostly empty here, and probably for most people who only have 2-3 accounts.

> For those who don't switch accounts often, there is an option to hide the accounts sidebar.

I was looking for such an option and couldn't find it in the settings or on a long press in the sidebar. Where can I find it? And how do you switch accounts afterwards? I have multiple accounts, but I switch between them only about twice a day and not all the time, so the toggles are a waste of space for me most of the time, but I still need to be able to access them in some way when I need to switch.

**Comment by allo-** [comment]
Oh, how could I have missed that ...

Another idea: What about using the account names as headers for collapsible folder lists? Then you would have all accounts in the sidebar without needing a secondary sidebar to switch between them, could collapse the accounts that are currently not needed, and would have the same amount of space to show the account name as to show the folder names. It would also be closer to Thunderbird on the desktop, which also uses collapsible lists.

**Comment by kewisch** [comment]
We're going to tackle folder hierarchy in 2025, collapsible folder lists and putting the account header on top is certainly something we could consider as part of that to save space. I'll make a note of this while we explore it. I appreciate the suggestion!
