### ISSUE TITLE
Please clarify differences between K-9 and Thunderbird in readmes

### ISSUE THREAD

**Issue by tdbe** [thunderbird/thunderbird-android#8619]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0

### Where did you get the app from?

F-Droid

### Android version

12

### Steps to reproduce

There is a k-9 Fdroid app (pointing to thunderbird page), and there is a Thunderbird Fdroid app ("based on k-9"). When I come to the github projects, there's no info on their relationship.

### Expected behavior

A statement of what is the relationship between k-9 mail and thunderbird, if one is meant to replace the other, if one became the other but is still maintained for legacy sake, etc.

### Actual behavior

No obvious information about what their relationship is with each other. From the point of view of a FOSS user it's very confusing.

Thunderbird FDroid page says: _"based on K-9 Mail"_
K-9 FDroid page says: _"You can find our bug tracker, source code, and wiki at https://github.com/**thunderbird/thunderbird**-android."_

Github of k9 or github of thunderbird, don't explain anything about this.

Is one of them going to be deprecated in the future? Is one of them more up to date? Is one of them taking decisions / features from the other? Is it unidirectional? Bidirectional?

**Comment by kewisch** [comment]
I could take some info from the [FAQ](https://support.mozilla.org/en-US/kb/thunderbird-android-8-faq), how about adding this to the K-9 Mail section in the README? The FAQ is already linked from the README, which might provide an alternative.

---


In June 2022, [K-9 Mail joined the Thunderbird family](https://k9mail.app/2022/06/13/K-9-Mail-and-Thunderbird.html) as the foundation for Thunderbird on Android. Since then, we’ve been updating both apps to give users the same solid experience, so it’s normal to notice that K-9 Mail and Thunderbird look and feel nearly identical. They’re built on the same code, and that’s intentional. You'll notice some features are selectively enabled for Thunderbird as opposed to K-9 Mail, usually when they are simply a better fit for Thunderbird (like the import from K-9 functionality).

If you prefer the robot dog and would like to keep K-9 Mail around, you can find it here:

- [K-9 Mail on Google Play](https://play.google.com/store/apps/details?id=com.fsck.k9&utm_source=thunderbird-android-github&utm_campaign=download-section)
- [K-9 Mail on F-Droid](https://f-droid.org/repository/browse/?fdid=com.fsck.k9)
